### ISSUE TITLE
Inspecting a ProtoFlux node input of type Engine crashes Resonite

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#1855] opened 2024-04-26 09:34 UTC
### Describe the bug?

Making an input of type Engine causes the game to not crash, but in fact close with no warning.

### To Reproduce

Spawn an input of type Engine, inspect the input. Game immediately dies.

### Expected behavior

For the game to not die.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/01cad9cb-46b0-4abb-8081-d2cbd8b3b598

### Resonite Version Number

2024.4.26.10

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Quest Pro

### Log Files

[DESKTOP-QBGCSAQ - 2024.4.26.10 - 2024-04-26 02_27_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15128335/DESKTOP-QBGCSAQ.-.2024.4.26.10.-.2024-04-26.02_27_36.log)

### Reporters

ModernBalloonie

**Comment by Nytra** [comment] 2024-04-26 09:39
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/701

**Comment by art0007i** [comment] 2024-04-26 12:20
also technically a dupe of #1646

**Comment by shiftyscales** [comment] 2024-05-24 21:36
Closing in favour of the existing issues.

**Closed** 2024-05-24 21:36 UTC
Labels: bug, duplicate
