### ISSUE TITLE
User Inspectors only generate correctly for the host

### ISSUE THREAD

**Issue by TheBasementNerd** [Yellow-Dog-Man/Resonite-Issues#2228] opened 2024-06-03 17:08 UTC
### Describe the bug?

When generating a user inspector, either through pulling out a user ref or through the dev tip, the left side of the inspector does not generate for users if they are not the host 

### To Reproduce

Open a user inspector through any method while not the host

### Expected behavior

All users should be able to generate a user inspector that shows a list of all users in the world on the left panel

### Resonite Version Number

2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

Reporting from phone, will add log files after work

### Reporters

TheBasementNerd

**Comment by shiftyscales** [comment] 2024-06-03 17:10
This is a duplicate of #1964.

**Closed by shiftyscales** 2024-06-03 17:10 UTC
Labels: bug
