### ISSUE TITLE
[Headless] Unhandled Exception when a non-builder grabs a builder holding a tool, crashing world rather than kicking the non-builder user

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#479] opened 2023-10-30 10:30 UTC
### Describe the bug?

When a non-builder user grabs a builder holding a tool in a headless session, the world will crash. 

### To Reproduce

Get a user with non-builder permissions in a headless session to grab a user with a tool equipped (such as through the user with the tool wearing an avatar with an enabled grabbable system such as this one found in Kodey's public folder - resrec:///U-KodeyTheNeko/R-c51e67ff-7559-41d1-b48b-c058eb9a13cf)

World should crash and restart

### Expected behavior

World should not crash - the non-builder user should be kicked (the same as the behaviour that occurs when the same situation happens in a session being hosted by a non-headless user)

### Resonite Version Number

Beta 2023.10.20.831

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Headless

### Log Files

[fe2f5942-8df3-47fc-a694-9865a0daee0f - 2023.10.20.831 - 2023-10-30 21_11_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13203923/fe2f5942-8df3-47fc-a694-9865a0daee0f.-.2023.10.20.831.-.2023-10-30.21_11_07.log)

Context starts at line 820, crash at line 841
`21:12:49.355	Failed Validation Element: ID3B200, Type: FrooxEngine.InteractionHandlerPermissions, World: Zuck World 0, IsRemoved: False, IsDestroyed: False, IsDisposed: False, Enabled: True`

`21:12:49.535	Unhandled Exception when updating world: Zuck World 0. State Running, Refresh Stage: ValidatingPermissions, Init State: Finished, SyncTick 4073, StateVersion: 8696`

### Reporters

bredo (Discord: bredo), BigRedWolfy (Discord: BigRedWolfy)

**Comment by Nytra** [comment] 2023-10-30 11:18
Mod to fix it is here https://github.com/Nytra/ResoniteHeadlessToolPermissionKickCrashFix

**Comment by epicEaston197** [comment] 2023-10-30 16:20
This outcome would preferably not happen at all whenever a non builder grabs a builder holding a tool it should just result in the non builder grabbing the builder user without any weird things happening

**Comment by Enverex** [comment] 2023-10-30 23:27
Original report - https://github.com/Neos-Metaverse/NeosPublic/issues/1693

**Comment by sveken** [comment] 2023-11-26 09:49
This pops up daily and gets pretty annoying. Hopefully it can be a quick fix

**Comment by LeCloutPanda** [comment] 2023-11-26 10:02
When ``ToolDequipped`` is called on headless servers it crashes at this code
```css
if (popOff)
{
	Slot slot = tooltip.Slot;
	v = slot.GlobalPosition;
	slot.GlobalPosition = v + b;
	Slot slot2 = tooltip.Slot;
	v = tooltip.Slot.Forward;
	float3 a = base.LocalUserRoot.HeadPosition;
	float3 b2 = tooltip.Slot.GlobalPosition;
	float3 to = (a - b2).Normalized;
	slot2.Forward = MathX.Lerp(in v, in to, 0.25f);
}
```
Solution: Add a check to see if it's a headless is calling this function ``ToolDequipped`` and if it is set ``popOff`` to false.

This issue was fixed with multiple mods and dll edits from the past.

This issue is significant because patrons, who contribute a substantial amount of money for access to the headless feature, face the risk of world/headless crashes simply due to one user mistakenly grabbing another. While it's true that players bear some responsibility for having grabbable systems on themselves, the issue extends beyond individual actions and can be easily reproduced using the game's native features.

Additionally, the problem extends to Workshops/Shows/Streams, where crashes can occur on headless servers if a user without the necessary permissions lifts another user who does have permissions. This situation is seen as impractical from a development standpoint.

Please correct me if I am wrong but this issue has persisted from the past and the fact people are paying for the headless and it can crash with such a simple mistake is unacceptable.

**Comment by ProbablePrime** [comment] 2023-11-26 10:44
The additional information is appreciated, however do keep in mind that pointing exactly in the code where the issue appears to be occurring can be distracting for our Team, I now need to evaluate your solution as well as researching the bug myself, for example your solution might not be applicable/idiomatic/performant etc. and it may take additional work, but I'll take a look.

Thanks!

**Comment by ProbablePrime** [comment] 2024-02-28 10:24
Alright I took a look at this today.

While your popoff fix does correct this particular crash, it's also a good example of not fixing the whole problem. 

When this grab occurs why are we running the permission checks on this tool? 
It is already being held or equipped by another user. 
So why are we trying to evaluate this tool as being owned/equipped by the grabbing user?
Is the grabbing user trying to equip it?
Or Is the grabbing user already registered as having equipped it because it is parented to another user who has it equipped?

These items could surface other bugs in the tools/permission system if left unkempt so those are the items I have to research.

So therefore I think this is in InteractionHandlerPermissions. Which is part of the permission system. 

I'm not entirely familiar with the permissions system but I'm going to take a look through it and consult with Froox when I need to.

If someone wouldn't mind, Can you test this with/confirm if this crash happens when the "Enable Legacy Double Grip Equip" is turned off? 

That will help me validate the exact path we're hitting here, thanks!

**Comment by ProbablePrime** [comment] 2024-02-28 10:29
Immediately after posting this I took a look at: GrabbablePermissions

Compare its Validate function to the tool one:

Grabbable:
````cs
public override bool Validate(User user, Worker worker)
{
    var grabbable = (IGrabbable)worker;

    if (grabbable.IsGrabbed && grabbable.Grabber?.Slot?.ActiveUserRoot?.ActiveUser == user && !CanGrab(grabbable))
        return false;

    return true;
}
```

Tool:
```cs
public override bool Validate(User user, Worker worker)
{
    var commonTool = (InteractionHandler)worker;

    // other users should only ever validate their own tools, not other users
    if (!World.IsAuthority && !commonTool.IsUnderLocalUser)
        return true;

    if (commonTool.ActiveTool != null && !CanEquip(commonTool.ActiveTool))
        return false;

    return true;
}
```

We're not double checking the user property but its available, so I'll PR using it.

If someone can still double check with "Enable Legacy Double Grip Equip" while I work on that, I'd appreciate it, there may be two bugs here.

**Comment by bredo228** [comment] 2024-02-28 10:45
> If someone wouldn't mind, Can you test this with/confirm if this crash happens when the "Enable Legacy Double Grip Equip" is turned off?

This crash occurs when "Enable Legacy Double Grip Equip" is turned off

**Comment by ProbablePrime** [comment] 2024-02-29 08:21
Oh and I was explaining "popOff" to someone, it basically makes the tool come away from your hand when you de-equip it and makes it point up at a 45 degree angle.

Here's my programmer art about what it does:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/8b9e28c6-bf6e-4357-98d1-8367748320e2)

**Comment by ProbablePrime** [comment] 2024-03-01 02:00
This one turned into 3 separate bugs:
- It was possible to equip an already equipped tool
- As the permission cleanup routine for InteractionHandlerPermissions can run on the Host and the User who has the tool, For headlesses who dont have a head. The "LocalUserRoot.HeadPosition" is null because... **headless users do not have heads.**
- The Permission system Was checking all InteractionHandlers even for ones that aren't owned by the user we're running permision checks for.

**Closed** 2024-03-12 19:19 UTC
Labels: bug, crash
