### ISSUE TITLE
LocomotionAnimationSuppressor does not function as intended

### ISSUE THREAD

**Issue by Wolf-Seisenbacher** [Yellow-Dog-Man/Resonite-Issues#2870] opened 2024-09-05 03:26 UTC
### Describe the bug?

Due to the new animation system not allowing feet proxies to be overridden, posers are broken.  The current fix has been stated to turn on "Suppress Feet Simulation" in the settings, or add "LocomotionAnimationSupressor" to the anchor in question.  However neither of these work, and your feet continue to be driven by the procedural animation system while seated.

It should be noted that while "Suppress Feet Simulation" is on, you slide around, as intended, showing it's disconnecting the feet simulation.  However, while seated, your feet get picked back up by the locomotion system and disregard the foot proxy override of the anchor.

### To Reproduce

-Sit on any posing system anchor (Easy seat, or just the cloud home ones), and note the behavior
-Turn on "Suppress Feet Simulation" in settings, and sit back on the seat, note the behavior.  Behavior is the same as if animation  isn't being suppressed.
-Toggle off the legacy settings, go into the anchor, and add "LocomotionAnimationSuppressor" component to the anchor, ensure the checkmark on the box "Suppress Feet Simulation" is checked off.  Sit down, and check the behavior.  Same behavior as previous two examples.

### Expected behavior

While feet animation is suppressed, the anchor's override should take over and allow you to pose your avatar properly.

### Screenshots

![2024-09-05 03 23 43](https://github.com/user-attachments/assets/c23a9d9a-904d-42bb-a839-15e7ce36a4fb)
![2024-09-05 03 24 09](https://github.com/user-attachments/assets/f0e79124-aae4-4082-bb01-5f67c35ee780)

### Resonite Version Number

2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

No log files, however I can run this clean and procure one if it'll help identify this issue

### Additional Context

While it appears the settings were working in the pre-release channel, in live they are not operational.

### Reporters

Wolf Seisenbacher

**Comment by shiftyscales** [comment] 2024-09-05 08:18
Is your issue specifically only with anchors, @Wolf-Seisenbacher? It seems like it may be a duplicate of #2862.

**Comment by shiftyscales** [comment] 2024-09-05 08:19
Actually- it appears this has also been reported in #2859. I'm going to close and merge these issues. Thanks for the report.

**Closed by shiftyscales** 2024-09-05 08:19 UTC
Labels: bug, needs more information
