### ISSUE TITLE
Massive Framedrops since Beta 2024.7.12.1147

### ISSUE THREAD

**Issue by TeknoCatron** [Yellow-Dog-Man/Resonite-Issues#2577] opened 2024-07-14 21:13 UTC
### Describe the bug?

Report on behalf of Chrono_Silverfang as the user does not have and will not use GitHub.
Ever since update Beta 2024.7.12.1147 the user is unable to play the platform without a massive frame drop with lows of 5 frames a second.

The first experience they had was during the sessions "Tekno's Nest <color red>V2.3</color> <color purple>HS</color>"
See Video: https://resonite.theroxden.net/media/video/issues/2024.7.12.1147.mp4
==============================================
Id: S-U-TheRoxDen:42302
Name: Tekno's Nest <color red>V2.3</color> <color purple>HS</color>
Host: TheRoxDen, CorrespondingWorldId: G-TheRoxDen:R-9d5abdeb-667d-456b-920a-a9bec98c3061
URLs: lnl-nat://0c7e40e7c2f541fc837abe89085d76f9/S-U-TheRoxDen:42302
IsExpired: False to Public

Unless the media players are being removed, User is unable to play normal in desktop.
Later on during their tests the noticed the same behavior of the massive frame drops in their home world. Without a mediaplayer even existing.

Frames used to be 120-144 before the updates.

User is using 5G modem as it's the only available networking option in their area.

User has attempted to reach out with this issue through your https://support.resonite.com but was told to go make a GITHUB.

### To Reproduce

N/A

### Expected behavior

Not have to play at 5 frames per second while trying to play the platform.

### Screenshots

https://resonite.theroxden.net/media/video/issues/2024.7.12.1147.mp4

### Resonite Version Number

Beta 2024.7.12.1147

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[HUNTER - 2024.7.12.933 - 2024-07-12 11_40_21.log](https://github.com/user-attachments/files/16228819/HUNTER.-.2024.7.12.933.-.2024-07-12.11_40_21.log)
[HUNTER - 2024.7.12.1089 - 2024-07-12 13_52_04.log](https://github.com/user-attachments/files/16228820/HUNTER.-.2024.7.12.1089.-.2024-07-12.13_52_04.log)
[HUNTER - 2024.7.12.1147 - 2024-07-12 14_49_16.log](https://github.com/user-attachments/files/16228821/HUNTER.-.2024.7.12.1147.-.2024-07-12.14_49_16.log)
[HUNTER - 2024.7.12.1147 - 2024-07-12 15_44_15.log](https://github.com/user-attachments/files/16228822/HUNTER.-.2024.7.12.1147.-.2024-07-12.15_44_15.log)
[HUNTER - 2024.7.12.1147 - 2024-07-12 16_14_14.log](https://github.com/user-attachments/files/16228823/HUNTER.-.2024.7.12.1147.-.2024-07-12.16_14_14.log)
[HUNTER - 2024.7.12.1147 - 2024-07-13 17_17_40.log](https://github.com/user-attachments/files/16228824/HUNTER.-.2024.7.12.1147.-.2024-07-13.17_17_40.log)
[TRD-42300 - 2024.7.12.933 - 2024-07-12 19_52_25.log](https://github.com/user-attachments/files/16228825/TRD-42300.-.2024.7.12.933.-.2024-07-12.19_52_25.log)
[TRD-42300 - 2024.7.12.1147 - 2024-07-12 21_48_20.log](https://github.com/user-attachments/files/16228826/TRD-42300.-.2024.7.12.1147.-.2024-07-12.21_48_20.log)

### Reporters

Chrono_Silverfang, Tekno Catron

**Comment by ohzee00** [comment] 2024-07-14 21:31
In some, not all, I am seeing a interesting case of protoflux nodes rebuilding every second. This correlates to their FPS in the logs, in this case 
`Rebuild: 31.9053 ms, Nodes: 24, Groups: 4`
seems to be the culprit, why only 24 nodes is doing this I have no idea nor where they could be other than on their avatar or otherwise.

**Comment by Frooxius** [comment] 2024-07-14 21:45
1) Did this start specifically with 2024.7.12.1147? Meaning 2024.7.12.933 was fine? If not, what's the previous version that worked fine?
2) What does CPU/GPU usage look like when this is happening?
3) Can you get screenshots of the debug dialog on Engine & World tabs when the framerate is low?
4) I'm a bit confused by the logs. Some seem to be for headless? And the framerate shown in there is significantly higher than 5 FPS. Are these the correct logs?

**Comment by TeknoCatron** [comment] 2024-07-14 22:46
Chrono_Silverfang:
1. 2024.7.12.933 was fine, after the "Before the weekend" updates everything went haywire (2024.7.12.1147).

2. See Screenshot (Cloudhome and Tekno's Nest HS)
CPU at 77% with Media Player, 
![Screenshot 2024-07-14 174109](https://github.com/user-attachments/assets/6c97a277-06d1-43e4-a3a3-1c710f73a93e)
CPU at 41% without Media Player
![Screenshot 2024-07-14 174420](https://github.com/user-attachments/assets/b86f75e4-d5c8-4ded-8f58-1a2e6b9843e6)

3. See Screenshot (See Debug Screenshot made in TheRoxDen by Chrono_Silverfang)
![Screenshot 2024-07-14 173647](https://github.com/user-attachments/assets/00ac6518-ca77-4d96-80ff-5a40b0d465e6)
![Screenshot 2024-07-14 173801](https://github.com/user-attachments/assets/f85c1f38-5b34-4667-bba7-9dca9f280eea)
![Screenshot 2024-07-14 173924](https://github.com/user-attachments/assets/29d6a475-cf83-417e-949e-1d52925dbe88)
![Screenshot 2024-07-14 174007](https://github.com/user-attachments/assets/4bd00628-1998-4b63-8a94-e1a74a41281f)

4. Logs were included for both sides. Hunter would be Chrono_Silverfangs logs. TRD-42300 would be the Headless Logs during the event of the video that was recorded.

**Comment by ohzee00** [comment] 2024-07-14 22:50
I am seeing a max of 42 ms for protoflux rebuild in that debug.

**Comment by shiftyscales** [comment] 2024-07-15 13:00
Can you have the user isolate a few variables to see if we can further narrow down a possible source of the issue, @TeknoCatron?

E.g.:
- Have the user use the -DatabasePath and -CachePath command line arguments to set these to a new location and see if the issues persist while the user is not signed in at all 
https://wiki.resonite.com/Relocate_Resonite_Folders

If that works:
- Have them sign in to that new test database and see if the issues occur

If they do:
- Have the user disable loading into their cloud home and see if the issues occur

If they do:
- Then have the user unfavourite their primary avatar and see if the issues occur

Please let us know if you can further isolate if the issue is related to a specific object / avatar / world, as that makes it a lot easier to diagnose and look into. Otherwise- just running through the above steps in itself would help determine at what level the issue might be occurring.

**Comment by Frooxius** [comment] 2024-07-15 14:29
Does this only happen when the video players are present? I'm a bit unclear on their role in this.

**Comment by shiftyscales** [comment] 2024-07-15 14:37
@TeknoCatron's initial post was a bit confusing, but from my understanding, video players are not relevant, @Frooxius.

Tekno noted:
> Later on during their tests the noticed the same behavior of the massive frame drops in their home world. Without a mediaplayer even existing.

So as far as I can tell, it isn't a relevant factor.

**Comment by Frooxius** [comment] 2024-07-15 16:46
@shiftyscales That makes me even more confused, because they keep providing usage with and without media player even in later posts.

I'd rather @TeknoCatron have clarify this, than try to interpret/assume what they might've meant.

**Comment by TeknoCatron** [comment] 2024-07-15 18:52
Yes, the Media players are most likely the entire issue and we are about to start the requested tests requested by ShiftyScales 5 hours ago.

**Comment by TeknoCatron** [comment] 2024-07-15 19:23
As there was a update a few hours back I advised Chrono not to start the the game through steam but directly from the folder so we keep the version where the issue started, but we are not having the same results at last night with the direct start from folder.

Now I wonder if it's related to the steam desktop option one can select, but we cannot really test that without updating the client as steam forces it. 

So how to proceed to get the issues documented?

**Comment by shiftyscales** [comment] 2024-07-15 19:25
Hmm... I don't really know what all would be different about running from Steam vs. not running from Steam (aside from not having access to some Steam specific features like Steam Networking Sockets).

They should still be able to provide the list of steps requested- but if the issue is not occurring at all, then that suggests the issue might have been elsewhere / was something transient, e.g. if they've restarted their PC since then.

If you aren't able to replicate the issue anymore, I'd recommend that they do update, and keep an eye on things- if the issue persists- it could be looked into further- if it doesn't- this issue could probably be closed for now until there is some certainty on the cause / replication steps, etc.

**Comment by TeknoCatron** [comment] 2024-07-15 20:26
Chrono_Silverfang has started the game through steam as they would normally.
User has updated to version Beta 2024.7.12.1147 and cleared both the Database folder and Cache folder before login.

Tests have been done in the same world around playing and removing the media players and user is no longer at 6-12 frames whenever those are out.

Prior to the issue Chrono_Silverfang did remove just the cache folder due to local storage issues, yet after removing both the Database folder and Cache folder prior to running the game the issue cannot be reproduced, Media players do still drop frames but not more then they normally would do.

Issue at this point could not be reproduced even with 7 people in the session during the test.

**Comment by shiftyscales** [comment] 2024-07-15 22:48
I'm going to close this for now then, @TeknoCatron. If the issue crops back up, either reply here, or make a new issue and it can be looked into further. Thank you for looking into it. :)

**Comment by jligeza** [comment] 2024-09-03 17:26
I am also affected with the frame drops after the mentioned update. My home world suddenly started to lag a lot, sometimes even going below 1 FPS and crashing the Steam VR.

After some tests yesterday (latest version, reinstalled everything, cleared cache), I discovered the media players are the issue. What is interesting, setting them to disabled doesn't solve the problem, I have to remove their slots to fix it.

I could reproduce the issue by simply creating an empty grid space and putting just the videos from my home world in there. The Steam VR would crash if I don't quit the world quick enough. I didn't test yet if I need to put those specific old videos, or if new videos have issues aswell.

I use windows 11 with vive cosmos elite headset, can provide more information if needed.

**Comment by shiftyscales** [comment] 2024-09-03 18:25
That sounds like it may be the same issue as #2845, @jligeza? I'd recommend posting your feedback, and links to content / videos that reliably trigger the issue there.

**Comment by jligeza** [comment] 2024-09-03 18:43
This issue is triggered with any random youtube video I try, they are a few minutes long (songs). I also tried an mp4 video from disk and it didn't cause the issue, so maybe it is youtube specific.

Also, I have a feeling there is some cache working in the background, protecting from crash. When I create a grid world with a youtube video, duplicate it like 15x -> save -> leave just before things go unbearable, and try to re-enter the world multiple times, the FPS drop became softer over time, although still noticeable.

The FPS drop can be then reintroduced by duplicating a video again, or by pasting a brand new youtube video and duplicating it.

**Comment by shiftyscales** [comment] 2024-09-03 18:46
Hmm- I can't say I've really had such issues to the point of crashing personally. I suspect it's probably a case where it might be system-dependent in some way, e.g. depending on the software / codec packs, etc. users have installed.

I have seen some users that momentarily freeze while a video loads- but that doesn't seem to be a universal problem.

**Comment by jligeza** [comment] 2024-09-07 07:49
Yesterday, somebody using a desktop client entered my world and asked why they suddenly have 5 FPS. I had some videos spawned and tried to move them one-by-one to a playlist video player, to have only 1 video at a time. For some reason, my own FPS were stable and high. The FPS problem of the guest was fixed as I deleted the videos, with each video removed giving progressive FPS boost.

So, this problem is not VR specific, and might affect a lot of random people.

**Comment by shiftyscales** [comment] 2024-09-07 19:44
If you can replicate the condition by spawning the videos into a gridspace, I'd recommend doing so, and saving a copy of that world, making it openable by everyone by editing its metadata, and posting the link to that world into #2845 then, @jligeza.

**Closed** 2024-09-07 19:44 UTC
Labels: bug, cannot reproduce, triaged, needs more information
