### ISSUE TITLE
clearing the r-home record does not clear it

### ISSUE THREAD

**Issue by Virerite** [Yellow-Dog-Man/Resonite-Issues#1202] opened 2024-01-20 04:09 UTC
### Describe the bug?

at the request of support i am making this, after following the steps to clear my cloud home's record he bot says that has deleted it but then when i try to sav a new cloud home, it errors out and claims version mismatch, after looking t the log it trying to use the previously deleted record and not finding it, and since it cant find it, its just now completely bugged

### To Reproduce

not sure other than i deleted my home after i made a copy of it and thats where the problems began

### Expected behavior

the bot will not clear it and it will be forever trying to look for it

### Resonite Version Number

2024.1.19.687

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Q2 steam link

### Log Files

[AVA - 2024.1.19.687 - 2024-01-19 16_07_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13996616/AVA.-.2024.1.19.687.-.2024-01-19.16_07_19.log)
[AVA - 2024.1.19.687 - 2024-01-19 17_52_54.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13996617/AVA.-.2024.1.19.687.-.2024-01-19.17_52_54.log)

### Reporters

@Virerite

**Comment by Visteria1** [comment] 2024-01-23 07:34
Yes I have tried this, I ended up deleting the world but before I did I
made a copy of the world, however after deleting copy the issue still
persisted, however rn I just used one of my old worlds as a home, it seems
to not have problems one I set the home to a different world and rebuild
the database. Though trying to generate a cloud home and save it will cause
the sync error to come back.

**Comment by Visteria1** [comment] 2024-01-25 14:05
ill reproduce it for you and send a video showing it later today, i hope
you have a great day and take care

**Comment by Frooxius** [comment] 2024-01-25 15:05
I know what is the cause of this, it's something I meant to fix for a while, because I actually hit this issue too and I haven't had my home syncing for a while.

The problem here isn't that the home doesn't get cleared - it does. But then trying to sync a new one results in a conflict - the new home is technically "older" than the deleted one, so it thinks it's out of date.

There will be a fix in the next build.

**Comment by Frooxius** [comment] 2024-01-26 10:42
This should be fixed in 2024.1.26.617! Let us know if you still run into issues.

**Closed by Frooxius** 2024-01-26 10:42 UTC
Labels: bug
