### ISSUE TITLE
unable to find source of what is driving a blend shape

### ISSUE THREAD

**Issue by aecii** [Yellow-Dog-Man/Resonite-Issues#733] opened 2023-11-19 04:52 UTC
### Is your feature request related to a problem? Please describe.

When you load an avatar, and notice a blend shape is being driven there is no way (that I know of) to see what is driving that specific blend shape. 

You can see for your self if you create an avatar, drive the blend using protoflux, and try to find what is driving it without a mod. 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33306334/994565cf-13ac-4380-a716-92e3fd0c7ae0)

Also see: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/733#issuecomment-1817745789

### Describe the solution you'd like

Native support for finding a drive source. 

### Describe alternatives you've considered

I've been told there is a mod for it called "ShowDriveSource", but I rather learn resonite without mods at least until im familiar with it.  Is it possible to do this?

**Comment by Stellanora64** [comment] 2023-11-19 04:55
Just note there is native support for finding drive sources (press the 3 line button on the field you want to find the drive source to and click open drive source).

It just appears to be missing for blendshapes

**Comment by ScarsTRF** [comment] 2023-11-19 09:59
This is the same as my issue here on #639

**Comment by Frooxius** [comment] 2023-11-21 18:54
Closing as duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/639

Thanks @ScarsTRF!

**Closed by Frooxius** 2023-11-21 18:54 UTC
Labels: enhancement
