### ISSUE TITLE
MultiSegmentMesh Winding not correct (its reversed)

### ISSUE THREAD

**Issue by AegisTheWolf** [Yellow-Dog-Man/Resonite-Issues#1994] opened 2024-05-07 00:48 UTC
### Describe the bug?

When creating a MultiSegmentMesh, the winding of the mesh is backwards nothing changes its winding ( changing the point positions or its radius to negative values)

### To Reproduce

Simply create a MultiSegmentMesh using the components or find it pre-made under 
Resonite Essentials>Assets>3D Models>Procedural Meshes>Stripe, Segment, and Wire Meshes folder.

### Expected behavior

The winding should be correct without having to bake and reverse the winding afterward.

### Screenshots

![2024-05-07 00 39 24](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65252793/1fe61270-e88c-4abe-a8df-22a0807d6812)

### Resonite Version Number

Beta 2024.5.4.678

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Vive Pro Eye

### Log Files

Let me know if a log file is required for this issue.

### Reporters

Aegis_Wolf

**Comment by Frooxius** [comment] 2024-05-07 06:03
Why are you using negative radius?

Negative radius essentially "inverts it", so this is technically correct behavior for that.

**Comment by AegisTheWolf** [comment] 2024-05-07 18:25
> Why are you using negative radius?
> 
> Negative radius essentially "inverts it", so this is technically correct behavior for that.

What I meant is regardless if it is a negative radius or not it is reversed in its winding.
@Frooxius sorry for the confusion

**Comment by shiftyscales** [comment] 2024-05-07 18:36
As indicated by Aegis- even if the radius is correct (positive), the winding is reversed.

Setting a negative radius also doesn't un-flip/reverse the winding like your post would suggest, @Frooxius.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/6554b627-0203-4cbf-ab3c-ed7eecea466e)

**Comment by Frooxius** [comment] 2024-05-07 18:41
Ah I see, thanks. I got a bit confused, because the first provided screenshot has negative radius used.

I'll  need to have a look.

**Comment by AegisTheWolf** [comment] 2024-05-07 23:21
> Ah I see, thanks. I got a bit confused, because the first provided screenshot has negative radius used.
> 
> I'll need to have a look.

one of the segment radius is negative, the other two are positive.

**Comment by shiftyscales** [comment] 2024-05-07 23:26
> > Ah I see, thanks. I got a bit confused, because the first provided screenshot has negative radius used.
> > I'll need to have a look.
> 
> One of the segment radius is negative, the other two are positive within the screenshot.

And in my case, both radius values are positive. I had even tried using different positions for each of the points just to see if that were somehow related- but it didn't seem to be- no matter how I configured them the winding was reversed.

**Comment by Frooxius** [comment] 2024-05-07 23:29
> > > Ah I see, thanks. I got a bit confused, because the first provided screenshot has negative radius used.
> > > I'll need to have a look.
> > 
> > 
> > One of the segment radius is negative, the other two are positive within the screenshot.
> 
> And in my case, both radius values are positive. I had even tried using different positions for each of the points just to see if that were somehow related- but it didn't seem to be- no matter how I configured them the winding was reversed.

Yes, but you made your comment after mine, so I couldn't have taken that one in consideration.

**Comment by shiftyscales** [comment] 2024-05-07 23:37
I'm aware, Frooxius - that was in reply to Aegis, letting him know where the issue is at/that it occurred across all permutations of the radius/segment positions I tested.

**Comment by Frooxius** [comment] 2024-09-16 12:10
Fix merged in 2024.9.16.715, thanks!

**Closed by Frooxius** 2024-09-16 12:10 UTC
Labels: bug, triaged
