### ISSUE TITLE
audio nodes

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#1218] opened 2024-01-22 05:38 UTC
### Is your feature request related to a problem? Please describe.

i'm thinking of ways to play with audio like sstv encoders/decoders, pitch shifting, tempo nodes ect
something that we can use to screwe around with audio effects too.

### Describe the solution you'd like

nodes to play with and manipulate audio, and possibly have sstv nodes aswell.

### Describe alternatives you've considered

crap ton of mods lol. 

but in all serousness mods would be doing the node things so i guess mods would be a alternitive?

**Comment by charlie-sans** [comment] 2024-01-22 05:41
would also be great if we could get some nodes to allow the creation of music apps inside resonite, like ableton or fl studio

**Comment by charlie-sans** [comment] 2024-01-22 05:48
btw sorry about the way i phrased the first message, i was decoding some sstv test transmitions on my computer to setup the software i'm using, had to type slow to not screw it up lol

**Comment by ohzee00** [comment] 2024-01-22 05:51
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/567 Your issue might be a duplicate of this, or at the very least, require 567 first

**Comment by charlie-sans** [comment] 2024-01-22 05:52
hmmm it sounds like both are happening, it's kind of a dupe but also requires 567
it's tough to say though

**Comment by charlie-sans** [comment] 2024-01-22 05:53
this also kinda hits #1217 aswell

**Comment by Frooxius** [comment] 2024-01-22 07:18
This is already covered by https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/567

Closing this one as duplicate.

**Closed by Frooxius** 2024-01-22 07:18 UTC
Labels: enhancement
