### ISSUE TITLE
Favorite world highlight not working 

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#596] opened 2023-11-09 15:10 UTC
### Describe the bug?

It's not pink so you can't tell if it's favorited or not 

### To Reproduce

Favorite a world it doesn't change the icon

### Expected behavior

It to have pink highlights so you know it's favorited

### Screenshots

![20231109_160905](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61125650/eb8cf5fc-db11-477e-a58e-9b7a52d4a19d)

### Reporters

I tried finding a report about this issue on here but I couldn't find another yet

**Comment by JackTheFoxOtter** [comment] 2023-11-09 15:11
Duplicate of #287 and #503

**Closed** 2023-11-09 15:13 UTC
Labels: content
