### ISSUE TITLE
Button tooltips!

### ISSUE THREAD

**Issue by Mr-Mumbles** [Yellow-Dog-Man/Resonite-Issues#3007] opened 2024-09-26 08:21 UTC
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I forget what each button does or component slot. (I'm very forgetful and don't play often.)
Which either means bothering another person, scanning through a probable-prime tutorial (if I have the patience to go back to that one little part in a vid where he explains that thing I need to know), or using the wiki or discord.

### Describe the solution you'd like

Just a few words that pop up when hovering over a button (or component if you are feeling adventurous, I understand this is a lot of work lol, there's lots of stuff) so that I can read "insert parent above" or "Delete" or even "takes x as input, outputs y"

### Describe alternatives you've considered

Linking to relevant tutorials.
Linking to wiki
A huge chatbot trained on Resonite documentation!
Me doing what everyone else does and remembering what does what, and putting more time into the game so this won't be an issue lol.

### Additional Context

Most of the icons are very simple and go quite far at explaining what they do, but still! You can never underestimate the depths of  stupidity some people possess (such as yours truly).

### Requesters

Mr_Mumbles

**Comment by ProbablePrime** [comment] 2024-09-26 08:31
Thanks for making an issue, this is however a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/94 so I will be closing it.

**Closed by ProbablePrime** 2024-09-26 08:31 UTC
Labels: enhancement

**Comment by Mr-Mumbles** [comment] 2024-09-26 08:36
Guh, very sorry! I did try searching through the issues, but I guess I didn't look very hard. My bad!
