### ISSUE TITLE
User creatable, Reusable protoflux functions

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#2785] opened 2024-08-20 04:42 UTC
### Is your feature request related to a problem? Please describe.

Frequently one has to re-write basic blocks, sometimes between projects, but sometimes many times within the same project.  A mechanism for code re-use would be revolutionary

### Describe the solution you'd like

A working solution to this problem would:

1. allow users to create reusable blocks with arbitrary numbers/types of inputs and zero or at least one output
2. make use of references, so that if the function is altered, these changes easily propagate to its users within the same context.  I envision this acting like when, for example, an avatar uses the same material on more than one mesh, the existing reference mechanics work well.
3. has some mechanism for handling, or at least alerting users to, cases where the call signature is mismatched (likely already covered by existing null/not null nodes, however it'd be nice if there were some highlight)

As a possible suggestion, if it helps discussion flow, we could achieve this through the introduction of:
a) customizeable inputs on the dynamic impulse receiver nodes
b) introduction of a "dynamic impulse return" node, require that the incoming flow(s) are all from dynamic impulse chains

### Describe alternatives you've considered

there's likely many ways to approach this problem, but a solution to this need is, in my opinion, essential quality of life

### Additional Context

I did check if there was an existing ticket for this, I didn't find any but it wouldn't surprise me if this exists already, which I'd like to apologize in advance for

### Requesters

zangooseoo

**Comment by AmasterAmaster** [comment] 2024-08-20 04:49
Another alternative currently is the advent of custom nodes made by the community. At least that is the way how I distribute and reuse my code and functions to others in a nice package. (The alternative before that was making a red print cube and sharing that, but of course requires red print to open)

**Comment by shiftyscales** [comment] 2024-08-20 04:59
What you are asking for is nested nodes, so this issue is a duplicate of #564. Thanks for looking for existing tickets first. :)

**Closed by shiftyscales** 2024-08-20 04:59 UTC
Labels: enhancement
