### ISSUE TITLE
[C# 11 Support] Laser grabbing of the dash and other elements does not work unless you grab with both controllers

### ISSUE THREAD

**Issue by Geenz** [Yellow-Dog-Man/Resonite-Issues#2107] opened 2024-05-27 15:38 UTC
### Describe the bug?

Note: This issue, and others with the `C# 11 Support` milestone, is not testable in a public build of Resonite.  No we are not distributing that build yet.  This is for tracking purposes only.

When attempting to grab an object with a laser with the default grab mode, I am unable to grab the object unless I push the grip button on both controllers.

Using ProtoFlux I am able to confirm that inputs are being registered on either controller when the grip buttons are pressed.  However laser grabbing is not functional when only one is pressed.

Physical/palm grab is unaffected and works as expected.

### To Reproduce

Using a C# 11 build of FrooxEngine, after your dash has loaded in VR attempt to grab the dash with just one hand using your lasers.  This will fail until you grip the other controller as well.

### Expected behavior

Laser grabbing to work with the default grab mode.

### Resonite Version Number

N/A - Internal C# 11 build.

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Quest Pro

### Log Files

<snip />

**Comment by BlueCyro** [comment] 2024-09-14 23:28
It looks like the cause of this was due to the way C# 11 optimizes delegates. Since it was assigning them to a hidden, compiler-generated class, the assembly post processor couldn't figure out that those delegates' methods needed `[SyncMethod]` attributes. 

I've pushed changes to the csharp-11 branch that fix the post processor, let me know if this is still a problem.

**Comment by Frooxius** [comment] 2024-09-16 12:09
Merged the fix in 2024.9.16.715, thanks!

**Closed by Frooxius** 2024-09-16 12:09 UTC
Labels: bug, triaged
