### ISSUE TITLE
Write or create dynamic variable node can create multiple copies of the dynamic variable component

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#112] opened 2023-10-14 00:51 UTC
### Describe the bug?

not sure exactly what the full context here is, but I believe it is firing for every user in some cases, and subsequently creating a new component on the target slot for all users, instead of only creating one

### To Reproduce

use "Write or create dynamic variable" with more than one user present, on a flow that includes all users

### Expected behavior

only one component created on the target slot

### Resonite Version Number

2023.10.13.202

### What Platforms does this occur on?

Windows, Linux

### Reporters

zangooseoo

**Comment by Frooxius** [comment] 2023-11-08 18:49
This is too vague. I don't know what "Flow that includes all users" means exactly.

Having screenshots of setup, detailed steps and ideally reproduction item would help a lot.

**Comment by shadowpanther** [comment] 2023-11-08 20:19
So what I'm reading here is if several users try to Write or Create a variable at the same time, each user doesn't see the variable existing and creates their own copy, then all those create diffs are synced between users and you end up with many copies.

The solution is not running the same event on every user at the same time.

**Comment by gentlecolts** [comment] 2023-11-08 20:50
> The solution is not running the same event on every user at the same time.

While this might seem like an obvious answer from my toy reproduction case, "write or create dynvar" nodes might be used as part of a longer chain that, for one reason or another, does need to be localized.

**Comment by shadowpanther** [comment] 2023-11-08 20:56
DynVars are (almost) never localized. And creating slots and components is never localized.

**Comment by Frooxius** [comment] 2023-11-08 21:32
I see. Yeah @shadowpanther is correct here, you're technically telling the system to make a variable for each user, so it's behaving as expected.

The solution to that is pretty much... don't tell it to do that. 

You'll need to structure your system so it creates those variables ahead of time on just one user and then have multiple user's update it. That suggests more issue with the setup - generally you don't want to fire these things at multiple users, because you'll cause conflicts anyways. 

I'm closing this one as not bug.

**Closed by Frooxius** 2023-11-08 21:32 UTC
Labels: bug
