### ISSUE TITLE
New contact session notification notifies you when the user starts in local home

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2035] opened 2024-05-14 16:52 UTC
### Describe the bug?

New contact session notification notifies you when the user starts in local home

### To Reproduce

1. Add someone as a contact
2. Make sure you have the new contact session notification bare minimum is toast
3. have the added contact start Resonite
4. You notice that you still received the notification along with the session name (which is likely "local")

### Expected behavior

New contact session notification should not notify me of someone starting in their local home 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/a2e31be1-8336-4cf9-839c-ed2efdc3e07f)

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.5.7.505 - 2024-05-17 15_21_03.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15358290/DESKTOP-DAN95E7.-.2024.5.7.505.-.2024-05-17.15_21_03.log)

### Additional Context

due to how similar new contact session notification is this could potentially also affect the new public session notification as well

### Reporters

@epicEaston197

**Comment by Nytra** [comment] 2024-05-14 17:00
logs are always required

**Comment by epicEaston197** [comment] 2024-05-14 17:19
> logs are always required

okay I'll get them and add them to the issue
my head moves at a mile a minute and I just wanted to report the issue before I forgot

**Comment by Frooxius** [comment] 2024-05-17 19:12
How is the Private session started? 

Can you see the Private session in the Contacts list shortly after it's started?

**Comment by epicEaston197** [comment] 2024-05-17 19:14
> How is the Private session started?
> 
> Can you see the Private session in the Contacts list shortly after it's started?

In the contacts list it is always hidden but I receive the notification for it starting

**Comment by Frooxius** [comment] 2024-05-17 20:25
Is this specifically for the Local home? Or does this happen for other sessions too?

How are the users on the other end starting the Private session? Can you provide reproduction steps for that?

**Comment by epicEaston197** [comment] 2024-05-17 21:15
>Is this specifically for the Local home? Or does this happen for other sessions too?

I'm pretty sure I've seen it happen to other worlds besides local

>How are the users on the other end starting the Private session? 

Local home for example it starts as private but I get the notification still so it might be because someone starting a private session as private to begin with

>Can you provide reproduction steps for that

I'm not sure the replication steps that I provided should work

1. Add someone as a contact
2. Make sure you have the new contact session notification bare minimum is toast
3. have the added contact start Resonite
4. You notice that you still received the notification along with the session name (which is likely "local")

I've also attached log files it's a little big because I was just playing as normal but as soon as the issue came up I immediately closed the game

**Comment by epicEaston197** [comment] 2024-05-17 22:58
Alright I tweaked the issue with a new discovery this only affects the local home

**Comment by Nytra** [comment] 2024-05-17 23:34
Probably related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1359

**Comment by epicEaston197** [comment] 2024-05-18 00:59
> Probably related to #1359

The thing is if I click on the notification it's immediately set to private

**Comment by ProbablePrime** [comment] 2024-05-18 05:01
I'm going to treat this as a duplicate of #1359 because sessions like this should not be producing notifications like that.

**Closed by ProbablePrime** 2024-05-18 05:01 UTC
Labels: bug, needs more information
