### ISSUE TITLE
SpaceMouse Support

### ISSUE THREAD

**Issue by MistressPlague** [Yellow-Dog-Man/Resonite-Issues#2469] opened 2024-07-04 02:05 UTC
### Is your feature request related to a problem? Please describe.

It would make handling models much easier, especially in desktop which is greatly lacking in rotation control currently

### Describe the solution you'd like

Using the spacemouse for rotating a held object, zooming it, etc all according to the standard spacemouse control scheme

### Describe alternatives you've considered

For desktop use, there really isn't a better solution to this issue. A mouse is only 4 axis. SpaceMouse was made to solve that.

### Additional Context

Most 3D tools use it, and with resonite being pretty much a game engine editor, it would make handling models much easier.

### Requesters

kannadev / MistressPlague

**Comment by MistressPlague** [comment] 2024-07-04 02:10
for context, i am not referring to third person.
Rotation and zoom, aka E+mouse movement and scroll wheel operations, but with much more precision thanks to the spacemouse

**Comment by lxw404** [comment] 2024-07-04 02:29
Possibly a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/598.

**Comment by MistressPlague** [comment] 2024-07-04 05:26
> Possibly a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/598.

It is not, as I am not referring to third person.

**Comment by ProbablePrime** [comment] 2024-07-04 07:07
When we integrate the space mouse, we'll make it general and applicable to as many situations as we can. 

To help with the communication here, I have renamed 598 to indicate this and we'll be closing this as a duplicate for 598.

**Closed by ProbablePrime** 2024-07-04 07:07 UTC
Labels: enhancement
