### ISSUE TITLE
Color Mask (And some other mats) dont use transparency properly/behave weirdly

### ISSUE THREAD

**Issue by Lynn-Weiskopf** [Yellow-Dog-Man/Resonite-Issues#1136] opened 2024-01-13 01:02 UTC
### Describe the bug?

I'm trying to use a color mask to make a psuedo mii maker world in resonite, so i dont have to make multiple textures for color variations, and i cant seem to get transparency working, and the texture is setting the alpha to 1 on any value that >0

### To Reproduce

1. create a color mask (spec or metal)
2. Place semi-texture in ColorMask section of material
3. place material on any 3d model
4. experience sadness
(this happens regardless of if you check the transparent box)

### Expected behavior

i expected the alpha on the texture to be visualized properly through the material with transparency (when checked)

### Screenshots

![2024-01-13 00 34 23](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/122935457/6a3826c7-c8ba-422b-b346-f9a7f80eb2c5)
![2024-01-13 00 52 50](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/122935457/0dd7e1af-586d-48c7-8ac6-5351bebdab55)

### Resonite Version Number

2024.1.13.8

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3 through VD

### Log Files

[Desktop-40EPB - 2024.1.12.1336 - 2024-01-12 17_45_15.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13925314/Desktop-40EPB.-.2024.1.12.1336.-.2024-01-12.17_45_15.log)

### Reporters

MilkGalaxy

**Comment by lxw404** [comment] 2024-01-13 05:02
Possible duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/887

**Comment by Lynn-Weiskopf** [comment] 2024-01-14 01:39
duplicate of #887, sorry!

**Closed** 2024-01-14 01:38 UTC
Labels: bug
