### ISSUE TITLE
Opensource Protoflux Binding Generator for Efficient Plugin Development

### ISSUE THREAD

**Issue by Xlinka** [Yellow-Dog-Man/Resonite-Issues#918] opened 2023-12-17 13:58 UTC
### Is your feature request related to a problem? Please describe.

Developing plugins for users and companies is significantly hindered by the absence of a publicly available binding generator. Currently, creating bindings manually is not only time-consuming but also prone to bugs and crashes.

### Describe the solution you'd like

Introducing an open-source binding generator integrated as a csproj (C# project file). This generator would automatically build bindings for all items within a designated folder (suggested name: "protoflux") as part of the solution build process. The outcome would be the automatic generation of bindings for nodes, which are then included in the output DLL..

### Describe alternatives you've considered

An attempt was made to create a custom csproj within the solution that activates a source generator during the build process to produce node bindings. However, this effort was not successful.

### Additional Context

Developing third-party plugins within an IDE is a challenging task, especially without supporting documentation or tools. The proposed binding generator aims to streamline this process, reducing development time and increasing efficiency.

**Comment by Frooxius** [comment] 2023-12-17 19:31
This is a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/37

**Closed by Frooxius** 2023-12-17 19:31 UTC
Labels: enhancement
