### ISSUE TITLE
Add wire cutting projection to protoflux tool in desktop mode

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2371] opened 2024-06-21 00:16 UTC
### Describe the Underlying Issue

When you're in desktop mode you can only cut wires if you're snapped onto the node in UI align mode trying to do otherwise just results in the red wire for cutting protoflux wires originating from the tip of the tool rather than the desktop reticle

### To Reproduce

Try cutting protoflux wires in desktop mode without snapping onto the nodes

### Expected Behavior

The red wire for cutting the protoflux wires should originate from the desktop reticle rather than the tool tip itself

### Screenshots / Video

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/eae68451-6400-44c4-9276-38e6677dfc28

### Reporters

@epicEaston197

**Comment by art0007i** [comment] 2024-06-21 00:51
dupe of #505

**Closed** 2024-06-21 01:46 UTC
Labels: duplicate, enhancement
