### ISSUE TITLE
Disable jiggle bones at low fps

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Yellow-Dog-Man/Resonite-Issues#1326] opened 2024-02-10 19:34 UTC
### Is your feature request related to a problem? Please describe.

At low fps, jiggle bones become very unstable, potentially causing a problem for photosensitive users.

### Describe the solution you'd like

At the threshold of stability, (wherever that is) disable jiggle bones locally.

### Describe alternatives you've considered

While this is possible using protoflux, it can add redundant code. Additionally, not all users will have the knowledge or experience to do or know to do it.

### Additional Context

I'm not an expert on photosensitive epilepsy.

### Requesters

@EmergencyTemporalShift

**Comment by gentlecolts** [comment] 2024-02-10 23:04
Honestly not just a photosensitivity issue.  Disabling them at low fps could also be an aid to performance as well.  I feel like this topic is familiar though, maybe a mod exists or it's been brought up in the past?

**Comment by ProbablePrime** [comment] 2024-02-11 01:08
Our current plans are a little different in this area.

Instead of disabling them at Low FPS we'd rather spend the time optimizing them so that they perform better. 

Due to this it is unlikely that we'll be implementing this specific idea but I will leave the issue open just in case other team members wish to take an alternative angle.

Thank you!

**Comment by TisFoolish** [comment] 2024-02-11 01:24
> Instead of disabling them at Low FPS we'd rather spend the time optimizing them so that they perform better.

Optimizing it further is great, but you'll never reach a point in which Res will always be running at above 20 fps in all situations on all types of hardware. It's impossible.

**Comment by ProbablePrime** [comment] 2024-02-11 01:26
We'll be trying our best. Maybe we'll revisit this after the optimizations are done.

**Comment by JackTheFoxOtter** [comment] 2024-02-11 01:33
> > Instead of disabling them at Low FPS we'd rather spend the time optimizing them so that they perform better.
> 
> Optimizing it further is great, but you'll never reach a point in which Res will always be running at above 20 fps in all situations on all types of hardware. It's impossible.  

The issue isn't that the framerate drops too low, the issue is that the dynamic bone simulation isn't stable at low framerate. But that should be a fixable issue by improving the simulation math.

**Comment by Frooxius** [comment] 2024-02-12 16:43
I agree with Prime here. 

isabling them isn't really the approach we would take to resolve the problem.

As a general rule we try to not "mask" bugs like this - instead our approach would be to resolve the root issue instead.

In this particular case, the root issue is that they jiggle at low FPS - that is something we want to fix, so it doesn't happen in the first place, but they handle low FPS more gracefully. 

I'm going to close this issue, since this particular course of action isn't something we plan (and we discourage making issues about specific solutions to a problem, rather than a problem itself in our guidelines: https://github.com/Yellow-Dog-Man/Resonite-Issues).

You're free to open a new issue that focuses on the problem.

**Closed by Frooxius** 2024-02-12 16:43 UTC
Labels: enhancement

**Comment by EmergencyTemporalShift** [comment] 2024-02-12 16:46
Would the new issue be considered a feature or bug report?

**Comment by shiftyscales** [comment] 2024-10-03 21:48
I just discovered #154 which is a much earlier reported instance of this issue- I've renamed it to focus on the underlying issue of physics simulation of dynamic bones being unstable under low FPS conditions.
