### ISSUE TITLE
Create Empty Slot Protoflux Node

### ISSUE THREAD

**Issue by scrapSavage** [Yellow-Dog-Man/Resonite-Issues#2402] opened 2024-06-25 20:17 UTC
### Is your feature request related to a problem? Please describe.

It can be very annoying to have to make a template slot of an empty slot for certain projects that involve a lot of variables or need to just quickly spawn some objects to parent other objects under. Currently to achieve this you need to add an empty slot to your creation to be able to create empty objects with Protoflux.

### Describe the solution you'd like

A Protoflux node that allows you to create an empty slot with inputs for Name, Parent, Tag, Position, Rotation, Scale, and Order Offset that would output the slot it creates.

### Describe alternatives you've considered

Using a template system.

### Additional Context

Ideally the defaults for each input would be:
Name - Empty Slot
Parent - Root Slot
Tag - null string
Position - [0; 0; 0]
Rotation - [0; 0; 0; 0]
Scale - [1; 1; 1]

### Requesters

scrapSavage, ShadowX, LeCloutPanda

**Comment by Zyzyl** [comment] 2024-06-25 20:28
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/808

**Closed** 2024-06-25 21:13 UTC
Labels: duplicate, enhancement
