### ISSUE TITLE
Audio lost on Device Change/disconnect

### ISSUE THREAD

**Issue by CaelThunderwing** [Yellow-Dog-Man/Resonite-Issues#474] opened 2023-10-30 02:14 UTC
### Describe the bug?

im Honest not sure if this is a Resonite Issue,  because it seems partially related to "maybe" SteamVR. but if at anytime my quest Sleeps or i exit Virtual Desktop and return, theres no sound and i cant restore it by re-selecting the correct (or any) sound device. 

im not 100% putting this Soly AS a virtual Desktop issue, because in windows i have working sound otherwise. this has atleast been an issue since Resonite's Launch, but not prior (this wasnt n issue in Neos nor is this n issue in other VR Platforms.)

### To Reproduce

Launch SteamVR after Virtual Desktop connect (Quest 2)
Launch Resonite. 
Upon any world is loaded, Exit Virtual Desktop on the Quest end.
Relaunch Virtual Desktop on the Quest end, and audio output is 100% lost. (it still has working Mic input)

### Expected behavior

Audio Not breaking upon Reconnect, 

### Resonite Version Number

2023.10.19.620

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Quest 2

### Log Files

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13200086/Player.log)

### Reporters

Discord: caelthunderwing
Resonite: CaelThunderwing

**Comment by Redd56** [comment] 2024-03-11 03:12
can confirm this still happening, it seems to be something to do with an audio device disconnecting, when an audio device reconnects it seems to bugger up the audio, causing some as you experience to not work but also some to still work but with "mixed" results, (some things being normal sounding others with large amounts of gain, and some others in mono without spacial audio)
it effects me heavily as my mic is also my audio output and it randomly disconnects, causing me to have to reboot resonite quite frequently

**Comment by CaelThunderwing** [comment] 2024-03-11 11:59
only recent started trying w/ the recent-ish SteamLink app inplace of Virtual Desktop, No change in behavior.

**Comment by AlanMoonbase** [comment] 2024-03-16 04:14
Having this issue, hete's my latest log.

[ALAN-VNMBLZR - 2024.3.12.1169 - 2024-03-15 19_50_43.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14622361/ALAN-VNMBLZR.-.2024.3.12.1169.-.2024-03-15.19_50_43.log)

**Comment by AlanMoonbase** [comment] 2024-03-19 02:31
My apologies, issue is reproduceable without mods aswell.

[ALAN-VNMBLZR - 2024.3.12.1169 - 2024-03-18 19_25_59.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14644516/ALAN-VNMBLZR.-.2024.3.12.1169.-.2024-03-18.19_25_59.log)

**Comment by CaelThunderwing** [comment] 2024-03-19 22:44
sorry for the Delay, trying to Reproduce the bug again, im certain that the logs have long since been clapped so attaching an existing one would have no relevent data.  i'll continue to try and reproduce the issue , but did not/could not test it w/ OculusLink (USB) as my PC cant seem to sustain over it's USB-C port required bandwidth. and honestly never considered AirLink as last time i used it even for VRC my FPS was all over the place. if i cannot end up reproducing it tonight i'll resume Friday as i will be out of town wednesday evening til friday morning. 

if it matters any of what i can still recall, when the Issue occured i *couldnt* resume output audio by reselecting a device but i could get Mic audio back.

**Comment by CaelThunderwing** [comment] 2024-03-23 16:52
i have managed to finally reproduce the bug but on VRC so i think my specific situation might of been caused by a change in SteamVR  (as since the recent beta updates + the last 3 versions of Virtual desktop i can finally use hand tracking in resonite w/o completely breaking SteamVR), have yet to make Reso cause a Drop out,.  manage dto make it happen 3 times and was triggered by letting the headset sleep n wait for the Desktop connection to time out and Reset Back to the original Sound device.

**Comment by AlanMoonbase** [comment] 2024-03-24 00:46
> i have managed to finally reproduce the bug but on VRC so i think my specific situation might of been caused by a change in SteamVR (as since the recent beta updates + the last 3 versions of Virtual desktop i can finally use hand tracking in resonite w/o completely breaking SteamVR), have yet to make Reso cause a Drop out,. manage dto make it happen 3 times and was triggered by letting the headset sleep n wait for the Desktop connection to time out and Reset Back to the original Sound device.

I was just able to reproduce the bug, noticed that keyboard typing sounds do come through but everything else appears to be gone. Here's my player.log

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14733989/Player.log)

As for Shifty's Questions:
1. Yes, except for VD Audio. Everything comes out fine on other devices.
2. I don't doubt it, although the fact that there is sound from some things in game is leading me towards this being a Resonite bug.
3. I cannot test this due to refusing to use Link/AirLink.

**Comment by CaelThunderwing** [comment] 2024-05-27 21:01
> Why refuse to use the official solution? If it occurred with that too- it would help demonstrate it's not just a "Virtual Desktop" issue and is instead a more broad one, @AlanMoonbase.

they maybe in a similar situation why i've had to use VD over just AirLink. in Some configurations of hardware AirLink/USBLink either cant happen (incompatible USB Chipset/inferior and causes too low overall bandwidth for USBLink, or that under AirLink, FPS may overall be Higher than VD but Wildly inconsistant and all over the place where VD may provide a Lower max FPS, but provides a STABLE & Consistent FPS.) Generally most who refuse to use AirLink/USBLink fall under those reasons. the only option for people in this scenario, is SteamLink (which came out before this Issue was opened. 

ontopic to my initial report it has not happened since w/ the settings overhaul , im starting to think this maybe related to SteamVR changed if atleast inpart.

**Comment by shiftyscales** [comment] 2024-05-27 21:36
If you are no longer having this issue, I am going to close this out for now then thanks, @CaelThunderwing.

**Closed by shiftyscales** 2024-05-27 21:36 UTC
Labels: bug, needs more information

**Comment by Redd56** [comment] 2024-05-28 05:45
give me 5 minutes to test 
if its stillhappening i can recreate in desktop mode real easy
