### ISSUE TITLE
Unity to Resonite converter

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#916] opened 2023-12-16 23:00 UTC
### Is your feature request related to a problem? Please describe.

This usually is a problem with porting worlds from Unity to Resonite, It could be long and painful, or you use a converter.

### Describe the solution you'd like

A Unity to Resonite converter. It would convert all the lights, the colliders and the positions of all the objects. Material work would still have to be done in-game, but that's okay. Just to get a bulk of a unity scene in to make life easier.

### Describe alternatives you've considered

Using a converter for another platform, and then migrating it over.

**Comment by gameboycjp** [comment] 2023-12-16 23:15
#6?

**Comment by ModernBalloonie** [comment] 2023-12-16 23:19
> #6?

Oh, crap i didn't see. Oops.

Great to know though!

**Comment by Banane9** [comment] 2023-12-17 00:46
You could close this issue if it's a duplicate of that one

**Closed** 2023-12-17 01:02 UTC
Labels: enhancement
