### ISSUE TITLE
contacts list and active sesions not always displaying correctly 

### ISSUE THREAD

**Issue by Kirv-goldblade** [Yellow-Dog-Man/Resonite-Issues#1021] opened 2023-12-29 19:56 UTC
### Describe the bug?

so i've been seeing a bug recently where people in the contacts list will show as off line despite me knowing for a fact they aren't set invisible and a potentially related issue where active sessions in a world will vanish while i look at them again despite knowing said session is still 100% active (this has even happened with a session i was in at the time)

### To Reproduce

hard to reproduce but keep an eye on contacts and worlds you'll likely notice them disappearing and reappearing rome time to time

### Expected behavior

statuses and sesions should display correctly 

### Resonite Version Number

Beta 2023.12.21.1127

### What Platforms does this occur on?

Windows

### Log Files

n/a

**Comment by Zyro1331** [comment] 2023-12-29 20:01
This is an issue I have often too! No matter how many times I re-sync my computers clock, sessions repeatedly rotate positions. 

I had one night where I was trying to join someones Saturday night session, and I'd see it in the Contacts menu, yet not in the Worlds menu. And strangely enough, the session would display as active in the Worlds menu, but when I click on it the session display would just go blank again as if no one had that world open. It appears to happen most frequently with Contacts and Contacts+ sessions too.

**Comment by Nytra** [comment] 2023-12-29 20:08
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/739

and https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/643

**Comment by Frooxius** [comment] 2023-12-29 20:37
Yes, this is a duplicate of these two. Closing this one.

Also for future reference - you need to provide logs. We cannot diagnose bugs like this without logs provided.

**Closed by Frooxius** 2023-12-29 20:37 UTC
Labels: bug
