### ISSUE TITLE
"Sad" face tracking shape now being detected as "Angry"

### ISSUE THREAD

**Issue by Cataena** [Yellow-Dog-Man/Resonite-Issues#2343] opened 2024-06-15 23:10 UTC
### Describe the bug?

Since a recent update (Nordwick suggested the Quest Face Tracking update), whenever we make the "sad" shape with our mouths, the AvatarExpressionDriver is also driving the "Angry" blendshape.

As noted by @shiftyscales, the raw mouth data has not changed, but the behaviour in the AvatarExpressionDriver has.

### To Reproduce

Have a face tracked avatar with the AvatarExpressionDriver and a blendshape mapped to "Angry". Frown (without showing your teeth) in real life, and the avatar will drive both the frown and the Angry blendshapes.

### Expected behavior

Frowning without baring your teeth should only drive the "Sad" blendshape.

### Screenshots

My face tracker is sporadic and is choosing not to work at all while I'm writing this ticket so I'll add photos as soon as I can get it to work again.

### Resonite Version Number

2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index + Vive Mouth Tracker

### Log Files

My face tracker is sporadic and is choosing not to work at all while I'm writing this ticket so I'll add a log file as soon as I can get it to work again.

### Reporters

@shiftyscales 
@Nordwick
@Cataena
@felixq.
@FlameSoulis
@lxw404 
@ModernBalloonie

**Comment by FlameSoulis** [comment] 2024-06-16 03:17
I can vouch for this. I thought it was just me one night, but since testing around, I can kind of confirm this isn't bound right.

**Comment by Cataena** [comment] 2024-06-16 04:07
Thank you for putting your word in! 

It hurts me too - I was trying to frown at a serious problem that a friend was telling me and I ended up giving them grimaces of disgust 😅 I have been trying to consciously avoid frowning IRL to get around the bug.

**Comment by lxw404** [comment] 2024-06-16 05:22
Just verified this is happening too and I can't unsee it.  Also actively avoiding frowning now too.

**Comment by ModernBalloonie** [comment] 2024-06-16 10:21
This is happening to me too on the quest pro.

**Comment by shiftyscales** [comment] 2024-06-17 18:14
This issue is a regression following the integration of the Quest Pro facial tracking shapes by @Frooxius.

As I had previously noted in DM with him:

> I see- I'll look into it deeper later, and open an issue, I feel like it might've came about with the Quest Pro shape additions when I started to notice my face moved a bit unexpectedly . I wrote it off as my tacker being dirty, or out of alignment until a couple of days ago when I put on my old hyenid as it has very prominent anger shapes. Noticed the same issue again on an entirely different avatar tonight- I had already tried cleaning and re-aligning it. My emote system that uses raw mouth data still properly detects sad, and every other emotion I tuned it to- so I know that's working properly- the issue seems isolated to AvatarExpressionDriver.

---

As it turns out- this was an issue that many people have been experiencing- but nobody has previously reported it, as they all expected someone else had already done so- as a reminder- this is why it is good to double-check, and if in doubt- make an issue anyway- the worse that'll happen is it'll be closed as a duplicate!

---

As noted above- this issue seems to specifically affect the `AvatarExpressionDriver` component, which outputs `Angry` when frowning even slightly. `AvatarRawMouthData` is seemingly not affected (at least on my avatars / in my initial findings) as systems I have built using it all still properly detect the range of emotions I have set up and work as expected (happy, sad, angry, disgusted, pouting).

#2076 however, is a potentially related issue, and indicates there may be issues in the raw detection as well.

**Comment by Frooxius** [comment] 2024-06-24 22:48
Thanks in 2024.6.24.1317! Sorry for making you Angry! x3

**Closed by Frooxius** 2024-06-24 22:48 UTC
Labels: bug, triaged
