### ISSUE TITLE
Bring back "Blocked Users" list in Debug Menu

### ISSUE THREAD

**Issue by Cataena** [Yellow-Dog-Man/Resonite-Issues#2344] opened 2024-06-15 23:27 UTC
### Describe the bug?

There was a "blocked users" list in the debug menu that is now missing. I'm not sure if this is a regression or intentional. I required it today and noticed it was gone.

### To Reproduce

Look at your Debug menu, the Blocked Users list is no longer one of the tabs.

### Expected behavior

Look at your Debug menu (or somewhere in the settings menu), and a Blocked Users list is one of the tabs. This tab showed you all the users you've blocked.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76889792/315d9a88-ca70-4854-b47c-fbd37ed02027)

### Resonite Version Number

2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

It's gone for everyone, but if my individual log file is necessary, I can produce one.

### Reporters

@shiftyscales 
@Cataena
@Felixq.

**Comment by ProbablePrime** [comment] 2024-06-15 23:28
This is unfortunately a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1713 so will be closed.

**Closed by ProbablePrime** 2024-06-15 23:28 UTC
Labels: bug

**Comment by Cataena** [comment] 2024-06-15 23:49
Thanks Prime! Apologies, I promise I searched a bunch of terms but apparently "ban" completely slipped my mind.

**Comment by ProbablePrime** [comment] 2024-06-15 23:49
No worries, this helps people find it better too!

**Comment by Frooxius** [comment] 2024-06-16 00:24
Make sure to upvote that main issue too!
