### ISSUE TITLE
Local cloud variables

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#2923] opened 2024-09-11 12:48 UTC
### Is your feature request related to a problem? Please describe.

I need this because cloud variables have a limit and don't update fast enough so I need local cloud variables to read/write to especially the write part is important 1 per sec 

### Describe the solution you'd like

Local cloud variables or something local you can write values to and read values from

### Describe alternatives you've considered

Mods

### Additional Context

Local value saver

**Comment by JackTheFoxOtter** [comment] 2024-09-11 12:54
Actually a while ago Froox added the ability for cloud variables to work "offline", but from what you're describing it sounds more like you'll want to use dynamic variables. You can bind them to the "World" dynvar space, which makes them accessible everywhere in the world. Cloud variables aren't designed for rapid changes, they are designed for persistent changes, which generally don't have to update rapidly. (That said in some cases cloud variables can update instantly accross sessions, Ukilop's dash sync uses them to copy the position of the dashboard from userspace to the worlds you're in in real-time)

**Comment by JackTheFoxOtter** [comment] 2024-09-11 13:01
Adding context from the Discussion on Discord, it seems the goal is instantly syncing values across sessions, which cloud variables very much can do, as long as you're in both sessions at the same time.

**Comment by shiftyscales** [comment] 2024-09-11 17:46
@alexderpyfox This seems to be a duplicate of your own previous issue #1941.

**Closed by shiftyscales** 2024-09-11 17:46 UTC
Labels: enhancement
