### ISSUE TITLE
Ability to export and reimport things like fully set up avatars?

### ISSUE THREAD

**Issue by FuzzyFoxe** [Yellow-Dog-Man/Resonite-Issues#1468] opened 2024-03-10 21:26 UTC
### Is your feature request related to a problem? Please describe.

Last I've tried, exporting and reimporting an avatar ends up mangling the entire thing (If I'm remembering correctly)
The reason I'm bringing this up, is for model/avatar creators and the ability to sell people an avatar and not making people have to set it up completely in game, for those who aren't very savvy at resonite tools.

### Describe the solution you'd like

I would appreciate being able to export an entire avatar with systems attached, and be able to reimport it as if it never left resonite. (similar to how the backups of the neos transition worked)

### Describe alternatives you've considered

I've considered the idea that someone could make a proof of purchase ui tool that can check and associate your account with the code, and use like, a websocket or something to share the avatar or avatar link. But this can be somewhat difficult to set up for some creators.

### Additional Context

I don't know if anyone else or how many have requested this, but it would be very useful for creators in the meantime before more permanent fixtures are created for the marketplace update.

### Requesters

FuzzyFoxe
TromAlexandre
heckadai (The artist in question's discord name)

**Comment by ProbablePrime** [comment] 2024-03-10 22:31
This is a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/950 so will unfortunately be closed.

**Closed by ProbablePrime** 2024-03-10 22:31 UTC
Labels: enhancement

**Comment by FuzzyFoxe** [comment] 2024-03-10 22:40
> This is a duplicate of: #950 so will unfortunately be closed.

Ah, thank you, I tried searching for something like this, guess I used the wrong keywords. Thank you!
