### ISSUE TITLE
DynBone Disable at low FPS

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#1797] opened 2024-04-20 21:38 UTC
### Is your feature request related to a problem? Please describe.

When the user FPS gets below like 20 or so, bones start to freak out. 

### Describe the solution you'd like

I'd like to have it when the users FPS gets to low it will just turn off Dynamic Bone calculations, and then it would turn it back on after it returns above a set FPS

### Describe alternatives you've considered

https://github.com/isovel/DynBoneWrangler

### Additional Context

I've been using this mod for a while and FPS bellow 20, and Re-Enable about 25 seems to work really well for me.

I also added code onto my avatar that is doing this as well for other users so my Dynamics turn off to other users so they don't see my whiskers turning into helicopters.

**Comment by ohzee00** [comment] 2024-04-20 21:42
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/154
However this is very much trying to correct a symptom that hides a overarching cause, it would be better for dynamic bones to just not do this, not solve it by disabling the component all together. That will introduce more problems than it solves.

**Comment by lxw404** [comment] 2024-04-20 22:52
This was addressed here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1326 where Froox states:

> I agree with Prime here.
> 
> isabling them isn't really the approach we would take to resolve the problem.
> 
> As a general rule we try to not "mask" bugs like this - instead our approach would be to resolve the root issue instead.
> 
> In this particular case, the root issue is that they jiggle at low FPS - that is something we want to fix, so it doesn't happen in the first place, but they handle low FPS more gracefully.
> 
> I'm going to close this issue, since this particular course of action isn't something we plan (and we discourage making issues about specific solutions to a problem, rather than a problem itself in our guidelines: https://github.com/Yellow-Dog-Man/Resonite-Issues).
> 
> You're free to open a new issue that focuses on the problem.

**Closed** 2024-04-20 23:15 UTC
Labels: enhancement

**Comment by troyBORG** [comment] 2024-04-21 17:49
Ahh ok.  I tried searching for dynamic bones under issues before I submitted this, but I didn't see anything show up.  Which is why I made mine my post.
