### ISSUE TITLE
user inspector does not generate for anyone but the host

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#3146] opened 2024-10-31 16:34 UTC
### Describe the bug?

in resonite, when users want to get their user, they ether use get active user self and write it or just use it by itself.

around 50% of the time, users will just use the user inspector for being able to get their user.

whenever the user inspector is spawned from anyone but the host however, the inspector panel does not generate and stays blank.

### To Reproduce

host a world on a alt account or visit a world where you are not the host.
spawn a user inspector from the create new menu and watch the inspector fail to generate for you.

### Expected behavior

for the user inspector to generate for anyone who creates it regardless if they are the host or not.

### Resonite Version Number

Beta 2024.10.29.1229

### What Platforms does this occur on?

Windows

### Log Files

*

### Reporters

charlie_san

**Comment by jae1911** [comment] 2024-10-31 16:35
Dupe of #1964

**Closed** 2024-10-31 17:50 UTC
Labels: bug
