### ISSUE TITLE
ParticleSpray component doesn't work with new particle system

### ISSUE THREAD

**Issue by HamoCorp** [Yellow-Dog-Man/Resonite-Issues#3342] opened 2024-12-11 21:37 UTC
### Describe the issue.

after converting a tool with particlespray component, the values for partstyle and partemitter are null

### To Reproduce

import [Cube Sprayer.zip](https://github.com/user-attachments/files/18102541/Cube.Sprayer.zip) and convert to photon dust it is now broken

### Expected behavior

The component to have values assigned correctly and spray particles

### Screenshots

before conversion

 ![Image](https://github.com/user-attachments/assets/a359255a-07b7-4ffd-ba6d-03e541e1d99a)

after conversion

![Image](https://github.com/user-attachments/assets/f52b3e50-5d79-456f-bdcd-1ccaa1e6ecc7)

### Resonite Version Number

Beta 2024.12.11.501

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[THE-GERMAN-ROME - 2024.12.11.501 - 2024-12-11 21_15_37.log](https://github.com/user-attachments/files/18102607/THE-GERMAN-ROME.-.2024.12.11.501.-.2024-12-11.21_15_37.log)

### Reporters

HamoCorp

**Comment by wisemagick1** [comment] 2024-12-12 01:43
This is a duplicate of the one I reported https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3285

**Comment by Frooxius** [comment] 2024-12-12 19:58
Closing this one as duplicate. Thanks for the reports!

**Closed by Frooxius** 2024-12-12 19:58 UTC
Labels: duplicate, prerelease
