### ISSUE TITLE
Legs do not pose using pose systems anymore.

### ISSUE THREAD

**Issue by Nexulan** [Yellow-Dog-Man/Resonite-Issues#2865] opened 2024-09-04 23:11 UTC
### Describe the bug?

When using avatar pose systems it does not pose the legs properly, also caused a crash once installed.

### To Reproduce

Use any system that allow legs to be posed

### Expected behavior

Legs to be posed

### Resonite Version Number

2024.9.4.357

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-810672E - 2024.9.4.357 - 2024-09-04 15_32_23.log](https://github.com/user-attachments/files/16881932/DESKTOP-810672E.-.2024.9.4.357.-.2024-09-04.15_32_23.log)

**Comment by Frooxius** [comment] 2024-09-05 00:29
The pose systems need to be updated to work with the new system - they hijack the proxies (which is something we generally advise against). 

To make them work, the author of the pose system needs to place LocomotionAnimationSuppressor component on it and make sure the checkbox on it is enabled when the system is active.

Alternatively, you can enable Settings -> Misc -> Supress Feet Simulation, which will make legacy posers work in the meanwhile - just make sure to disable this once you're done using them.

**Comment by Wolf-Seisenbacher** [comment] 2024-09-05 03:15
> The pose systems need to be updated to work with the new system - they hijack the proxies (which is something we generally advise against).
> 
> To make them work, the author of the pose system needs to place LocomotionAnimationSuppressor component on it and make sure the checkbox on it is enabled when the system is active.
> 
> Alternatively, you can enable Settings -> Misc -> Supress Feet Simulation, which will make legacy posers work in the meanwhile - just make sure to disable this once you're done using them.

I have tested this and these functions do not work in the current live build, and are not a proper workaround.  This has been mentioned in a couple places on this github.  I don't know if I should contribute to one of the ones complaining the posers don't work, or if I should make a new bug report saying these workarounds currently do not work.

**Comment by art0007i** [comment] 2024-09-05 07:13
I've already updated my poser to work with the latest update, and it seemed to be working just fine.
I definitely think this is an issue with the posers and not the game right now.

Here's a folder link if you want to try my pose system:
```
resrec:///U-art0007i/R-8DD3F38F960FFA10E71D909CC7F09587D1EA9FD14F4E44F96EE5E357F78F6BE4
```

**Comment by shiftyscales** [comment] 2024-09-05 08:08
Can you provide a ResonitePackage or link to the system you are using @Wolf-Seisenbacher?

I could upgrade my existing pose-system without issue, and have also done so for other similar systems made by other people.

If the system you are referring to in particular operates in a different way, it would be helpful to understand how it was built / what it does, and what about it in specific is breaking.

**Comment by Wolf-Seisenbacher** [comment] 2024-09-05 11:59
> I've already updated my poser to work with the latest update, and it seemed to be working just fine. I definitely think this is an issue with the posers and not the game right now.
> 
> Here's a folder link if you want to try my pose system:
> 
> ```
> resrec:///U-art0007i/R-8DD3F38F960FFA10E71D909CC7F09587D1EA9FD14F4E44F96EE5E357F78F6BE4
> ```

I will have to check this, but in all my testing the settings don't work in current version with many people confirming this.  Later tonight I can pop back on and give this a try on my setup.

@shiftyscales you have found my report I made in #2870 and that is all the detail of what I was doing.  This report here I believe is another duplicate of the same issue as mentioned in #2859

**Comment by shiftyscales** [comment] 2024-09-05 16:45
I see- I didn't realize at the time you were referring to anchors, @Wolf-Seisenbacher. "Pose mode" in this context, are user-made tools that allow the user to pose their hips / legs anywhere- even outside of anchors.

But yes, as Frooxius suggested above, this issue requires you to update the pose system with the new `LocomotionAnimationSuppressor` component @Nexulan. (Or as a temporary fix which will be eventually removed, using the setting in the interim until you update your content.)

Either way, it seems there is nothing else actionable here, so I'll close this issue.

**Closed by shiftyscales** 2024-09-05 16:45 UTC
Labels: already exists
