### ISSUE TITLE
Radial menu sometimes will not stay centered in Desktop Mode

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#471] opened 2023-10-29 15:59 UTC
### Describe the bug?

The Radial menu does not stay in the center of the screen in desktop mode, which causes a lot of annoyance when your cursor suddenly teleports to the middle of the screen and ends up dismissing the menu or selecting something you didn't intend. 

### To Reproduce

Simply enter desktop mode, either natively or within VR. Open your Radial menu using T or middle-mouse, then simply click the locomotion menu. If you freeze your mouse, the menu will stay off-center, but as soon as your mouse moves, it will teleport the the center of the screen and completely miss the menu causing it to close itself. The problem is worse if it happens while using the "flick" gestures. 

### Expected behavior

I expect the mouse recentering to either be disabled when the menu is not in the center of the screen, or simply make the menu forced to keep it's position at all times in Desktop mode. 

### Screenshots

This short video shows how my cursor will sometimes teleport to the center of my screen even when the menu is off-center.
_My condolences for the low resolution & bitrate._
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/bd7171a0-5f7c-4457-80f0-d49c4c31fd33

Near the end, you'll notice that it strangely fixes itself and my intent to select the fly locomotion is being registered instead of constantly getting my mouse suddenly warped into the teleport locomotion.

### Resonite Version Number

2023.10.20.831

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

[MANGOVRG - 2023.10.20.831 - 2023-10-29 08_44_32.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13198518/MANGOVRG.-.2023.10.20.831.-.2023-10-29.08_44_32.log)

### Reporters

`@zyro1331` on Discord

**Comment by epicEaston197** [comment] 2023-10-30 01:53
this is a duplicate of #67

**Closed** 2023-10-31 00:00 UTC
Labels: bug
