### ISSUE TITLE
LUTs Appear Significantly Darker than Expected

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#339] opened 2023-10-20 01:14 UTC
### Describe the bug?

Imported and migrated Texture3Ds do not display the correct output colors when used in a LUT filter. Switching between Linear and SRGB does not appear to change the behavior of the texture. Neutral linear LUTs, which should not be visible at all (barring some post-processing differences), are noticeably dark.

### To Reproduce

Below is a public folder containing an example of a "neutral" LUT darkening an image (includes raw texture file):
resrec:///G-Bright-Spark/R-7DE8FA1003C4F51E96AC4C508DFAC26B3C13DDD8B6DAC19BFB8457E1F8FE4E90

### Expected behavior

LUT output should be limited to the data in the Texture3D

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/ce611222-1430-4da8-a57c-036144fa643c)

### Resonite Version Number

2023.10.18.449

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index, Desktop

### Log Files

N/A

### Reporters

Discord Usernames:
code807
luxkitty

**Comment by Frooxius** [comment] 2023-10-20 07:11
This is a known issue, Geenz and I have been working on a fix.

**Comment by Frooxius** [comment] 2024-01-16 03:08
@code807 Is the replication item still up? I cannot spawn it.

**Comment by code807** [comment] 2024-01-16 03:12
@Frooxius here is a link to the folder with the replication item inside:
`resrec:///G-Bright-Spark/R-C5BDB55D56B0DE4851D3827A4A6F0AFA0C8738F0E1E70C42CBEF6DB1222A034D`

**Comment by Frooxius** [comment] 2024-01-17 01:30
Thanks! Is the LUT expected to be completely invisible? I've been working on this and currently it looks like this: 

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/533806c4-1ac8-404e-af50-c4e6aa83a87a)

**Comment by code807** [comment] 2024-01-17 05:26
@Frooxius Affirmative, the LUT should be invisible. All the color values are mapped in such a way that the input and outputs should be the same through the lookup.

**Comment by Frooxius** [comment] 2024-01-17 06:41
Ok thanks! I'll be poking around some more.

**Comment by Frooxius** [comment] 2024-01-17 08:15
Hmm... It seems that the slightly different color is the sampling being off by half a pixel of the texture. I'm not sure why exactly that happens or if this is new behavior.

This is how it looks with a neutral LUT that's 256x256x256, it's pretty much invisible as it should be:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/a1425f8f-8b6a-48c4-ab73-6225fb3f9428)

This is with neutral LUT that's 32x32x32, but with values offset by half a pixel of the texture:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/38dfbc7b-dc28-4720-aec7-2543f5d4e32c)

But it looks wrong with dark tones still. So there's something off. It could be the sampling range.

**Comment by Frooxius** [comment] 2024-01-18 01:02
I think this is pretty fixed now. There's still very tiny discrepancy, but it should work much better:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/ef4394ca-c2bd-4c75-b140-f6bd9d7168d0)

I've pushed a build to `prerelease` branch in case anyone wants to give it a try. The asset variant system in the cloud is not aware of the new changes, so there's going to be some oddities with that, it will mostly do the processing and loading locally.

**Comment by Frooxius** [comment] 2024-01-18 13:23
Okay this should be fixed in 2024.1.18.775 now! Closing this now. 

If you still run into issues, you can reopen!

**Closed by Frooxius** 2024-01-18 13:23 UTC
Labels: bug

**Comment by lxw404** [comment] 2024-01-19 05:43
I'm still running into a discrepancy with this in the current build 2024.1.18.775:

![Resonite_H7rEG3c9w5](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/01cf97be-aef6-40cf-a834-a3dff4ea6ea8)

![Resonite_NmuMaGE0MM](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/92f77498-6890-4c0e-87f4-cda28c9fc90d)

The colors are semi-washed out and do not show quite the same as what was demonstrated in the devlog.  Here's a better dynamic range comparison using an analogue of the [IT8](https://en.wikipedia.org/wiki/IT8) color calibration image input:

Pre-LUT             |  Post-LUT | Normalized absolute difference
:-------------------------:|:-------------------------:|:------------------------:
![Resonite_fzR4lWIp37](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/aa1e0d57-9b66-4856-82cb-5d3b3ca020c0)  |  ![Resonite_QifwJ3gJZR](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/4791a454-33f8-4bec-bf6a-89b1f1526dd4) | ![CalTestOut_VAbsDiff001b](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/c9f4b5a0-bd8c-45c3-a835-045a9dda60b4)

I recognize that it was shown in the devlog that errors were varied in a grayscale gradient, however the following shows a bit more information visually about what is happening across each channel.  The outputs show positive variation (blue) and negative variation (red) per channel in a normalized view:

Red Channel | Green Channel | Blue Channel
:-------------:|:----------------:|:--------------:
![CalTestOut_VChan_REDpm](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/73e63dd8-07b1-4be4-b388-12dd8d43cf76) | ![CalTestOUT_VChan_GREENpm](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/3738bb7b-fa6e-40cc-a4b1-7e49d1024226) | ![CalTestOut_VChan_BLUEpm](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/627b9da0-c06f-4d32-b6ef-99a33e77b336)

The actual variance in values are close to $0.01$, however this can add up visually if multiple channels are different.


Furthermore, importing a RAW 32bit linear mapped LUT does not work in Linear mode, (which might be a separate bug report):

![Resonite_h6yVycVNEC](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/d67abb71-fa14-4d89-8765-becd6ef1b0c6)

![Resonite_2JQ39ZbOTF](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/f36d7a75-ce7d-4220-be3e-f6c4f5671de2)


Here are two updated replication objects for your consideration:

*sRGB mode test:*
resrec:///U-LuxKitty/R-5C7A2575819C9794CFE139FDD31B904753057920954A582E2DB63414A95B74F0

*Linear mode test:*
resrec:///U-LuxKitty/R-6A853077499CEC24C33B894D803EC8178489E9B496E797D60D7B314F1822E79F

**Comment by Frooxius** [comment] 2024-01-19 06:38
The small discrepancy is expected behavior in this case, the focus was on them being significantly darker, but there can be small imprecision.

I'd open new issue on that if you want us to look into that.

I'd do separate one on the linear LUT too.
