### ISSUE TITLE
Flux write arrows always on

### ISSUE THREAD

**Issue by Breakfastes** [Yellow-Dog-Man/Resonite-Issues#2195] opened 2024-06-01 07:37 UTC
### Is your feature request related to a problem? Please describe.

I find that Flux gets really confusing and I end up lost in my own code due to the write nodes not having a visual pointer to what they write to. There technically is one but it only appears when you hover your laser over the reference or the write node.

### Describe the solution you'd like

All I want is a toggle on perhaps the Flux tip, to always show the arrows that come from the write nodes pointing to their respective write targets

### Describe alternatives you've considered

Aside from writing something in game to solve this, which would be more annoying since I would have to make something attached to a specific flux tip or make it on avatar.

### Requesters

IGN: Erin
Discord: axolotlfren

**Comment by Stellanora64** [comment] 2024-06-01 07:43
You can rename variables so you can then just read off to where they are writing to. Generally helps as it works more like traditional programming where you name the variables. 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/b8856019-d4b7-4e5d-975e-a33e8868d15e)

**Comment by NepuShiro** [comment] 2024-06-01 07:53
I second this improvement, as Renaming the Nodes requires looking for the Store or the Write node in a jumble of wires. So having the Write arrows be always one would help with readability at a glance and speed up development with Flux

**Comment by Breakfastes** [comment] 2024-06-01 07:53
> You can rename variables so you can then just read off to where they are writing to. Generally helps as it works more like traditional programming where you name the variables. (you can even update the name and it will update it in the write nodes) ![image](https://private-user-images.githubusercontent.com/91010433/335785830-b8856019-d4b7-4e5d-975e-a33e8868d15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjg0NDMsIm5iZiI6MTcxNzIyODE0MywicGF0aCI6Ii85MTAxMDQzMy8zMzU3ODU4MzAtYjg4NTYwMTktZDRiNy00ZTVkLTk3NWUtYTMzZTg4NjhkMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA3NDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NzhiMzllZjFiZjljZjBhZDVkYThlYjFjOTg4YjJkZThmYzA4YjBhMjQ3OWY2MjU0NzgyY2VkNTEyYjQ5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aMJerVf-0NE6KByv68jIkls2lc0HJ6yjZfAIqKBmvOU)

I can do this yes but i find it easier to look at when i have a physical connection shown between node and reference, just as we had with previous systems like logix. In logix the write nodes would have a little triangle connected to the node. I could easily see that multiple writes all went to the same reference.

Also naming the variables solves only a tiny element of the issue. I still have to look closely at the write node to see the name and then go looking for that node, but at that point I may as well hover my laser over it to see the arrow, bringing me back to my original problem.

I dont want to hover over the node to see what it points to every time.

**Comment by Stellanora64** [comment] 2024-06-01 07:57
That's fair, I was just pointing it out as I don't see it get used very often / is often not known about, and has solved issues in my use case.

**Comment by Breakfastes** [comment] 2024-06-01 08:03
Even if its not used often, it would still help a lot with anything that uses variables. This is just about the only part of Flux that I find is worse than the old system, yet the impact of it makes it an absolute pain to work with.

**Comment by shiftyscales** [comment] 2024-06-06 17:52
This is a duplicate of #1129, @Breakfastes.

**Closed by shiftyscales** 2024-06-06 17:52 UTC
Labels: duplicate, enhancement
