### ISSUE TITLE
Replace First Substring Crash on String with length 1, out of range indices also implemented inconsistently

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#2550] opened 2024-07-12 08:28 UTC
### Describe the bug?

The solution to #1659 introduced clamping `StartIndex` to avoid the crashes.
Unfortunately a `Str` input of length 1 causes it to be clamped to -1 which is again illegal and causes crashes.

Additionally I'd argue that clamping is not a consistent behaviour for this function.

### To Reproduce

1. Create a display from this:
![grafik](https://github.com/user-attachments/assets/faa38955-68e8-482b-81a3-615ff3ff228c)

3. Take a look at an emulation of what a fixed clamp would output:
![grafik](https://github.com/user-attachments/assets/f5e57131-2993-44c0-8eb5-9dfa530e747d)
(The last two displays had to be editited as they display "aba" at the moment.)

### Expected behavior

1. The evaluation should not crash.
2. The output of a ReplaceFirstSubstring with a `StartIndex >= Str.Length` should either fail with null or return the unmodified `Str` input. Just fixing the clamp will not make it consistent!
  I would not have expected the last output to display "aab" as the `StartIndex` of the search is beyond where the last "a" within that string is.

### Resonite Version Number

2024.7.12.12

### What Platforms does this occur on?

Windows

### Log Files

[Anonymous - 2024.7.12.12 - 2024-07-12 10_11_33.log](https://github.com/user-attachments/files/16190722/Anonymous.-.2024.7.12.12.-.2024-07-12.10_11_33.log)

**Comment by Frooxius** [comment] 2024-07-12 13:42
Assigning @BlueCyro, since he originally implemented the fix.

**Comment by JackTheFoxOtter** [comment] 2024-08-04 08:11
This seems like a very minor regression to me, but it's currently breaking content. Since it's already been open for a while I wanted to ask if there's a rough estimate when this gets fixed, if it's still gonna take a couple of weeks I'm gonna have to implement a workaround for the trivia panels in the mentor certification centre.

**Comment by shiftyscales** [comment] 2024-08-04 16:29
Seeking a status update from @BlueCyro.

**Comment by JackTheFoxOtter** [comment] 2024-08-10 10:33
Since this seems to be taking longer I've implemented a workaround for the trivia panels in the Mentor Certification Centre, the node now doesn't get evaluated when the input length is 1, so my use-case is no longer urgently affected by this regression.

**Comment by fulgenscode** [comment] 2024-08-22 02:38
I am having this problem right now.

I also discovered that the last character in a string cannot be replaced, the index is clamped to the second to last character.

![Image png](https://github.com/user-attachments/assets/cde908e2-0559-409a-b0d3-f4518c16f965)

**Comment by Frooxius** [comment] 2024-09-04 07:13
Merged fix in 2024.9.4.357!

**Closed by Frooxius** 2024-09-04 07:13 UTC
Labels: bug, triaged
