### ISSUE TITLE
References to Parent Field are lost on Duplicate

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#27] opened 2023-10-13 21:59 UTC
### Describe the bug?

References to the parent field of a slot are lost when duplicating.
It works when saving and spawning the object.

### To Reproduce

resrec:///U-TheAutopilot/R-c6dcda3d-50c1-4204-80f7-97f2abb46e8d
Duplicate the box, compare values of the ReferenceField<SyncRef<Slot>> components within the original and the new box.
(null on the new slot)

### Expected behavior

The reference should point to the parent field of the new slot.

### Screenshots

![2023-10-13 21 49 03](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/0bc6d47d-5722-4bb8-8742-4beb56814ca8)
setup used to reproduce

### Resonite Version Number

2023.10.18.449

### What Platforms does this occur on?

Windows

### Log Files

[2023.10.18.449 - 2023-10-18 22_06_42_cleaned.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13033618/2023.10.18.449.-.2023-10-18.22_06_42_cleaned.log)
pasting object directly after world loaded, duplication at 22:10, removed personal data from log ("XXX")

**Comment by art0007i** [comment] 2023-10-13 22:03
seems similar to #12 
may be the same root cause?

**Comment by DaryeDev** [comment] 2023-10-14 13:34
Bump!

**Comment by mpmxyz** [comment] 2023-10-18 20:18
I added a log and confirmed bug on newest version.

**Comment by Frooxius** [comment] 2023-11-08 05:50
Fixed in 2023.11.8.335, thanks!

**Closed by Frooxius** 2023-11-08 05:50 UTC
Labels: bug
