### ISSUE TITLE
Drive source not accessible in lists

### ISSUE THREAD

**Issue by EuphieEuphoria** [Yellow-Dog-Man/Resonite-Issues#1243] opened 2024-01-24 21:30 UTC
### Describe the bug?

In resonite we have the ability to show/break drives within inspectors. This ability does not extend to blendshapes on the SkinnedMeshRendererComponent.

### To Reproduce

Attempt to access the drive source of any driven blendshape on the SkinnedMeshRenderer component

### Expected behavior

The ability to show or break drives on driven blendshapes

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/101027344/e51aaf2a-d333-493c-bc8d-9dae6c715c3a)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/101027344/057d9cb4-8e8b-4926-bb0c-8343ebb3bef9)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/101027344/e20a9ebe-053f-4c21-a308-028e9af401de)

### Resonite Version Number

Beta 2024.1.24.840

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-LQAQ7BB - 2024.1.24.840 - 2024-01-24 16_21_38.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14043813/DESKTOP-LQAQ7BB.-.2024.1.24.840.-.2024-01-24.16_21_38.log)

**Comment by Frooxius** [comment] 2024-01-25 00:51
This is duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/639

**Closed by Frooxius** 2024-01-25 00:51 UTC
Labels: bug
