### ISSUE TITLE
Having 13+ Write nodes connecting to each other in a chain using both OnWritten & OnFail starts causing massive performance drops

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2765] opened 2024-08-16 04:10 UTC
### Describe the bug?

I encountered this when modifying someone else's creation that was made in Neos, which must have not been an issue there, but every time I spawned their object, it would freeze the game for several seconds. I unpacked it and the culprit was these write nodes in a chain using both OnWritten & OnFail (Like image below)
![image](https://github.com/user-attachments/assets/20112818-223b-48b6-9c2b-68a8c44acea1)

Even adding relays would cause the entire game for everyone in the session to freeze. (The above issue causes everyone to freeze too)

### To Reproduce

Create a chain of writes like the image above and after 13, every added write would quickly gradually cause the game to freeze harder and harder, after 16-17 it becomes unbearable. What's worse, there doesn't even need to be any actual event or references. Just empty nodes. It doesn't even need to be unpacked for this performance problem!! 

### Expected behavior

For there to be no performance degradation with chain writes setup in this way

### Screenshots

I put them above

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[SilvyPC - 2024.8.5.1341 - 2024-08-16 00_03_51.log](https://github.com/user-attachments/files/16632832/SilvyPC.-.2024.8.5.1341.-.2024-08-16.00_03_51.log)

### Reporters

SilvyPaws

**Comment by TisFoolish** [comment] 2024-08-16 06:12
I have a feeling that the bug that causes this is the same bug that causes https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2750

**Comment by SilvyPaws** [comment] 2024-08-16 09:56
> I have a feeling that the bug that causes this is the same bug that causes #2750

I do not agree

**Comment by Frooxius** [comment] 2024-08-16 17:02
This sounds like it's different from those two issues to me.

Let's keep this open and we'll see once we investigate.

**Comment by Nytra** [comment] 2024-08-17 13:34
The reason why I think this is #1467 is because the performance issue only happens when the node group is rebuilding (when spawning the item, adding or removing nodes)

If you look in that linked issue the reproduction steps are very similar, create a bunch of linked nodes with multiple outputs connected to single inputs

**Comment by Frooxius** [comment] 2024-08-17 17:29
Is this only on spawning? From the m skimming the issue I thought this happens during executing the writes, since they mention it happens even when it's packed.

If it's while editing the nodes and only during spawning, thalen it's very likely #1467

**Comment by Nytra** [comment] 2024-08-17 18:11
They say "there doesn't even need to be any actual event or references. Just empty nodes." which suggests to me that the nodes are not executing.

**Comment by SilvyPaws** [comment] 2024-08-17 18:14
> Is this only on spawning? From the m skimming the issue I thought this happens during executing the writes

This does not cause performance issues while it's doing writes. Just when interacting with the physical nodes. (Connecting anything in the chain, detaching, adding relays, ect). The actual function of the nodes isn't affected by this issue.

**Comment by Frooxius** [comment] 2024-08-17 18:14
Ah thanks for clarifying. In that case I'm confident that this is same as #1467 then, I'll close this one as duplicate.

**Closed by Frooxius** 2024-08-17 18:14 UTC
Labels: bug, triaged
