### ISSUE TITLE
my settings menu is gone

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#1973] opened 2024-05-05 18:59 UTC
### Describe the bug?

its not there

### To Reproduce

open settings and it not being there

### Expected behavior

settings being there

### Screenshots

![2024-05-05 20 56 26](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61125650/b1ccb815-1207-41e6-8ee6-b3e48d0aea8f)

### Resonite Version Number

2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

steamvr

### Log Files

[DESKTOP-OTQN0RR - 2024.5.4.678 - 2024-05-05 20_45_13.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15214148/DESKTOP-OTQN0RR.-.2024.5.4.678.-.2024-05-05.20_45_13.log)

### Reporters

_No response_ crow in the patreon channel

**Comment by alexderpyfox** [comment] 2024-05-05 19:23
i fixed it by adding the facet from the facets folder to it
but im not sure what caused it to dissapear in the first place

**Comment by epicEaston197** [comment] 2024-05-05 19:42
This is a duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/466

**Comment by shiftyscales** [comment] 2024-05-05 20:23
Without context from what @alexderpyfox did in the session prior to observing this issue, it's not possible to say with complete certainty one way or the other, @JackTheFoxOtter. However, the log file submitted indicates the use of mods, so I'll be closing this issue, regardless.

**Closed by shiftyscales** 2024-05-05 20:23 UTC
Labels: bug

**Comment by alexderpyfox** [comment] 2024-05-05 20:38
i didnt do anything i loaded up the game and it was gone

**Comment by shiftyscales** [comment] 2024-05-05 23:36
I'd suggest following up with any additional information you have about the issue in #466, @alexderpyfox.
