### ISSUE TITLE
User Interface indicator jumping around

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#1641] opened 2024-04-07 22:59 UTC
### Describe the issue.

While in desktop mode, sometimes when you hover over different tabs in setting.  The UI looks like it keeps switching between two different object continuously.  

### To Reproduce

Click on User Interface and hover over Locale and watch

### Expected behavior

It to act like the rest of the tabs

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10406330/c67a7fcc-04a8-42c7-a462-d9a16db2520d

### Resonite Version Number

2024.4.5.1261

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-H0FLKOJ - 2024.4.5.1261 - 2024-04-07 17_41_20.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14899291/DESKTOP-H0FLKOJ.-.2024.4.5.1261.-.2024-04-07.17_41_20.log)

**Comment by ohzee00** [comment] 2024-04-07 23:02
I believe this is a duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1617#issue-2226743948

**Comment by troyBORG** [comment] 2024-04-07 23:06
Ahh yeah it looks like it is.  I only looked in the Prerelease tags for reports of it.  That's why I didn't see that one.  
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1641

**Closed** 2024-04-07 23:06 UTC
Labels: prerelease
