### ISSUE TITLE
Gridspace grid texture is offset by 16 pixels

### ISSUE THREAD

**Issue by amplified1** [Yellow-Dog-Man/Resonite-Issues#2789] opened 2024-08-20 23:21 UTC
### Describe the Underlying Issue

Gridspace grid texture has an offset, making the grid not appear centered at 0,0.

### To Reproduce

Create fresh gridspace. observe.

### Expected Behavior

The grid texture is most useful if it is representative of a true global grid.

### Screenshots / Video

![20240820171416_1](https://github.com/user-attachments/assets/8a3e8927-5c4c-42e9-8eb0-f7c76f679149)
![20240820171430_1](https://github.com/user-attachments/assets/d4c66757-f24f-4148-8db0-a1ab2a891949)
![20240820172020_1](https://github.com/user-attachments/assets/ad6e4bf7-25ad-4ae1-bcf7-f3e36516d326)

### Reporters

`@_Amplified_`

**Comment by lxw404** [comment] 2024-08-20 23:48
Duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2754.

**Closed** 2024-08-21 03:04 UTC
Labels: duplicate, content
