### ISSUE TITLE
Alternative storage subscriptions

### ISSUE THREAD

**Issue by Nihlus** [Yellow-Dog-Man/Resonite-Issues#655] opened 2023-11-12 18:08 UTC
### Is your feature request related to a problem? Please describe.

Currently, the only way to get more storage is to subscribe to Patreon. This is not an option for some people, and the use of Patreon to link with an account is problematic if you want or need to maintain multiple accounts for things like headless hosting.

While the Patreon subscription levels are fairly granular at the lower tiers, the higher tiers sport some fairly large jumps between them in terms of pricing and storage space (5, 25, 50, 75, 100, 200, 500, 1000, 2000). On top of that, only the 500GB tiers and above support sharing storage with others, even when the accounts are also your own personal accounts used for headless hosting.

For example, I have a few smaller headless servers I run for friends and communities, and I really don't need more than 20-30GB of total space. I do, however, need to have them as separate accounts and with the worlds only accessible to the specific accounts with their specific contact lists in order to remain compliant with Resonite's terms of use.

It's a relatively large jump for me to go from $10 to $80 per month in order to enable storage sharing, and I'd be left with almost 10 times more storage than I actually need.

### Describe the solution you'd like

A way to purchase storage space, either permanently or via a subscription service, outside of Patreon would be very useful to a number of people.

The ability to also select the desired storage space in a more granular fashion, allowing you to adjust your budget depending on your actual storage needs, would also be highly desirable.

Finally, a way to purchase or enable shareable storage for these more granular purchases would be appropriate. It's wasteful for both the customer and Resonite's backend to allocate more storage than the customer would actually use or need, which you are more or less forced to do with the present system.

### Describe alternatives you've considered

The alternatives available today are limited - you can, of course, purchase a higher tier on your main account and then share worlds via public folders or groups. You can also use your main account as the one hosting the headless servers.

Both of these alternatives are far less flexible and far more fragile than being able to cleanly separate different accounts with different responsibilities. Not every member of a group, for example, should be able to see and modify all worlds a given group of headless servers might need or want to use.

Contact lists come into play if you reuse your main account, too - not all people on your primary account's contact list should have access to all headless servers you might be running.

Another alternative would be to use a growing third-party market of storage, where people with higher Patreon tiers take it upon themselves to effectively sublease parts of their storage space to others. 

This is problematic for several reasons, chief among them the forced reliance on single individuals to offer a service through less-regulated means than Resonite would be able to. Beyond that, it's not entirely clear if that type of subleasing is presently allowed, or if it will remain that way in the future.

**Comment by shadowpanther** [comment] 2023-11-12 18:51
Duplicate of:
#601 - Gifting subscription tier
#497 - Alternatives to Patreon

**Comment by FuzzyFoxe** [comment] 2023-11-12 21:43
I was wondering similarly; is it possible for twitch commands to be accessible to patrons, or perhaps storage be linkable to twitch subscription too? It'd be nice to save money on these things.. ^^;

**Closed** 2023-11-13 16:51 UTC
Labels: enhancement

**Comment by Nihlus** [comment] 2023-11-13 17:47
> Closing this, as #497 already exists.
> 
> Just a note, we're very unlikely give you the ability to purchase storage permanently - it would still be a monthly cost for us, so giving you storage for a fixed price forever would either be uneconomical for us or very expensive for you (think paying dozens of years worth of subscription at once).

Completely understandable! Personally, the most important thing for my use case would be the ability to subscribe to smaller portions of storage for more accounts without having to maintain multiple Patreon associations.
