### ISSUE TITLE
Controllers get stuck to the ground when using Quest 3 over steam link

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#2164] opened 2024-05-30 04:03 UTC
### Describe the bug?

Some new users using a Quest 3 over steam link have noted that their controllers are stuck to the floor and don't have any tracking. However, it seems that controller input still seems to function, just no tracking.

For most users this seems to be fixed by adding the -LegacySteamVRInput launch argument, and some have noticed it being fixed when an update occurs (although newer users still notice the issue on the updated version). However, this solution does not always work, as is for the case of the user that provided their logs for this issue.

### To Reproduce

It seems to vary between users, but for the logs provided, they were using a quest 3 over steam link.

### Expected behavior

The controllers should have tracking. 

### Resonite Version Number

2024.5.30.68

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3 over steam link

### Log Files

[message.txt](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15493480/message.txt)

### Additional Context

This report was made on the behalf of a new user that provided the logs, as I have wanted to make this issue for awhile but haven't been able to get logs for the issue until now.

### Reporters

stellanora 
spaghettioooh

**Comment by Nytra** [comment] 2024-05-30 05:09
Dupe of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/927 I think

**Comment by Stellanora64** [comment] 2024-05-30 05:13
Maybe, although this doesn't seem to be caused by the headset going into standby, and isn't fixed by a restart afaik

**Comment by Nytra** [comment] 2024-05-30 05:16
If it's the same issue it requires a full SteamVR restart to resolve it. Just restarting Resonite alone doesn't help.

**Comment by Stellanora64** [comment] 2024-05-30 05:27
They said it's been fixed for them, but they still have the legacy input launch argument active. I'll report back once I get an update on if it still works without the launch argument. (In which case I'll close as duplicate)

**Comment by shiftyscales** [comment] 2024-05-30 20:22
Have you had a chance to look into this issue further to assess if it is a duplicate yet, @Stellanora64?

**Comment by Stellanora64** [comment] 2024-05-30 22:36
@shiftyscales I have heard nothing back from them yet unfortunately. I've asked again but if they still don't respond by later today it, this can be closed.

**Comment by Stellanora64** [comment] 2024-05-31 00:56
@shiftyscales they have managed to get back to me and when they removed the launch arguments everything was still working as normal. So it is most likely a duplicate of #927 and can be closed as such

**Closed** 2024-06-02 03:07 UTC
Labels: bug, needs more information
