### ISSUE TITLE
swap facet anchor button option

### ISSUE THREAD

**Issue by Draconas** [Yellow-Dog-Man/Resonite-Issues#2132] opened 2024-05-28 22:51 UTC
### Is your feature request related to a problem? Please describe.

noticed when enabled, the button to activate or deactivate facet anchors are bound to the right dash button

### Describe the solution you'd like

add a toggle option to let people swap the activation button to either the left or right dash button for facet anchors

### Describe alternatives you've considered

N/A?

### Additional Context

if an option exists already, i havent found it

### Requesters

@draconas_rayne

**Comment by shiftyscales** [comment] 2024-05-28 22:54
This is a duplicate of #2118 and will be in the next build, @Draconas.

**Closed by shiftyscales** 2024-05-28 22:54 UTC
Labels: enhancement
