### ISSUE TITLE
ambient occlusion toggle for new ui

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#1717] opened 2024-04-16 14:18 UTC
### Is your feature request related to a problem? Please descibe

its because ssao is horrible it updates out of sync with the rest its at 30hz flickering leaves marks ghost outlines and spots grom movement for a second after its just horrible

### Describe the solution you'd like

a toggle to disable ambient occlusion

### Describe alternatives you've considered

mods but it broke

**Comment by alexderpyfox** [comment] 2024-04-16 14:34
its because ssao is horrible it updates out of sync with the rest its at 30hz flickeri g leaves marks ghost outlines and spots grom movement for a second after its just horrible

**Comment by Geenz** [comment] 2024-04-16 15:59
We'll likely wait to support this with post processing volumes.

**Comment by alexderpyfox** [comment] 2024-04-16 16:23
its needed now

**Comment by Geenz** [comment] 2024-04-16 17:27
It would be better to ask for better AO (and associated "options" for preference - there's many AO techniques we can support here) than to just request a toggle.  There are several worlds that depend on AO being present overall, and not all AO is created equal.  Our current solution uses some temporal sampling which can create odd "smear" effects, for example, vs. some other methods which don't have this problem.  I would probably start there instead - which there's already options we can look at for this such as using Unity's built-in AO in the postprocessing stack for the time being rather than the AO we brought in from a third party vendor which we currently use.

**Comment by 5H4D0W-X** [comment] 2024-04-16 18:08
>for now a setting that turns it off will do

I don't think it makes sense to do that right now, especially because it will probably only take a few days for the relevant mods to be updated

**Comment by Frooxius** [comment] 2024-04-16 18:09
It's not a big issue to add right now, because I'll be doing the Motion Blur, Bloom and some other settings.

**Comment by alexderpyfox** [comment] 2024-04-16 18:16
will that mean that a toggle for ssao will be added?

**Comment by shininghero** [comment] 2024-04-16 19:45
Intriguing, we have a third party AO being used despite Unity having one available?  I assume this was due to some legacy availability or implementation issues.

I believe it would be best to start by comparing the two that are already available to the devs.  Especially with a repro scene that readily demonstrates the flickering or smudging issues.

As for better AO, I'm sadly not sure where to start either.  HBAO might be interesting, it's in a lot of modern titles already.

**Comment by Geenz** [comment] 2024-04-16 19:46
AO improvements should be taken to a separate issue - not here.

**Comment by LimeProgramming** [comment] 2024-04-16 20:51
I'd like to turn off AO no matter what AO it uses.

**Comment by Frooxius** [comment] 2024-04-17 19:39
This is actually duplicate of this one: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/21

**Closed by Frooxius** 2024-04-17 19:39 UTC
Labels: enhancement, setting
