### ISSUE TITLE
Add maximum focused frame rate

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1989] opened 2024-05-06 10:21 UTC
### Is your feature request related to a problem? Please describe.

Right now you can't limit your frame rate apart from V sync

### Describe the solution you'd like

I would like to be able to edit my frame rate using a slider similar to the maximum background frame rate

### Describe alternatives you've considered

Using external tools

### Requesters

@epicEaston197

**Comment by shiftyscales** [comment] 2024-05-07 20:46
Duplicate of #1052, @epicEaston197.

**Closed by shiftyscales** 2024-05-07 20:46 UTC
Labels: duplicate, enhancement

**Comment by epicEaston197** [comment] 2024-05-07 22:35
> Duplicate of #1052, @epicEaston197.

Well that was particularly asking for the frame rate be limited when you're not focused in the tab so if that feature was asking for two features it wasn't very clear when I read the issue
