### ISSUE TITLE
status page not showing graph data since the 14th of dec 2023

### ISSUE THREAD

**Issue by clarjon1** [Yellow-Dog-Man/Resonite-Issues#930] opened 2023-12-19 02:12 UTC
### Describe the bug?

Graphs not being populated on status site

### To Reproduce

Visit [status.yellowdogman.com](https://status.yellowdogman.com/)

Set graph of choosing to "Week" view

No data since the 14th!

### Expected behavior

The graph should be above zero!

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/627845/fff051a2-773c-4a7a-8e10-a9947570b055)

### Resonite Version Number

n/a

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

desktop

### Log Files

n/a

### Reporters

ToyDragon (aka clarjon1 in discord)

**Comment by ProbablePrime** [comment] 2023-12-19 02:27
Thanks! Im moving the stats-provider around to make things more reliable. It'll show stats again soon.

**Comment by suspiciouslyBee** [comment] 2023-12-23 17:36
This bug still exists.
![Screenshot 2023-12-23 at 09-35-11 Yellow Dogman Studios](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66197294/33934c73-de16-4fa2-8252-c33848f5bb60)

**Comment by ProbablePrime** [comment] 2023-12-25 00:42
> This bug still exists. 

Yup, until the issue is closed it exists.

**Comment by ProbablePrime** [comment] 2023-12-28 04:09
This has been resolved!

I also added some stuff:
1. Relay and bridge status is acurate, if we cant find them bridge or relay it will report an outage
2. I've added the number of bridge users and the relay users

**Closed by ProbablePrime** 2023-12-28 04:09 UTC
Labels: bug
