### ISSUE TITLE
Turn only default option results in worse tool usage

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#2309] opened 2024-06-12 18:30 UTC
### Describe the bug?

With the recent change to add and default to a turn only option for your offhand, when you grab a tool the offhand stays turn only and a user is entirely unable to move. This also affects using the laser to grab items with Index controllers.

### To Reproduce

Equip a tool or laser grab an object and attempt to move with the offhand.

### Expected behavior

For the game to detect that you've only got one available hand and fall back to the previous one handed style control scheme. This is how this problem is handled on other platforms and games when one of your hands is overridden by settings or tools.

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

---

### Additional Context

I don't want a full reversion of this, I think how it works with the default is fine when you're empty handed, but especially on the Quest this basically made the tool problem far worse.

**Comment by epicEaston197** [comment] 2024-06-12 21:51
I think this would be fixed just by having the ability to move while holding a tool be a thing

**Comment by Frooxius** [comment] 2024-06-12 21:58
It's been coded to automatically change the movement to be turn + move on a single joystick if one of the joysticks is used by something else (e.g. a tool).

Can you please share a screenshot of your settings so we can replicate this? 


@epicEaston197 You can already to that for some tools. But if the tool is using the joystick, locomotion can't use it.

**Comment by epicEaston197** [comment] 2024-06-12 22:10
>@epicEaston197 You can already to that for some tools. But if the tool is using the joystick, locomotion can't use it.

I've noticed this when I was equipping the dev tool I'm unable to move when it's equipped which is not desirable behavior
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/ea42b68e-1f34-445e-9222-ac14ea61e329)

**Comment by Frooxius** [comment] 2024-06-12 22:13
@epicEaston197 That's because right now, it uses the joystick, which means it can't be used for locomotion.

We can look into it not needing to use joystick, but that's separate issue from this, because even if that one is fixed, there will still be other things that might need to take control of the joystick.

**Comment by epicEaston197** [comment] 2024-06-12 22:23
> @epicEaston197 That's because right now, it uses the joystick, which means it can't be used for locomotion.

The dav tool doesn't need to use the movement of the joystick it only uses the clicking function every single default tool in the game requires a secondary action meaning that you're not able to move with most default tools all because they only require the clicking action of the joystick i think if you separate the requirement from movement vs joystick clicking that would be preferable

**Comment by Frooxius** [comment] 2024-06-12 22:25
This is not really the place to discuss that. 

Like I said, even if the devtool didn't use it, other things might - and the bug will still be an issue. We need to resolve the bug reported in the original issue.

**Comment by epicEaston197** [comment] 2024-06-12 22:28
Ohh I'm sorry about that so the intended behavior is for it to automatically turn the other controller to "turn and move"?

**Comment by ko-tengu** [comment] 2024-06-12 22:38
I attached a video showing the issue along with a log for completeness sake.
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/585ffed5-3158-47bc-97e4-f7da1d7a372c

[BUFU - 2024.6.11.74 - 2024-06-12 18_27_54.log](https://github.com/user-attachments/files/15811633/BUFU.-.2024.6.11.74.-.2024-06-12.18_27_54.log)

**Comment by shiftyscales** [comment] 2024-06-13 22:34
Confirming the reported behaviour- with the configuration of left hand strafe, right hand turn only, I am unable to move forward with either hand while on Touch controllers, @Frooxius. This applies both to grabbing an object remotely and equipping a tool to either hand.


https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/fcad896a-3fe9-4a5d-ae2f-aec3d36a4ddb

[SHIFTY-LAPTOP - 2024.6.11.74 - 2024-06-13 15_29_31.log](https://github.com/user-attachments/files/15829357/SHIFTY-LAPTOP.-.2024.6.11.74.-.2024-06-13.15_29_31.log)

**Comment by Stellanora64** [comment] 2024-06-15 10:02
Had some new users that were stuck due to this, are there any updates on this?

**Comment by shiftyscales** [comment] 2024-06-17 18:05
If we have an update on an issue, it will be posted to the issue, @Stellanora64.

As far as I can see- this issue has all it needs to be looked into by @Frooxius who is currently assigned to it- it just needs time.

As it stands- this issue was reported less than a week ago, and there has since been a weekend in-between as well as other priorities to take care of- so your patience would be appreciated.

**Comment by Frooxius** [comment] 2024-06-25 19:26
I've made a fix in 2024.6.25.1149, thanks!

Just a note for next time please - if we request screenshot, please provide the screenshot instead of video. The video made it much harder for me to parse what is going on and get the key piece of information I needed from it to fix this.

**Closed by Frooxius** 2024-06-25 19:26 UTC
Labels: bug, triaged
