### ISSUE TITLE
setting to disable and adjust motion blur for desktop

### ISSUE THREAD

**Issue by Turtle9112** [Yellow-Dog-Man/Resonite-Issues#1697] opened 2024-04-16 00:20 UTC
### Is your feature request related to a problem? Please describe.

lower framerate and motionblur do not mix very well and makes working on things quite jarring on occasion

### Describe the solution you'd like

just a simple toggle to disable and perhaps a slider to adjust how strong the motion blur is

### Describe alternatives you've considered

there is a mod to disable it, however it would be infinately better in the new settings under graphics

### Requesters

resonite : Turtle
Discord : turtle9112

**Comment by jae1911** [comment] 2024-04-16 00:21
Duplicate of #178

**Comment by ohzee00** [comment] 2024-04-16 00:24
To put more information with the recent settings ui update found on the discord:

> If all goes well, these changes will be pushed to public and further Setting UI work will continue on the public builds with quick iteration speed - adding more functionality, lots of new settings (yes including motion blur toggle!) and expanding upon this - we just need to make sure the core things work well first.

**Comment by ModernBalloonie** [comment] 2024-04-16 00:57
This will happen.

**Comment by Frooxius** [comment] 2024-04-16 08:17
Yes this is duplicate, closing this one!

**Closed by Frooxius** 2024-04-16 08:17 UTC
Labels: enhancement
