### ISSUE TITLE
Index controllers grip not behaving properly.

### ISSUE THREAD

**Issue by spencershoe** [Yellow-Dog-Man/Resonite-Issues#850] opened 2023-12-05 21:16 UTC
### Describe the bug?

index controllers use grip force sensors as opposed to finger position when grabbing objects. using the input debugger, it appears to stop grabbing around .2 force level.  maybe add slider to change sensitivity, if using finger position is not an option?

### To Reproduce

if you grab too lightly with index controllers the object you are holding will fall out of your hands.

### Expected behavior

if you keep your hands closed the object will stay in your hands.

### Resonite Version Number

beta 2023.11.28.1365

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

N/A

**Comment by TisFoolish** [comment] 2023-12-05 21:21
> if you grab too lightly with index controllers the object you are holding will fall out of your hands.

I am pretty sure this is intended behavior, but I do like the idea that it requires a full release of your grip to let go of something.

**Comment by Frooxius** [comment] 2023-12-05 21:29
This is intended behavior, not a bug.

We don't want drop items at too low of a value, because that ends up in "sticky hands" issue, where it might be difficult to actually let go of items.

Sensitivity and required force does differ from controller to controller - you can adjust your own using the Steam Input editor to customize the bindings - it lets you adjust the strength needed to start grabbing and to let go of items.

We can potentially add in-game setting for that, instead of using Steam Input - if you are interested in that over the Steam Input editor, you can make a feature request.

I'm closing this issue, as it's specifically not a bug.

**Closed by Frooxius** 2023-12-05 21:29 UTC
Labels: bug

**Comment by spencershoe** [comment] 2023-12-05 21:30
it is not, i keep accidentally dropping objects. the sensitivity is too low and there is no way to change it

**Comment by spencershoe** [comment] 2023-12-05 21:35
so i should make a finger position based grip setting as a feature request?

**Comment by Frooxius** [comment] 2023-12-05 21:52
Yeah, that might be a good request, we can look at that!

Please include some more info about their method too if possible, I'm not super familiar with what they use and how it work, so info on that will help.

**Comment by spencershoe** [comment] 2023-12-05 21:55
im booting the games up now to make sure i wasn't just speaking out of my ass. I'll be sure to look into the exact method while i'm at it.
