### ISSUE TITLE
Overdriven color on toon material is much brighter now

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2395] opened 2024-06-25 01:54 UTC
### Describe the bug?

If you overdrived a color material in build `2024.6.11.74` The material would glow a bit when you did so 
but now on build `2024.6.24.1317` The color is now dramatically blown out compared to build `2024.6.11.74`

### To Reproduce

This is really difficult to replicate since it requires going between two builds

### Expected behavior

The glow of an overdriven tune material should be the same as build `2024.6.11.74`

### Replication item

[EE_Item.zip](https://github.com/user-attachments/files/15964196/EE_Item.zip) (Resonite package)

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/92fff8a7-0911-48fa-9d27-365d563e4867)

### Resonite Version Number

Beta 2024.6.24.1317

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

build `2024.6.24.1317` 
[EPICEASTON197 - 2024.6.24.1317 - 2024-06-24 21_50_39.log](https://github.com/user-attachments/files/15963412/EPICEASTON197.-.2024.6.24.1317.-.2024-06-24.21_50_39.log)

build `2024.6.11.74` 
[EPICEASTON197 - 2024.6.11.74 - 2024-06-24 22_20_26.log](https://github.com/user-attachments/files/15963646/EPICEASTON197.-.2024.6.11.74.-.2024-06-24.22_20_26.log)

### Additional Context

This is what my avatar looked like build `2024.6.11.74` Emission color: R3 G3 B3 A1
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/a42f6bc0-4b66-4789-a02f-c53515603cd8)

And now this is what it looks like Emission color: R3 G3 B3 A1
(I imported the exact same Resonite package for my avatar In both screenshots)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/f1cb64a7-18b9-44b9-86a8-50936cca181b)

### An additional note
If users weren't meant to do this and this was unintended behavior why is there a "gain" slider in the color picker If content was just destined to break like this?

This could also severely break content with how blown out the color is compared to build `2024.6.11.74`
There was also no mention of the toon material in the latest Update log for build `2024.6.24.1317` So my takeaway from this is that it wasn't Supposed to be affected at all

### An additional detail
if i overdrive it to 2, 2, 2 ,1 My avatar goes back to normal
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/b3ab6acb-008b-48a7-9e22-910b4ae36624)

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment] 2024-06-25 02:06
I would like to also request if anyone has seen me in game on an NVIDIA card can tell me if this is how I've always looked I doubt it but it could be a possibility

**Comment by ko-tengu** [comment] 2024-06-25 02:52
I don't have anything with huge emissive spaces like that, but it seems to be acting as I'd expect and how it has been previously on my install. 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/52134e1b-8e83-41d5-bcbf-27d3b2270567)

If you do think it's GPU related, I have a 2070 Super on driver 552.22.

**Comment by epicEaston197** [comment] 2024-06-25 02:54
> I don't have anything with huge emissive spaces like that, but it seems to be acting as I'd expect and how it has been previously on my install.
> 
> If you do think it's GPU related, I have a 2070 Super on driver 552.22.

Not to be rude but that isn't Related to this issue the title specifically describes overdriven color behavior

**Comment by shiftyscales** [comment] 2024-06-25 03:56
Seeking input from @Geenz - possible regression / changed behaviour from the latest shader update?

**Comment by knackrack615** [comment] 2024-06-25 09:39
Can confirm this issue does happen on our end aswell (both me and @NepuShiro)

**Comment by ShrikeAlvaron** [comment] 2024-06-25 10:08
What color profile is this using?  I know that srgb colors are not meant to be overdriven and that doing so can result in unpredictable behavior (hence the gain slider in the color picker being locked when I’m srgb mode), but if this is occurring with overdriven linear values that could be a problem.

**Comment by ko-tengu** [comment] 2024-06-25 15:50
After a nap, a reproduction object, and some testing, the curve for overdriven colors did change on xiexetoon materials. The current release is closer to what I would expect, but it's a lot brighter and prone to color peaking compared to the old setup.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/95811b1c-3268-49d7-b8c2-14da24b98c18)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/03fcfefe-c8b9-4fc7-bbca-299e8e21d613)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/c0b57bca-725f-4c8e-a312-6a1e9e2e7c9d)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/3021ca87-a41a-4d86-88aa-abfc3eae3248)

However, PBS_metallic was the same for both previously, so this brings Xiexetoon in line with it
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/2e065e8d-bfad-4118-af19-8eeb544baa33)

**Comment by epicEaston197** [comment] 2024-06-26 19:45
@NepuShiro
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/1761d7de-42c8-4979-b0f4-b42a21bc806a)

**Comment by Geenz** [comment] 2024-06-27 17:06
This looks like a misconversion that's breaking on the HDR end.  We didn't make any changes to the toon shader other than recompiling without any variant stripping enabled.  If need be we may just roll back the toon shader specifically to the previous version.

**Comment by epicEaston197** [comment] 2024-06-28 06:31
> If need be we may just roll back the toon shader specifically to the previous version.

That would be preferable

**Comment by Geenz** [comment] 2024-07-01 16:58
I've looked at this - and if anything the previous version was inconsistent with how linear HDR values are handled.  Corporate needs you to find the difference between these two orbs:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/341813/21a3dd26-7095-467a-ad60-c2d3cda2e537)

The one on the left is using PBS metallic, while the other on the right is using Xiexe toon.  Halving the intensity to 1.5:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/341813/4f78b1dd-6cd9-4157-acd7-8b39ebb99cf2)

It seems to yield the same results.

It's possible that somewhere along the way a full rebuild without variant stripping resulted in _something_ breaking with Unity's own color conversions.  Unity has its own internal "HDR" conversion for sRGB values.  We treat these as linear through and through - so if your range is bumping past something like 2 you will get some really strong bloom.

One thing we could do for assets is apply an adapter in the next update that "nudges" these values, whether driven or static for previous versions of this shader.  New content will need to be similarly nudged once you get into HDR or "overdriven" territory however.

**Comment by epicEaston197** [comment] 2024-07-01 17:02
> I've looked at this - and if anything the previous version was inconsistent with how linear HDR values are handled.

Yes I understand that 
but this breaks so many things And again gives a lot less wiggle room for overdriven colors (using linear)

**Comment by Geenz** [comment] 2024-07-01 17:04
> > I've looked at this - and if anything the previous version was inconsistent with how linear HDR values are handled.
> 
> Yes I understand that but this breaks so many things And again gives a lot less wiggle room for overdriven colors (using linear)

Sure - but if we're going to fix this, then it needs to be done in a way that does not introduce even more inconsistencies.  I'm not saying we're not fixing it, I'm saying we need to do so in a way that won't make content even more inconsistent for when we migrate to the new rendering engine.

**Comment by Geenz** [comment] 2024-07-01 17:13
Out of curiosity - was any of this content previously migrated? @epicEaston197 @NepuShiro?

**Comment by NepuShiro** [comment] 2024-07-01 17:18
> Out of curiosity - was any of this content previously migrated? @epicEaston197 @NepuShiro?

My avatar was migrated, but the Materials and everything was Re-done. Including my audio reactivity system, and its colors.

**Comment by epicEaston197** [comment] 2024-07-01 17:30
> Out of curiosity - was any of this content previously migrated? @epicEaston197 @NepuShiro?

My avatar was also migrated and the color was a bit off so it was made linear and the color driven to `3, 3, 3, 1`

**Comment by Geenz** [comment] 2024-07-01 17:32
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/341813/0a374144-dfb9-4ed6-b87a-1565d0f04caa)
Does this in line with what it looked like before?

**Comment by Geenz** [comment] 2024-07-01 17:36
This uses an adapter that will automatically be applied to **all old** Xiexe materials created prior to whenever this fix ships by adjusting HDR values against a modified gamma curve when the value is greater than 1 in any channel.  New ones will not have this adapter applied.

ProtoFlux should also be applied here - but if you're worried about that please send me a repro with flux applied to test against for this specific bug.

I'll look into adding a ProtoFlux node to allow you to decide how to adjust HDR values.

**Comment by epicEaston197** [comment] 2024-07-01 17:42
> ProtoFlux should also be applied here - but if you're worried about that please send me a repro with flux applied to test against for this specific bug.

This is the same model of my head except it uses the dark mode flux from my avatar and I've readjusted the values to be before I updated them
[green and black (head 2 with flux).zip](https://github.com/user-attachments/files/16057194/green.and.black.head.2.with.flux.zip) (Resonite package)

**Comment by Frooxius** [comment] 2024-07-04 23:00
I've merged this fix in 2024.7.4.1347, things should be okay now! Let us know if there's more issues!

**Closed by Frooxius** 2024-07-04 23:00 UTC
Labels: bug, triaged
