### ISSUE TITLE
video players desync audio and visuals or lose audio entirely after playing for long times

### ISSUE THREAD

**Issue by RueShejn** [Yellow-Dog-Man/Resonite-Issues#3200] opened 2024-11-20 00:10 UTC
### Describe the bug?

video players set to loop or stream audio seem to just stop playing audio randomly after 30min-1hr of continuous play, videos also desync sound from visuals in sessions with multiple users

only common thing ive been able to figure out is that it usually happens if the player is running for a while non-stop

### To Reproduce

spawn a video and set it to loop or spawn in a stream and wait

### Expected behavior

the videos should not lose sound to visual sync and the video players should not loose sound when playing normally

### Resonite Version Number

Beta 2024.11.19.479

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop, VR

### Log Files

[DESKTOP-L6KVB13 - 2024.11.19.479 - 2024-11-19 10_13_43.log](https://github.com/user-attachments/files/17822848/DESKTOP-L6KVB13.-.2024.11.19.479.-.2024-11-19.10_13_43.log)

### Additional Context

Sorry for the large log file it takes a while for these issues to popup

**Comment by shiftyscales** [comment] 2024-11-20 01:16
This has been previously reported in #1415. As far as I'm aware, this is just something that happens with the currently available playback engines. Whenever there is a client hitch / stutter, the sync will slowly drift with time, this can be seen in the `CurrentClockError` value on the `VideoTextureProvider`.

I assume it is something that will be improved / resolved with the VLC upgrade #1476 - but I'm curious if @Frooxius has any suggestions for ways this could possibly be improved in the interim?

In social contexts, users usually resolve this by briefly pausing and resuming playback, which will resynchronize the video and audio until they invariably drift noticeably out of sync again.

I have noticed this issue rather frequently while watching longer-form content with others, but I'm uncertain what all could be done to improve this issue in the short-term.

**Comment by ProbablePrime** [comment] 2024-11-25 08:51
This is a duplicate of #1415, the fix here is probably the VLC upgrade.

**Closed by ProbablePrime** 2024-11-25 08:51 UTC
Labels: bug, duplicate
