### ISSUE TITLE
Admin only slots in inspectors

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#1657] opened 2024-04-11 04:10 UTC
### Is your feature request related to a problem? Please describe.

There is currently no way of being able to hide certain slots within a world for scenarios where you want to provide builder level access but also don't want people accessing world level systems and assets directly (paid assets, security systems, games worlds, etc)

### Describe the solution you'd like

A security component that when applied to a slot the user will not be allowed to view the contents of that slot within the inspector unless the user is currently set as an admin

### Describe alternatives you've considered

security servers that will only check access level but really not not solve the problem of hiding content of the world while also allowing builder access

### Additional Context

this component would really help with the issue of worlds being locked down just because people don't want others seeing slots with sensitive information like a game world's game state data, slots with paid assets, security systems with auth based systems in them, etc

**Comment by jae1911** [comment] 2024-04-11 04:31
Probably a duplicate of #1103

**Closed as completed** 2024-04-11 06:30 UTC
Labels: duplicate, New Feature
