### ISSUE TITLE
Headless customSessionId not working

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#630] opened 2023-11-11 04:21 UTC
### Describe the bug?

The Headless customSessionid option is not currently functioning. Trying to connect via OpenWorld or FocusWorld ProtoFlux nodes displays a "Failed to establish connection" error. SessionInfoSource shows that the sesssion url has an unexpected string of characters in it.

### To Reproduce

- Set the `customSessionid` parameter to a valid value within a Headless config file
- Launch the headless client using the config file
- Attempt to join using an OpenWorld node, using the custom session id as a uri by appending `S-lnl-nat:///` to the beginning

### Expected behavior

The session should be join-able using the `lnl-nat:///S-<custom_session_id>` uri

### Screenshots

![Resonite_FqelWLb5AX](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/6cfab647-0a3a-4ed1-836a-3a148aa0af15)

### Resonite Version Number

Beta 2023.11.8.335

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[DESKTOP-1E2V3A8 - 2023.11.8.335 - 2023-11-10 20_12_09.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13324414/DESKTOP-1E2V3A8.-.2023.11.8.335.-.2023-11-10.20_12_09.log)

### Additional Context

A valid custom session id follows this format:
`<user_id>:<custom_string>`
Example:
`U-code807:GuavaGrid`
For a custom session id to be valid, the headless client must be logged in as the specified user

### Reporters

code807
badhaloninja

**Comment by liny-fox** [comment] 2023-11-11 04:28
Duplicate of #347?

**Comment by code807** [comment] 2023-11-11 04:36
Ah yes, this does appear to be the same problem. I never had to use tokens in the uri in the past, but it has been a while since I used my headless with a custom session id.

**Comment by ProbablePrime** [comment] 2023-11-11 04:38
Closing in favor of 347

**Comment by ProbablePrime** [comment] 2023-11-11 04:39
Sorry in closing this I wanted to clarify, @code807 you're headless is having the visibility issue with Contacts + in addition to custom session ids?

This issue does not mentioned contacts+ at all.

**Comment by code807** [comment] 2023-11-11 04:48
My session is not Contacts+, it is set to Anyone. It does appear to be related to the token issue mentioned in the other Issue. I have no experience with using tokens for OpenWorld uri's. In the past I did not use them at all, and the uri was just `lnl-nat:///` followed by the session id.

**Comment by ProbablePrime** [comment] 2023-11-11 04:50
Ok, then I call this sufficiently distinctive.

Next up, please provide the fully filled in values you are attempting to use for CustomSessionId in the config and the Join string.

**Comment by XDelta** [comment] 2023-11-11 05:52
It may boil down to the same issue as #347, revolving around the extra info that is now in the join link. In the linked issue, there just wasn't otherwise a way to join it as it was hidden.

**Comment by code807** [comment] 2023-11-11 06:26
Here are screenshots of the exact config line and the link I'm attempting to join the session with
![WindowsTerminal_ePYjc5NVzU](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/273741f7-b2b6-4f12-8122-364f07547767)
![Resonite_67ok1PFDJs](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/eea51546-0e61-4677-8f16-6991ff6e3c5f)

**Comment by ProbablePrime** [comment] 2024-09-28 05:01
I know what's going on here.

I was lazy, so grabbed a session I knew that had a custom session id:
![image](https://github.com/user-attachments/assets/f7ed6a54-2dce-49e5-85ca-cc9ee208482f)

Plugging this url into open world works:
![image](https://github.com/user-attachments/assets/4beae8b2-c753-43ca-b627-c21d489dfa89)

The issue here is the use of `lnl-nat:///`.

## lnl-nat urls

lnl-nat urls need an LNL Bridge ID in them to work, for example as pictured above, we see the resync lounge has:
`lnl-nat://aba6f27b-c51c-49ba-ac03-0bcc96cd97cc/S-U-BigGreenWolfy:SyncLounge`.

That first part:`aba6f27b-c51c-49ba-ac03-0bcc96cd97cc` is the id of bridge EU:
![image](https://github.com/user-attachments/assets/ed81800a-956b-4aa4-8069-823b0059d0ab)


The way an lnl-nat url, works is that it instructs Resonite, to communicate to the node id, in the url and ask how to reach the session.
So in this case it communicates to bridge eu and says "Hi where is `S-U-BigGreenWolfy:SyncLounge`", then the bridge provides information if it has it.

If there's no nodeid in the lnl-nat url its invalid and just won't work. That's how the format works. therefore `lnl-nat:///S-<custom_session_id>` will never work.

However, there is an alternative, which is basically the same.

## ressession:// urls

You can just use `ressession:///<custom session id>`.

So in our above example with the Sync Lounge, you can whack `ressession:///S-U-BigGreenWolfy:SyncLounge` into open world and it'll work!

## Conclusion
I'll be closing this issue as there isn't actually a bug here, but I will also be editing the wiki to cover the custom session ids.

**Closed by ProbablePrime** 2024-09-28 05:01 UTC
Labels: bug

**Comment by ProbablePrime** [comment] 2024-09-28 05:48
https://wiki.resonite.com/Custom_Session_IDs exists to explain all of this now.
