### ISSUE TITLE
OSC send/receive ProtoFlux nodes

### ISSUE THREAD

**Issue by 5H4D0W-X** [Yellow-Dog-Man/Resonite-Issues#2007] opened 2024-05-08 08:01 UTC
### Is your feature request related to a problem? Please describe.

OSC works by sending a value when a state changes. Since Resonite represents OSC as constant values that are written to on state change, some applications of OSC are currently difficult to implement in resonite, such as

- manually resending a value in the same state, without relying on the automatic resend interval
- receiving the same value multiple times (this is used for buttons in some OSC controllers, where releasing the button does not reset its state back to 0. This currently requires a Flux setup to automatically reset the OSC_Value back to the default state)
- receiving all OSC messages on a given port to, for example, automatically build a visualization UI based on all the different paths that are used in the messages, or create a log that shows all OSC messages that have been received

### Describe the solution you'd like

- OSC Port Events Node:
  - `OSC_Handler` input/global
  - `RootPath` input, filters incoming messages to those that are addressed to a path underneath this one (for example to only receive messages addressed to `/oscControl/buttons/`)
  - `OnReceived` call output
  - `Message` output (string, can be parsed manually)
  - `Path` output, the path of the message’s target value
  - `ArgumentIndex` output, the target argument index of the message
  - `Type` output, the type of the value in the message (such as float)
 
- OSC Path Events<T\> Node:
  - `OSC_Handler` input/global
  - `Path` input, filters messages for path like an OSC_Value
  - `ArgumentIndex` input, determines the argument index to receive updates for
  - `OnReceived` call output
  - `Message` output (direct value depending on the generic type overload of the node)

- Send OSC<T\> Node:
  - `OSC_Sender` input/global
  - `Path` input, path to send to
  - `ArgumentIndex` input, argument index to send to
  - `Message` input, value to send (type depends on node overload)
  - `Send` call input
  - `OnSent` call output
  - `OnFailed` call output

### Describe alternatives you've considered

N/A

### Requesters

ShadowX

**Comment by Dusty-Sprinkles** [comment] 2024-05-08 08:13
this is probably a duplicate of #1888

**Comment by 5H4D0W-X** [comment] 2024-05-08 08:18
This issue focuses on the impulse aspect of the nodes, which #1888 doesn't (although Cyro did comment about impulses on that issue). Of course I don't mind if this is closed in favor of #1888 or vice versa

**Comment by EmergencyTemporalShift** [comment] 2024-05-08 17:58
This one feels more complete, I would rather keep this one.

**Comment by ProbablePrime** [comment] 2024-08-20 04:54
Thanks for your issue, I'm moving conversation to #1888 for the conversation on this issue. We've got a few duplicates, so I'm merging into the one that Froox responded to.

**Closed by ProbablePrime** 2024-08-20 04:54 UTC
Labels: enhancement
