### ISSUE TITLE
XYZ inputs in new settings can be undo'd by Ctrl Z (and redo) which also affects worldspace

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#1661] opened 2024-04-11 09:11 UTC
### Describe the bug?

When editing things like Hand Tracking Offset, or Photo Resolution values, if you hit Ctrl Z (or Ctrl Y) you do a undo/redo step that affects both the settings and worldspace.

Interesting enough, a context menu undo/redo does not affect this.

### To Reproduce

1. Launch up resonite on Prerelease
2. Do a undoable action in session
3. Go to Photo Capture under User Interface 
4. Edit Photo Resolution to be something else ex: 512 for the x value and hit enter to confirm
5. Hit Ctrl Z (be it with the dash on or off)
6. Notice how the worldspace undoable action was affected and the setting change was reverted

### Expected behavior

Undoable/redoable actions should not affect both worldspace and userspace. I imagine it only affecting worldspace would be prefered.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/fd7f4f58-a31c-420f-82a7-bcd66a40e800
(ignore the mechanical keyboard user aka me)

### Resonite Version Number

2024.4.11.484

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-V75BHJO - 2024.4.11.484 - 2024-04-11 04_33_24.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14943991/DESKTOP-V75BHJO.-.2024.4.11.484.-.2024-04-11.04_33_24.log)

### Additional Context

Note, I alt F4'd in this log to exit.

### Reporters

Ohzee

**Comment by JackTheFoxOtter** [comment] 2024-04-11 09:14
Duplicate of #513

**Comment by ohzee00** [comment] 2024-04-11 09:18
> Duplicate of #513

Yep alright, weirdly enough I tested toggles and they do not do ctrl Z. Enums however do, I did not check those, given I misfiled this issue anyways I'll just close in favor of that duplicate given that the underlining issue is still there.

**Comment by JackTheFoxOtter** [comment] 2024-04-11 09:18
Oh that might be a seprate issue if the toggles don't generate an undo step.

**Comment by ohzee00** [comment] 2024-04-11 09:20
> Oh that might be a seprate issue if the toggles don't generate an undo step.

The issue's example gives a enum of primary hand which still happens in the new settings (just checked).
So I think these are the same issue at the end of the day.

**Closed** 2024-04-11 09:21 UTC
Labels: bug
