### ISSUE TITLE
Logging out takes MINUTES

### ISSUE THREAD

**Issue by ELO621B73** [Yellow-Dog-Man/Resonite-Issues#2685] opened 2024-07-29 00:30 UTC
### Describe the bug?

I was logging out to switch accounts and it was taking literal minutes.

### To Reproduce

Start resonate with an account logged in and log out. Come back a couple of minutes later and you MIGHT be logged out.

### Expected behavior

Logging out to be nearly instant.

### Screenshots

![image](https://github.com/user-attachments/assets/40788081-8b7e-484b-8397-d8536c153a3e)

### Resonite Version Number

Beta 2024.7.25.1284

### What Platforms does this occur on?

Windows

### What headset if any do you use?

screen

### Log Files

[OLDFART - 2024.7.25.1284 - 2024-07-28 20_19_52.log](https://github.com/user-attachments/files/16405854/OLDFART.-.2024.7.25.1284.-.2024-07-28.20_19_52.log)

**Comment by kulzae** [comment] 2024-07-29 01:28
duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1086

**Comment by ProbablePrime** [comment] 2024-07-29 02:52
Thank you for your report, as described by Kulzae, this is a duplicate of #1086 we'll therefore be closing this issue

**Closed by ProbablePrime** 2024-07-29 02:52 UTC
Labels: bug
