### ISSUE TITLE
Resonite bot in-game - Add generic info response when user attempts to message the Resonite bot account

### ISSUE THREAD

**Issue by rampa3** [Yellow-Dog-Man/Resonite-Issues#2684] opened 2024-07-28 20:24 UTC
### Is your feature request related to a problem? Please describe.

From discussion during moderation office hours on 2024-07-28 - people might attempt to message the Resonite bot in-game in some cases.

### Describe the solution you'd like

I would like to suggest adding a generic response that the bot would reply to any non-command message sent to it, which would state how to list the bot commands, and also additionally where to go for moderation issues, support and bug reports.

### Describe alternatives you've considered

There are no applicable alternatives I could think off.

### Additional Context

\<office hours recording will be linked here when uploaded\>

### Requesters

rampa_3

**Comment by ProbablePrime** [comment] 2024-07-29 02:56
Thanks for your report, this is unfortunately a duplicate of #124 

Your idea about a generic response that's helpful and has resources is a good one though!

**Closed by ProbablePrime** 2024-07-29 02:56 UTC
Labels: enhancement
