### ISSUE TITLE
Add Protoflux node "User Role"

### ISSUE THREAD

**Issue by archer007** [Yellow-Dog-Man/Resonite-Issues#1915] opened 2024-05-02 08:26 UTC
### Is your feature request related to a problem? Please describe.

There is no way to programmatically get a user role from flux in non-userspace worlds

### Describe the solution you'd like

Add Protoflux node "User Role" similar to existing node "User Username" with input being User and output being a String of the user's role.

### Describe alternatives you've considered

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/297

However you don't need full permissions checking or other security features since it's a String and only intended to describe the user role

### Requesters

Archer42

**Comment by ProbablePrime** [comment] 2024-05-02 08:30
I'm sorry this is a duplicate of #297.

If we gave it to you as a string, users would use it for security matters even if we told them not to.

**Closed by ProbablePrime** 2024-05-02 08:30 UTC
Labels: enhancement

**Comment by JackTheFoxOtter** [comment] 2024-05-02 08:38
As per your comment in #297:

> We want to do this, we just need to make sure we're doing it correctly.

Is there already an issue for doing it the "correct" way? If not, can you create one? I agree this would be useful information in some circumstances, but I also agree that just outputting a string would make people check `if permission == "Builder" then...`, which wouldn't work reliably considering the permission names and what they mean are completely up to the world creator.

**Comment by ProbablePrime** [comment] 2024-05-02 08:46
We can totally do it in the correct way, that will require development though. 

I'd recommend we continue conversation in #297
