### ISSUE TITLE
UserRootOverrideAssigner acts weirdly in VR

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1808] opened 2024-04-22 09:33 UTC
### Describe the bug?

when using the `UserRootOverrideAssigner` in VR it acts really weirdly often your view will start to jitter and cause motion sickness

### To Reproduce

set up the `UserRootOverrideAssigner` like you normally would and have it set to view make sure that the override object is on your head bone or your head proxy and when do you put your user root into the equipping slot you will notice that your viewpoint is really jittery

### Expected behavior

The behavior of the `UserRootOverrideAssigner` should be consistent between desktop and VR users

### Resonite Version Number

2024.4.18.1398

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A

### Additional Context

a user in discord was commenting about the behavior of this component in VR being inconsistent with desktop mode and causing motion sickness

here's a few comments from them taken from the discussions channel I was given permission to use these in this issue

> you have the information and the recreation steps are pretty simple
> override view while in vr, wiggle head
> it doesn't even have to be parented to you, you can get the wiggles if it's completely stationary 
> like it's moving it by the original position and then a second time
> yeah it is vr only cause even the desktop mirror isn't getting it
> fun

the user has also shared a video of this issue

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/5285b4e2-f4dc-45ae-9b8d-2f0964ad6abf

> here's a video for you
> that's the view parented to a completely stationary object in the world
> it shouldn't be wiggling
> it not showing up on the steam vr view or in the resonite desktop mirror is super weird though but the meta cast got the wiggling

### Reporters

@epicEaston197, KarasuTengu on discord

**Comment by lxw404** [comment] 2024-04-22 09:43
Duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1520

**Comment by epicEaston197** [comment] 2024-04-22 09:46
> Duplicate of: #1520

yeah I agree with this but your issue should be tweaked to make it specifically mention it only happens to VR users desktop users are completely fine your issue makes it look like an overall issue with the component on both platforms

**Closed as not planned** 2024-04-22 17:48 UTC
Labels: bug, duplicate
