### ISSUE TITLE
While Loop in ProtoFlux runs on Main Thread, instead of Asynchronously, leading to instability

### ISSUE THREAD

**Issue by NukiRaccoon** [Yellow-Dog-Man/Resonite-Issues#1456] opened 2024-03-07 19:19 UTC
### Describe the bug?

Just caused Resonite to freeze after implementing a While Loop that had some sort of issue which I'm guessing made it infinite.  This shouldn't have been possible, because While Loops shouldn't be able to stall the main loop that significantly: the only explanation I can think of is it's somehow running on a main thread instead of a secondary one.

### To Reproduce

I don't have the code because I didn't think to save before I ran it, but it seemed to be a while loop running from a condition that was never reached: a float variable set elsewhere reaching 1, and the while loop was supposed to be a wait-timer to set it back to zero.

### Expected behavior

I didn't expect that to freeze the program.  It should've just slowed it down while the while thing freaked out, but it froze everything.

### Screenshots

Can't get screenshots: frozen.

### Resonite Version Number

Beta 2024.3.1.1178

### What Platforms does this occur on?

Windows

### Log Files

not possible because freeze, not crash

### Reporters

Nuki

**Comment by Frooxius** [comment] 2024-03-07 19:28
I'm going to close this, because there are several issues with this:
- It is supposed to run on main thread, you cannot just "force" code to be multi-threaded, you're asking us to do something we cannot do
- It's a duplicate: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/774
- You have not provided logs. We require logs for these kinds of things. Freeze does not make the logs disappear from the system.
- You don't provide clear reproduction steps. If you encounter a bug, please take some time to see if you can replicate the behavior first before reporting

**Closed by Frooxius** 2024-03-07 19:28 UTC
Labels: bug
