### ISSUE TITLE
Sync method to add/remove Selective/Exclude Render for camera components

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#1911] opened 2024-05-02 02:36 UTC
### Is your feature request related to a problem? Please describe.

I would like a good way to control what the camera sees with Flux.
The camera component has Selective/Exclude Render fields, but there is no easy way to add/remove these from Flux.

### Describe the solution you'd like

Add a Sync method to add/remove Selective/Exclude Render for the Camera component.
This is like a Sync method to add/remove ExcludeUser that AudioOutput component has.
It takes any Slot as an argument and adds or removes the Slot from the list.

Perhaps something like the following
AddSelectiveSlot(Slot slot)
RemoveSelectiveSlot(Slot slot)
ClearSelectiveSlots()
IsSlotSelected(Slot slot)

AddExcludeSlot(Slot slot)
RemoveExcludeSlot(Slot slot)
ClearExcludeSlots()
IsSlotExcluded(Slot slot)

### Describe alternatives you've considered

Create a bunch of SelectiveRender fields in advance and set them to Dynamic variable so they can be accessed from Flux.

### Additional Context

I tried this alternative in my MMC entry, Sticker Studio.
The purpose was to show only the avatar model to the camera, excluding the nameplates and lasers contained within the user.
I requested this because I wanted an easier way to achieve this.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/f7f35715-143f-4b7e-960b-7551e29c1380)

### Requesters

orange3134

**Comment by shiftyscales** [comment] 2024-05-03 16:27
Modifying lists would be handled as a part of generic collections support in ProtoFlux #572, @orange3134. As such, this is a duplicate of that issue. I'd recommend that you, and others thumb up that issue 👍 to express interest in seeing it prioritized.

> A set of generic nodes for working with various collection types - whether it's accessing elements, iterating or mutating those collections (adding/removing/modifying elements).

**Closed by shiftyscales** 2024-05-03 16:27 UTC
Labels: enhancement
