### ISSUE TITLE
Locomotion Animation Configurations being reset to default

### ISSUE THREAD

**Issue by OfficialXau** [Yellow-Dog-Man/Resonite-Issues#2894] opened 2024-09-06 19:19 UTC
### Describe the bug?

LocomotionAnimationConfiguration components that were saved or exported into Resonite Packages last update and spawned in this update are reset to default.

### To Reproduce

Spawn an avatar or item with a LocomotionAnimationConfiguration component that was saved before Beta 2024.9.6.626 (resdb:///e46ef05ead7622c088adddc22edd26368df40ec882e9701323fef1615e0c4c67.brson for example) and review the component values in an inspector. For an example of this issue on this item, gait 0 should have almost everything at the lowest setting on the sliders.

### Expected behavior

LocomotionAnimationConfiguration components that were created before this update should spawn in with their custom values intact.

### Screenshots

![image](https://github.com/user-attachments/assets/46240028-a730-4224-93e9-f72742a3a1ef)

### Resonite Version Number

Beta 2024.9.6.626

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest, Desktop (as far as I know, affects all)

### Log Files

[XAU-AIR-SUPER - 2024.9.6.626 - 2024-09-06 18_10_01.log](https://github.com/user-attachments/files/16911111/XAU-AIR-SUPER.-.2024.9.6.626.-.2024-09-06.18_10_01.log)

### Additional Context

If for any reason the link doesn't work, here's a Resonite Package of Orange's configuration, though I'm afraid I don't have one of Gearbell's, which is the original one linked.
[LocomotionConfigByOrange.zip](https://github.com/user-attachments/files/16912115/LocomotionConfigByOrange.zip)

### Reporters

Xau, Charizmare, Inucune, GyztorMizirath

**Comment by paradoxical-autumn** [comment] 2024-09-06 19:28
Dupe of #2893, Froox's comment contains an important PSA though:

> Do not resave any of these. I'll push a fix, which will make them load properly.
If you save them after they reset, they'll be lost.
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2893#issuecomment-2334675160

**Comment by OfficialXau** [comment] 2024-09-06 19:32
> Dupe of #2893, Froox's comment contains an important PSA though:
> 
> > Do not resave any of these. I'll push a fix, which will make them load properly.
> > If you save them after they reset, they'll be lost.
> > [#2893 (comment)](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2893#issuecomment-2334675160)

Aw, dang. I've been working on this for an hourish and checked beforehand. Guess I didn't check good enough before sending ^^;

**Comment by Frooxius** [comment] 2024-09-06 20:04
Oh I didn't realize there were two issues for this. Fixed in 2024.9.6.1185 though, thanks!

**Closed by Frooxius** 2024-09-06 20:04 UTC
Labels: bug
