### ISSUE TITLE
Blendshapes not Importing Properly

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#912] opened 2023-12-16 06:46 UTC
### Describe the bug?

Imported .fbx models with blendshapes have their blendshapes automatically reordered and renamed. This bug appears to not affect .gltf files, but is noticeable on .fbx imports. The order of the blendshapes is important in models like avatars, where groups of related blendshapes will generally be organized in order by body location.

### To Reproduce

- Import any .fbx model with blendshapes
- Inspect the model and observe the blendshape order/names

### Expected behavior

Blendshapes for fbx models should be ordered as they are in the fbx file upon import, similar to how gltf imports are treated.

### Screenshots

![Resonite_enuYy4va4f](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/cbaeb636-18da-47e5-a7fd-9df3279f745e)

### Resonite Version Number

Beta 2023.12.15.22

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-1E2V3A8 - 2023.12.15.22 - 2023-12-15 22_29_05.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13691638/DESKTOP-1E2V3A8.-.2023.12.15.22.-.2023-12-15.22_29_05.log)

### Reporters

code807
June

**Comment by Frooxius** [comment] 2023-12-16 06:51
This is a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/627

**Closed by Frooxius** 2023-12-16 06:51 UTC
Labels: bug, duplicate
