### ISSUE TITLE
Settings Menu: Graphics - VSync : Visualisation of the status switch is on and off at the same time in VR

### ISSUE THREAD

**Issue by Muppeq** [Yellow-Dog-Man/Resonite-Issues#2880] opened 2024-09-05 22:46 UTC
### Describe the bug?

For me the VSync switch status display is not consistent if I start resonite in VR: the position of the switch and the '1' say: on, but the red color says: off.

This does not happen for me if I start resonite in desktop, then i can toggle it and it shows a normal 'on' or 'off' state.

### To Reproduce

Start resonite in VR and open the settings menu, select Graphics, look at the VSync setting.

### Expected behavior

Show the status as on or off, don't send mixed signals.

### Screenshots

![20240906002157_1](https://github.com/user-attachments/assets/31a08aac-5e30-4013-9b6c-79e6c8e2d196)

### Resonite Version Number

2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-164NKSS - 2024.9.4.357 - 2024-09-06 00_20_27.log](https://github.com/user-attachments/files/16900882/DESKTOP-164NKSS.-.2024.9.4.357.-.2024-09-06.00_20_27.log)

### Reporters

Muppeq

**Comment by Frooxius** [comment] 2024-09-05 22:57
This is not a bug. VSync cannot be controlled while VR is active, this is limitation of Unity.

**Comment by shiftyscales** [comment] 2024-09-05 23:04
This is a also a duplicate of #1996. In that issue, @Frooxius had suggested adding a quick note to the setting descriptions indicating why they're disabled- that could still be a good option as a holdover to try and minimize possible confusion about these settings being disabled.

**Closed by shiftyscales** 2024-09-05 23:04 UTC
Labels: by design

**Comment by Muppeq** [comment] 2024-09-05 23:08
I know I can't switch VSync in VR, but if this is trying to show that the setting is on in desktop but currently off because VR the display is not easy to understand.  I would expect this setting then to be off (switch on the left, showing 0 in red color) in VR. I don't mind the setting to be off, but I wouldn't show the 1 on an 'off' setting.

**Comment by shiftyscales** [comment] 2024-09-05 23:11
The stored value remains the same, @Muppeq - it shows what the setting is set to, even if that setting is not applicable to the current hardware configuration.

It'd take additional engineering time to force it to display "off" despite the actual stored value, which I don't think is worth the engineering time for a solution that provides less information to the end-user.

In other words the setting **is** on if you have it enabled, even if it can't be used at that time.
