### ISSUE TITLE
Tutorial for migrating from an existing game

### ISSUE THREAD

**Issue by imagitama** [Yellow-Dog-Man/Resonite-Issues#932] opened 2023-12-19 07:09 UTC
### Is your feature request related to a problem? Please describe.

I am guessing many first time users are migrating from an existing game such as VRChat. The first thing they would want to do is migrate their VRChat avatar into this game. The learning curve is _insanely_ big (similar to learning Unity I know) and the steps for migrating specific features of a VRChat avatar are non-existent.

I am betting many people like myself try to migrate their VRC avatar into Resonite, struggle immensely, then bail on the entire game and never touch it again because it was too difficult. I understand the appeal of the game is to build stuff in VR and work together, etc. but some people just want to get the "bare minimum" working first (ie their personal avatar they are used to and have muscle memory with).

### Describe the solution you'd like

When the user signs up the game should immediately ask them what their experience level is at:

- first time in VR
- experienced VRChat player
- experienced VRChat avatar creator
- experienced NeosVR player
- skip

Depending on the choice, the game will present the user with a platform-specific tutorial.

For experienced VRChat avatar creators it will guide them through migrating their original avatar including as many features as they can. It will tell them about the specific differences in the games and try and answer as many common questions:

- the fundamental differences between the 2 games
- features of avatars that can be recreated in Resonite:
  - importing an FBX or .obj with its textures
  - recreating Poiyomi and other custom shaders
  - permanently changing its shape keys / blendshapes
  - importing an FBX and inserting it under a specific bone
  - PhysBones/DynamicBones
  - overriding idle/locomotion/sitting/prone animations
  - hand gestures (make a finger gun and it plays a facial animation)
  - Unity parent/other kinds of constraints
  - a radial menu on your hand for adjusting parameters synced with other players
  - custom Unity Animator controllers for playing complex animations / state machines
- features that cannot be recreated (but are on the roadmap?):
  - custom shaders
  - etc.

### Describe alternatives you've considered

In the meantime you could create a migration guide in your wiki or website or anywhere. It should explain the step-by-step instructions for migrating a VRChat avatar with as many features ported over as possible.

### Additional Context

Discord discussion: https://discord.com/channels/1040316820650991766/1186531891076157580

**Comment by JackTheFoxOtter** [comment] 2023-12-19 08:55
From a new user's perspective, I think one of the worst things you can do is immediately draw comparisons to other platforms. For once, many other platforms (I'm using VRC here because that seems to be your main focus) have a completely different focus (primarily social VR) than Resonite (primarily real-time cooperative building). There's many things that don't translate super well because of this, but more generally you don't want the first thing people see be "this is how you do the exact same things you know from other games in this game", you want them to learn and experience what makes the platform special.

Secondly, there are a lot of technical differences that basically prevent you from 1:1 importing most VRChat avatars, some of while relating to the points you've mentioned:
- Resonite runs on a custom engine and uses Unity only for rendering, which means most Unity-specific knowledge doesn't apply
- Resonite has no compatibility with custom Unity shaders, and currently does not support custom shaders built in-game (#632)
- Resonite does not currently support avatar animations without complicated workarounds
- Resonite does not currently support independant state machine Logic (#565)
- Values are networked by default, there is no need to create specific logic to sync them with other players
- Resonite has a completely unique visual programming language that allow for a lot of things not possible on other platforms

There are more, but I hope this help to illustrate my point. Now, that being said, what is important is showing people how to import a rigged model into the game and turn it into an avatar, I would just generalize it much further than limiting it to only VRC avatars. There are already some great community resources online (look up "Resonite Avatar" on YouTube), and more will be coming as time goes on. I think featuring links to some of those in-game would be a pretty simple way guide new players into the right direction. Official tutorials would be good as well.

Additionally, Resonite has a super eager volunteer team of "Mentors" that love to help new users when they struggle with something. In general, new users are encouraged to ask questions either directly in-game or on the Discord to find someone who can help them quickly. This isn't a fix for the missing documentation a Wiki / official tutorials will provide, but for the time being is probably the simplest way for users to get help in setting up a custom avatar.

**Comment by Stellanora64** [comment] 2023-12-19 09:11
Possibly a duplicate of #109 ? But it's definitely related,  also #539 .

**Comment by imagitama** [comment] 2023-12-19 10:45
> Possibly a duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/109 ? But it's definitely related. also https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/539 is related.

Yes for sure. It's all related.

Since there are so many issues surrounding the tutorial and user onboarding process is there anything on the roadmap for it? There isn't much point to a social game if nobody is getting past the tutorial step.

> Also from a legal stand point I don't know if they can directly ask what platform a user is coming from as they do not have the right to those trademarks. (I'm not a lawyer so take that with a grain of salt)

I understand this and I would probably just ask "have you built avatars from other games VR before?" as 99% of the time it will be VRChat.

Then again I play Dota 2 and in their tutorial it asks you if you have played League Of Legends which is their direct competitor so maybe it's okay? You aren't exactly _stealing_ anything.

**Comment by JackTheFoxOtter** [comment] 2023-12-19 12:05
> You kind of have to draw comparisons. They are Resonite's main "competitor". The vast majority of users of Resonite are probably coming from VRC who is the market leader by a huge lead right? You want people to pause playing their favourite VR social game to try out Resonite.

Do you? I don't. I would like users to pick the place they are enjoying the most and stick with that. I don't think the competition mindset is necessarily super healthy for the project. Instead of focusing our efforts on how other platforms are doing things, if we focus on how we are doing things and try to polish that, I think the end user experience will be a better, and more unique one.

> That is true but that shouldn't stop the game from explaining how to do most of the stuff other VR social games can do. I expect to be able to do a finger gun on my hand to make my face change - why is it so difficult to implement?

Because we don't have a native way of gesture tracking yet. There are plenty of user-made systems, but they are all a bit complex to implement. I would however argue that this is WAY past the basic avatar setup steps we are talking about. I think #42 is worth a read here, as that provide a possible cross-controler solution for the gesture problem (many controllers not having individual finger tracking).

> Someone in one of those issues said it really well - you shouldn't have to talk to anyone to get started in a game. Personally I'm not a mentor kind of person.

The game is complex. If you want to draw comparisons, compare it more to Unity itself than to VRC. When you get started with Unity, you kind of have to watch a whole bunch of tutorials, read documentations and play around with it until you get comfortable with using it. This is just the nature of being a powerful editor. I can tell you from experience that one thing this community really excels at is providing support and helping each other. This is not something you have in most other sandbox games / editors, as it is a direct result of the "everything is synced" architecture. Again, I am not saying stuff shouldn't be documented better, but I'm saying that until we are at that point, we shouldn't underestimate the value of helping each other.

To get back to the point of this issue though, I would say we should focus on improving documentation accross the board (#1 is probably going to be the next major step in that), but beyond that perhaps providing a system to promote community tutorials in-game could solve some of the current issues without putting too much additional work on the developers.

**Comment by Geenz** [comment] 2023-12-19 13:08
Tutorials for common operations such as importing an avatar are reasonable enough, however as noted drawing direct comparisons between Resonite and <insert platform here> is not a great idea.

A very simple explanation as to why is: we're not them.

There are many fundamentally different things between Resonite/FrooxEngine and most engines.  You will find it to be extremely hit or miss when trying to find 1:1 mappings between one platform's way of, for example, setting up an avatar vs. another's.  In this regard, it's better to focus on _the specific thing you're trying to achieve_ than drawing a comparison to another platform.

I'll also note that attempting to draw a direct comparison to a game engine such as Unity also isn't a great way to look at Resonite.  The entire platform can be seen as a collaborative game engine of sorts, yes, but that's not really the comparison you should draw here.

**Comment by FlameSoulis** [comment] 2023-12-20 21:49
Just my 5 cents on the table, but for Davinci Resolve, its initial setup wizard outright asks you what previous system you were using so they can match the inputs to be more tailored to you if coming from something like Premiere and the like. This isn't new; depending on what you can do with that information, it is potentially helpful.

**Comment by imagitama** [comment] 2023-12-21 04:17
>  As for the finger emote system: I hate it. I get that people are used to it, but being used to something that is not a great system to begin with isn't a direct excuse to continue using it. 

What better way is there to animate my ears while I am mid-conversation without opening up a menu?

**Comment by gameboycjp** [comment] 2023-12-24 04:17
As for the former, I'd say they're completely different. Sure, they both facilitate socialization in VR, but I'm willing to argue it's a VRC competitor in the same way Second Life or Bonelab Fusion is, which is that it's an apples and oranges comparison. 

For the latter, I personally use scripting to act on my index touchpads/analog and capacitive touch buttons on quest for all of my facial puppeteering. It's similar to gestures, but it gives way more control, and it's really not something I can live without anymore.

**Comment by shiftyscales** [comment] 2024-05-23 18:30
This issue is better handled by #109 / #539, and generalized documentation, e.g. on the [wiki](https://wiki.resonite.com/Main_Page) and making it easier to find existing documentation. E.g. adding a help screen to the dash. https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1123

Resonite users can come from all sources. They may have prior experience with another platform like VRChat, but we also get users from other places, e.g. SL, or users that have never used a platform like Resonite before.

The best thing we can do for everyone is to best explain and document how Resonite and its systems work such that anyone can learn regardless of experience level with other platforms, because Resonite is its own platform.

**Closed by shiftyscales** 2024-05-23 18:30 UTC
Labels: enhancement
