### ISSUE TITLE
Color(X) to Hex Short Code does bad math

### ISSUE THREAD

**Issue by Sharkmare** [Yellow-Dog-Man/Resonite-Issues#2414] opened 2024-06-28 04:11 UTC
### Describe the bug?

ColorX to hex short code has values ranging form 0 to 10 instead of 0 to F

### To Reproduce

Red into Color X to Hex Code
Enable Shortcode
Receive 1000

### Expected behavior

F00

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34294231/a16a598a-306a-48a7-991d-b4f0abd5c9e6)

### Resonite Version Number

2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index, Vive Pro eye, Quest 2, Pico 4

### Log Files

.

### Reporters

Sharkmare / Eldritchkaiju

**Comment by ProbablePrime** [comment] 2024-06-28 04:12
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/384 

also tagging https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1404 as related

**Closed by ProbablePrime** 2024-06-28 04:12 UTC
Labels: bug

**Comment by Sharkmare** [comment] 2024-06-28 04:28
huh no clue how i didnt see those when searching "hex" weird

**Comment by ProbablePrime** [comment] 2024-06-28 08:50
No worries, it happens :D
