### ISSUE TITLE
No worlds in world tab

### ISSUE THREAD

**Issue by SaraLouisa** [Yellow-Dog-Man/Resonite-Issues#2028] opened 2024-05-12 04:56 UTC
### Describe the bug?

the worlds Tab is completely empty

### To Reproduce

No Idea

### Expected behavior

list of Worlds to be there

### Screenshots

![2024-05-12 05 49 51](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/154685179/028814d8-aafb-49a7-b1d2-3190064d79d4)

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index 

### Log Files

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15285126/Player.log)

**Comment by stiefeljackal** [comment] 2024-05-12 05:07
This is a duplicate of #466. If you read the thread in that issue, it should have a workaround to restore the screen and keep the facet on there.

**Comment by SaraLouisa** [comment] 2024-05-12 06:10
it took a couple of resets , but has worked thanks

**Closed** 2024-05-12 06:10 UTC
Labels: bug, duplicate
