### ISSUE TITLE
Eye rotation for eye tracking taken over by colliders 

### ISSUE THREAD

**Issue by Nexulan** [Yellow-Dog-Man/Resonite-Issues#1053] opened 2024-01-02 16:59 UTC
### Describe the bug?

When a user with eye tracking gets close to a collider it takes over their eye tracking for the user.

### To Reproduce

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38895890/2bc06abf-ac12-41ef-bdd5-97caa7c22b18

### Expected behavior

Expected behavior is for eye tracking to not be affected by colliders.

### Resonite Version Number

Beta 2023.12,21.1127

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[DESKTOP-810672E - 2023.12.21.1127 - 2024-01-01 16_32_55.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13812186/DESKTOP-810672E.-.2023.12.21.1127.-.2024-01-01.16_32_55.log)

### Additional Context
![2024-01-02 16 37 21](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38895890/156bddae-65f5-4e96-94d9-48f864ea7221)

_No response_

**Comment by Frooxius** [comment] 2024-01-02 23:11
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/263

**Closed by Frooxius** 2024-01-02 23:11 UTC
Labels: bug
