### ISSUE TITLE
Major updates log user out

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1924] opened 2024-05-03 08:32 UTC
### Describe the bug?

When upgrading to a new major update (non-compatible with previous), I get logged out of the game on the first start and have re-login.

The "remember me for 30 days" was checked on last login.

Some settings such as audio interfaces also get reset.

### To Reproduce

1. Log into Resonite
2. Wait for major update
3. Upgrade
4. Start game
5. Logged out on game start

### Expected behaviour

I should stay logged in.

### Screenshots

![Resonite_1MuEwjxwy9](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/84f55f74-e768-4ff2-a137-822562b38424)

### Resonite Version Number

2024.5.3.467

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index; Desktop

### Log Files

[TETHYS - 2024.5.3.467 - 2024-05-03 11_29_56.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15197709/TETHYS.-.2024.5.3.467.-.2024-05-03.11_29_56.log)

### Reporters

U-j4 | j4.lc (Discord)

**Comment by ohzee00** [comment] 2024-05-03 08:36
[DESKTOP-V75BHJO - 2024.5.3.467 - 2024-05-03 04_06_40.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15197725/DESKTOP-V75BHJO.-.2024.5.3.467.-.2024-05-03.04_06_40.log)
Here is my log of the exact same thing happening, reproducing this is really difficult given it happens only on updates but it has been consistent these past few days with a update.

**Comment by Readun** [comment] 2024-05-03 08:39
It interestingly only startef since the update before the current one (haven't checked yet if the new update with Texture resolution will do that too)

Maybe we can pinpoint on when it started to happen?

**Comment by Frooxius** [comment] 2024-05-03 08:49
Can you share the log from session immediately before the one that logged you out?

**Comment by jae1911** [comment] 2024-05-03 08:54
> Can you share the log from session immediately before the one that logged you out?

Here is the log file for the session right before being logged out.
Some notes:
- It is super large due to #1522 
- It has mods

Hosted to avoid GitHub's limit: https://bm.777.tf/TETHYS%20-%202024.5.1.68%20-%202024-05-02%2017_32_59.log

**Comment by Frooxius** [comment] 2024-05-03 09:00
Thanks! One thing I see that is likely culprit there - UID calculation has failed in the last build before this one, which meant it computed it by fallback method, which results in a different UID. In the latest log, your UID is calculated normally. 

We use UID to make sure that your login is only usable from the same machine as last time. Since UID changed, the token is invalid.

I'm not sure why it failed in previous build, it looks like one of the assemblies failed to load that were needed for it. I don't know if that's result of a mod or something else got messed up, but it's likely why the log out happened.

We'll have to see if it happens again.

**Comment by Banane9** [comment] 2024-05-03 10:16
Ah, and here I was wondering why I was randomly not logged in when launching Resonite yesterday

**Comment by shadowpanther** [comment] 2024-05-03 12:15
> I'm not sure why it failed in previous build, it looks like one of the assemblies failed to load that were needed for it. I don't know if that's result of a mod or something else got messed up, but it's likely why the log out happened.

I don't use any mods, but the same happened to me too.

**Comment by gameboycjp** [comment] 2024-05-03 20:38
[DESKTOP-3EE2DAL - 2024.5.3.561 - 2024-05-03 13_20_45.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15204857/DESKTOP-3EE2DAL.-.2024.5.3.561.-.2024-05-03.13_20_45.log)
No idea if more logs will help, but I'll hand mine over anyways. I don't use mods, so this log will be clean. I did not log back in during this run.

**Comment by GrayBoltWolf** [comment] 2024-05-04 02:11
Same issue here, getting annoying to have to re-login every time there's an update

and there's like 3 updates a day sometimes

**Comment by Frooxius** [comment] 2024-05-04 04:44
@GrayBoltWolf Did every single of the updates released in a day log you out? Are you able to share logs for these?

Generally if you have this happening, we'd need logs from the session immediately before being logged out and after, otherwise we can't really do anything with this.

There is nothing about the updates that would inherently cause to be logged out. In J4's case it was because a dependency library failed to load for some reason, which changed the UID and invalidated the token, but that seems more like a busted install or something.

**Comment by GrayBoltWolf** [comment] 2024-05-04 12:43
> @GrayBoltWolf Did every single of the updates released in a day log you out? Are you able to share logs for these?
> 
> Generally if you have this happening, we'd need logs from the session immediately before being logged out and after, otherwise we can't really do anything with this.
> 
> There is nothing about the updates that would inherently cause to be logged out. In J4's case it was because a dependency library failed to load for some reason, which changed the UID and invalidated the token, but that seems more like a busted install or something.

This has happened to myself and Ralinesh both, two times in the last week. I'll try to remember to save logs before launching.

**Comment by Frooxius** [comment] 2024-05-04 18:51
@GrayBoltWolf I need more details to understand which builds is this affecting. 

When you say it happened twice a week, is that with every single build released? Or it happened with two builds?

Without logs though, we won't be able to do much.

**Comment by GrayBoltWolf** [comment] 2024-05-04 19:42
> @GrayBoltWolf I need more details to understand which builds is this affecting.
> 
> When you say it happened twice a week, is that with every single build released? Or it happened with two builds?
> 
> Without logs though, we won't be able to do much.

The recent ones I can remember for sure are: 2024.5.1.68 and 2024.5.3.1229

Before 2024.5.1.68 logged me out:
[DESKTOP-KHSI045 - 2024.4.30.495 - 2024-04-30 20_51_22.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15210794/DESKTOP-KHSI045.-.2024.4.30.495.-.2024-04-30.20_51_22.log)

When 2024.5.1.68 logged me out:
[DESKTOP-KHSI045 - 2024.5.1.68 - 2024-05-01 20_58_04.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15210795/DESKTOP-KHSI045.-.2024.5.1.68.-.2024-05-01.20_58_04.log)

Before 2024.5.3.1229 logged me out:
[DESKTOP-KHSI045 - 2024.5.1.68 - 2024-05-01 20_59_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15210786/DESKTOP-KHSI045.-.2024.5.1.68.-.2024-05-01.20_59_35.log)

After 2024.5.3.1229 logged me out:
[DESKTOP-KHSI045 - 2024.5.3.1229 - 2024-05-03 22_07_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15210783/DESKTOP-KHSI045.-.2024.5.3.1229.-.2024-05-03.22_07_50.log)

**Comment by ExoTheWicker** [comment] 2024-05-05 01:08
I've had the same issue after each update. (I'm currently gathering logs and will reply when I have them)

**Comment by ExoTheWicker** [comment] 2024-05-05 01:13
> I've had the same issue after each update. (I'm currently gathering logs and will reply when I have them)

I've included logs for sessions before and after updates.

[ExoTheWicker - logs.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211408/ExoTheWicker.-.logs.zip)

**Comment by Frooxius** [comment] 2024-05-07 08:42
This *might* be fixed in 2024.5.7.505

I'm not 100 % sure of what's making the library freak out sometimes, but it might've been due to a package collision. I'll close this for now, if it still keeps happening, we can reopen this.

**Closed by Frooxius** 2024-05-07 08:42 UTC
Labels: bug, triaged, needs more information
