### ISSUE TITLE
PBS_ColorMask is not applying EmissiveMap to EmissiveColor channels

### ISSUE THREAD

**Issue by towneh** [Yellow-Dog-Man/Resonite-Issues#158] opened 2023-10-14 12:10 UTC
### Describe the bug?

PBS_ColorMask is not applying EmissiveMap to EmissiveColor channels.

The EmissiveColor0 through 3 settings apply the desired colour value to the mesh and ignores the greyscale EmissiveMap when applied to the correct shader slot.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/25694892/a3990c71-50df-4076-a096-c79f94e91e7a)

### To Reproduce

Starting of with a ColorMask texture applied to the mesh, so far so good.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/25694892/55f41cfc-b368-4787-a703-b86b6b5f0a58)

I have applied the following texture in to the EmissiveMap:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/25694892/d8071bcd-b70c-4487-b0a7-c7ef7967aecf)

When starting to configure the emissivecolor value for each of the channels, I notice that the entire channel has the emission applied to it, regardless if a texture is applied to the EmissiveMap slot or not:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/25694892/1ac82bae-7d48-4694-9879-75b568fa69e1)

### Expected behavior

Expected behaviour for EmissiveMap is that it should "Mask" off the entire mesh in the same UV channel as the AlbedoTexture, for any emission applied, similar to how a popular Unity shader does this with RGBA masking:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/25694892/64c607ce-e4c7-4c8f-939e-7a61103001a3)

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Valve Index

**Comment by kulzae** [comment] 2023-10-16 15:51
Adding here that currently the emission map slot acts the same as the abledo although with emission and functions off the RGBA channels. im not sure if thats intended behavior but thats how it currently works
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40366296/19b34b7c-7de0-4ea4-a75a-3d3ce2fbace8)

**Comment by kulzae** [comment] 2023-10-16 21:30
resrec:///U-Kulza/R-CC846284D49298BDB1F928B06F927146764A0AD1C8E53959BDA33B289E9EE69D can be found in this folder as the item with the issue number
[RENEGADE - 2023.10.13.743 - 2023-10-16 17_07_49.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12922174/RENEGADE.-.2023.10.13.743.-.2023-10-16.17_07_49.log)

**Comment by Geenz** [comment] 2024-04-01 20:17
Managed to confirm this one.  I'll get it in the next shader update.

**Comment by Geenz** [comment] 2024-04-04 10:55
I've looked at the code for this - and it appears we're not properly setting a keyword.  Fix has been queued for shader update 1.

**Closed** 2024-04-04 10:57 UTC
Labels: bug
