### ISSUE TITLE
Order offset for Components

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#666] opened 2023-11-13 23:43 UTC
### Is your feature request related to a problem? Please describe.

With slots you have the capability of changing their order relative to their fellow children. This is incredibly useful for *many* reasons, the most common of which is just simple organization.  But with components we don't have the ability to set any sort of order offset and are at the mercy of what feels like a random order. This can make figuring out what the components on a slot are doing much harder because of a lack of easy to understand flow.

### Describe the solution you'd like

Add a Component Order Offset field to components, eg

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38511571/1c3de417-2892-4011-b92a-bf80e417b5da)

### Describe alternatives you've considered

The only other alternative I can think of is putting each component on its own slot, which is not efficient in terms of processing, memory, or just reading through it.

**Comment by mpmxyz** [comment] 2023-11-13 23:58
That looks like a duplicate of #421.

**Comment by TisFoolish** [comment] 2023-11-13 23:59
Damn, you are right. Not sure how I didn't find it before hand

**Closed** 2023-11-13 23:59 UTC
Labels: enhancement
