### ISSUE TITLE
Add a "Break" call input to async protoflux nodes

### ISSUE THREAD

**Issue by Raidriar796** [Yellow-Dog-Man/Resonite-Issues#1786] opened 2024-04-20 05:17 UTC
### Is your feature request related to a problem? Please describe.

When working with protoflux, there are times when you may want to interrupt a loop prematurely for certain functions or for debugging. I've been able to stop loops by removing references or disconnecting wires but I feel that shouldn't be needed to force a loop to stop.

### Describe the solution you'd like

I would like an additional call input in protoflux nodes like "Async While" and "Async For" that will end the loop when called.

### Describe alternatives you've considered

Potentially a way to pause a loop, but that may introduce needless complexity compared to a break.

### Requesters

@Raidriar796 / raidriar796, gmanamby, winterblizzards

**Comment by marsmaantje** [comment] 2024-04-20 14:02
Duplicate of #1054

**Closed** 2024-04-20 19:39 UTC
Labels: enhancement
