### ISSUE TITLE
Allow F16-F24 as valid Key Input values in ProtoFlux

### ISSUE THREAD

**Issue by polyjitter** [Yellow-Dog-Man/Resonite-Issues#2259] opened 2024-06-08 08:30 UTC
### Is your feature request related to a problem? Please describe.

Within ProtoFlux, the recognized F16-F24 keys do not appear to be allowed as key inputs in ProtoFlux. Although these keys are not typically found on modern keyboards, they are still accepted in most valid keymaps. This makes them ideal for reassignment to macropads or shortcut pads.

Currently, I am working on an in-game tool for editing and creating custom shortcut menus for use with arm-mounted macro pads (see attached picture). Essentially, I want to create a manager to allow users to create custom radial menus and toggles for their armpads, with in-game visual menu feedback.

Allowing usage of F16-F24 will give me a clear path to recommend best practices to users of this tool, in terms of how to assign their keypads, as these buttons should not ever conflict with other running applications, and should be accepted in a standardized way by most input environments.

### Describe the solution you'd like

I would like F16-F24 to be added as accepted values for a Key Input within ProtoFlux. No further changes should be required :)

### Describe alternatives you've considered

Creating a custom OSC application would resolve issues with key conflicts, but would require players to download external tools, and would make for more configuration overhead than would be ideal. Just asking users to use already Resonite-accepted key combos or buttons would be easier to configure, but would run the risk of interfering with other applications' key bindings unpredictably.

### Additional Context

Example of an "armpad" (arm-mounted macro pad) this would be useful for:
![IMG20240607163303](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/18127936/f01e8314-4792-4d3a-8a40-e43a7eac129f)

### Requesters

Discord - ashewebsite, Resonite - kaestral

**Comment by Electronus** [comment] 2024-06-08 22:03
Duplicate of #1515

**Comment by polyjitter** [comment] 2024-06-08 22:06
Indeed; commenting over there and closing this issue!

**Closed** 2024-06-08 22:06 UTC
Labels: enhancement
