### ISSUE TITLE
Loading indicator doesn't reveal error message

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#3000] opened 2024-09-23 15:32 UTC
### Describe the Underlying Issue

When you fail to join a world (for example because it's full), the loading indicator just disappears without revealing the reason why the join failed. This used to work, not sure when it broke.

### To Reproduce

Attempt to join a world that is full / doesn't allow you to join

### Expected Behavior

The loading indicator should stay around to inform the user why the join failed.

**Comment by TisFoolish** [comment] 2024-09-23 17:21
I noticed it from before the most recent work, so i suspect it's a regression caused by the changes Prime did before that

**Comment by JackTheFoxOtter** [comment] 2024-09-23 18:16
Looks like no exception is being thrown, so I wasn't aware this was an engineering issue, I thought it was an issue in the indicator itself. Here's a log of me attempting (and failing) to join a session. The loading indicator just disappeared without displaying an error text. Resonite version is `Beta 2024.9.16.1105`

[J4-C - 2024.9.16.1105 - 2024-09-23 20_11_51.log](https://github.com/user-attachments/files/17102347/J4-C.-.2024.9.16.1105.-.2024-09-23.20_11_51.log)

**Comment by shiftyscales** [comment] 2024-09-23 18:56
Does this issue also occur on custom indicators as well, @JackTheFoxOtter @TisFoolish? There has been recent work done both on content and engineering sides- @RyuviTheViali had updated / optimized the indicator on the third of this month- and Prime has recently been doing some work on it as well.

If you are aware **when** it first broke, it'd be a bit more clear where the issues lies- same with if the issue occurs on custom user-made indicators made / saved prior to that date.

**Comment by TisFoolish** [comment] 2024-09-23 19:01
I wanna say it was version 2024.9.4.357 when I first noticed

**Comment by JackTheFoxOtter** [comment] 2024-09-23 20:02
> Does this issue also occur on custom indicators as well

I don't know, I only use official ones. I never made my own so I can't test that quickly.

> If you are aware when it first broke, it'd be a bit more clear where the issues lies

I don't know, I noticed today, but I *think* I also had this happen before EF. That would have been on the same build though.

**Comment by NepuShiro** [comment] 2024-09-23 20:37
It's an issue with the new Reworked Loading Indicator from @RyuviTheViali
Using version 'Beta 2024.8.5.1341' which is before the Rework and the Patches Prime has done recently, I cannot test with any older Loading indicators since I do not have any on hand, and I cannot go back to the old one since the new one is spawned from the cloud.

https://github.com/user-attachments/assets/2b2edfbd-0193-443e-b404-195fe774ba42

This Test is done with Default settings on a just downloaded Resonite, and Attempting to join a newer headless, which should give the Session not compatible error. Ver. Beta 2024.8.5.1341

[NEPNEPSHIRO - 2024.8.5.1341 - 2024-09-23 15_29_01.log](https://github.com/user-attachments/files/17103973/NEPNEPSHIRO.-.2024.8.5.1341.-.2024-09-23.15_29_01.log)

**Comment by shiftyscales** [comment] 2024-09-23 20:39
Thanks for looking into it further, @NepuShiro. Unassigning Prime.

**Comment by Gawdl3y** [comment] 2024-09-28 18:51
It seems that failure messages from custom join verifiers also don't make it through to the indicator. The indicator just hangs on "Authenticating" for a few seconds and then disappears.

**Comment by Frooxius** [comment] 2024-09-28 18:55
@RyuviTheViali Would you be able to prioritize this as soon as possible please?

It's making some issues with the session networking handling harder to diagnose.

**Comment by RyuviTheViali** [comment] 2024-09-28 22:12
Getting to this ASAP.

**Comment by RyuviTheViali** [comment] 2024-09-28 22:45
@Frooxius I've updated the loading indicator to properly show error responses now.

Could I ask for confirmation it is working before I close this issue?

**Comment by Zyro1331** [comment] 2024-09-29 05:49
@RyuviTheViali I have tested both an older version of the WorldLoadingIndicator and the latest one in the Resonite Essentials. 
I set-up a Custom Join Verifier in a basic session that basically denied any join requests. Upon joining the session, the Default loading indicator proceeded to just say "Authenticating" before vanishing without reason. Same thing occurs with the latest one in the Resonite Essentials. 
I saved a much older version of the WorldLoadingIndicator from February 2024, and set it as my loading indicator, to which it properly showed an error message when trying to join the test session. I also did this testing in the prerelease build to just make sure that it wasn't inconsistent between stable, but still saw the same results.

**Comment by RyuviTheViali** [comment] 2024-09-30 04:38
I've updated the indicator again, it should properly show error state now! Turns out `HasCompleted` only triggers on a successful completion, and not a failed completion. Could I get confirmation the indicator works as intended?

**Comment by NepuShiro** [comment] 2024-09-30 05:15
> I've updated the indicator again, it should properly show error state now! Turns out `HasCompleted` only triggers on a successful completion, and not a failed completion. Could I get confirmation the indicator works as intended?

It seems to be working great, for me at least
![image](https://github.com/user-attachments/assets/c8030174-2a27-496c-8c2f-f82b2a03a8de)

**Comment by ProbablePrime** [comment] 2024-10-04 02:34
Thanks for the confirmation!

**Closed by ProbablePrime** 2024-10-04 02:34 UTC
Labels: content, triaged
