### ISSUE TITLE
Assimp does not preserve blend shape order for fbx files

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#1106] opened 2024-01-09 17:43 UTC
### Describe the bug?

As in title, this causes significant issues as the semingly non-deterministic order makes updating assets with driven/driving shapes significantly harder

### To Reproduce

import asset with blend shapes

### Expected behavior

blend shape order matches exporting application, ex blender

### Resonite Version Number

Beta 2024.1.3.1265

### What Platforms does this occur on?

Windows, Linux

### Log Files

n/a

### Additional Context

somewhat related to #813 and #1004

### Reporters

zangooseoo
@GunnarO0
@GearBell

**Comment by gentlecolts** [comment] 2024-01-09 18:39
Only tested so far with fbx, Trivial to reproduce:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/5e776bab-8f79-47d9-b003-e3eeaee043c0)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/da266458-bcc8-4a9b-b956-bda5a2201a04)
[resonite blendshape issue.fbx.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13877737/resonite.blendshape.issue.fbx.zip)

**Comment by Kirv-goldblade** [comment] 2024-01-09 18:46
tested this myself. fbx seems to be the only format to retain blend shapes (tested with dae and obj aswell neither had bledshapes after uploading), and the scrambling of blendshapes is completely random. uploaded the same fbx 3 times and every time the order of the shapes was different
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/151879416/9ce5f183-06ad-4154-b496-323d82e513e0)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/151879416/8796b41a-a2be-49c5-8030-34f247426f02)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/151879416/2b5525b8-62ec-49c1-b885-cdab6cef7075)

**Comment by FlameSoulis** [comment] 2024-01-09 20:09
I've noticed this as well, when exporting from Blender. It seems to add some kind of 'class' system, if that makes any sense. This, in turn, ruins the order.

So, like VRC.AA. VRC is the class, AA is the blendshape. If a blendshape doesn't do this, it'll become XX.XX, with XX being the blendshape name. This occurred after the blendshape re-ordering feature.

Not sure if it's related, but sounds a bit like it.

**Comment by ModernBalloonie** [comment] 2024-01-10 02:56
If I use Gltf, it seems the blendshape order is correct, Meanwhile FBX is messed up.

**Comment by lxw404** [comment] 2024-06-27 22:52
I've just submitted a pull request that should hopefully fix this issue.

**Comment by Frooxius** [comment] 2024-07-04 23:00
I've merged the fix in 2024.7.4.1347, thank you!

**Closed by Frooxius** 2024-07-04 23:00 UTC
Labels: bug, third party

**Comment by 989onan** [comment] 2025-05-10 19:43
This issue has resurfaced again. I have imported my friend's FBX and a few others and I have been telling people not to use them before I found this issue. I can provide logs but it will be a while since I'm at FWA. The reproduction steps are the same

**Comment by 989onan** [comment] 2025-05-12 01:15
Ran into the issue just now again, this needs reopening
