### ISSUE TITLE
Bulk selecting still selects flux nodes that were disconnected from each other

### ISSUE THREAD

**Issue by LeCloutPanda** [Yellow-Dog-Man/Resonite-Issues#1306] opened 2024-02-05 14:59 UTC
### Describe the bug?

When disconnecting chunks of nodes from each other and then bulk selecting to pack/move nodes it selects all the nodes that were connected to each other.

### To Reproduce

Spawn an item out that has nodes connected together and disconnect them from each other and bulk select one chunk of nodes.

### Expected behavior

When bulk selecting nodes that were disconnect from each other to only select the properly connected nodes.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/53411604/8524013b-c879-4835-acc8-d2405f37dda3)

### Resonite Version Number

2024.2.2.1015

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[GEOFF - 2024.2.2.1015 - 2024-02-06 01_02_29.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14167330/GEOFF.-.2024.2.2.1015.-.2024-02-06.01_02_29.log)

### Reporters

LeCloutPanda

**Comment by Frooxius** [comment] 2024-02-05 15:01
Duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/907

**Closed by Frooxius** 2024-02-05 15:01 UTC
Labels: bug
