### ISSUE TITLE
Most Protoflux nodes continue updating despite being packed under a deactivated hierarchy

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#814] opened 2023-11-28 04:57 UTC
### Describe the bug?

Even if packed protoflux is under a slot that's disabled events, driven behavior and similar still happen, with some exceptions and do not respect the slot's disabled state.

However, this behavior is inconsistent, a Fire While True won't do anymore events if under a disabled slot or disabled itself for example.

### To Reproduce

1. Copy and paste resrec:///U-ohzee/R-54fcf946-f1a3-4406-9f60-8054af856719 into the world
2. Notice how the Protoflux is running
3. Hit the top button to turn off the packed slot holding the Protoflux
4. Notice how most nodes still do events and continue driven behavior via the text

I hope the resrec works, here is a public folder incase it doesn't: 
resrec:///U-ohzee/R-FEF7D9695F1791283C0F430867CFE2931C5D90BAC7388EBE75C19A28F2A2DB2F

### Expected behavior

The expected behavior is that all Protoflux underneath a disabled slot should stop doing events and updating values.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/7cd1a6d5-b0ad-4b85-873a-d2ea444fdf80

### Resonite Version Number

2023.11.25.49

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-V75BHJO - 2023.11.25.49 - 2023-11-27 23_13_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13483564/DESKTOP-V75BHJO.-.2023.11.25.49.-.2023-11-27.23_13_34.log)

### Additional Context

This was made from request from #804 
I do know it was requested to gain a deeper understanding of which nodes are affected or not, however I do not have the time to fully go through with this currently. If others could provide more information with this, I would be grateful.

The behavior of Protoflux running under a disabled slot makes sense in a way, given that it is disconnected from the datamodel mostly but I don't know the correct solution would be that would both allow users to optimize their content better while also not breaking said content at the same time. 

### Reporters

Ohzee
zyzylian
ShadowPanther
Shrike
Foohy

**Comment by Nytra** [comment] 2023-11-28 05:02
I think this issue in which ProtoFlux continues running after the nodes have been destroyed is related https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/689

**Comment by bontebok** [comment] 2023-11-28 05:13
I wrote a Protoflux profiler Mod that simply computes the execution time spent in the RunUpdateLoop() and on all of the Protoflux methods, including RebuildAndCleanup(), RunNodeEvents, RunNodeUpdates, RunContinuousChanges, and RunDiscreteChanges to troubleshoot performance issues in Creator Jam worlds, both ported from another platform and ones build within Resonite.

I monitored the average millisecond execution times of all of the methods. In disabling the entire parent slot for the world (The Janitor Bot slot which contains all of the world), I could observe an increase of frames due to the World Update Loop reducing in execution time, however the millisecond execution times for all Protoflux nodes were effectively unchanged.

In a particular world of interest, CJ 192 I performed a live profile on the world. Here are the average results from before disabling the slot, to after disabling the slot. I know it's a lot of data but bear with me.

```{"source":"ProtoFluxController.RebuildAndCleanup", time:0.00570000009611249}
{"source":"ProtoFluxController.RunNodeEvents", time:0.00150000001303852}
{"source":"ProtoFluxController.RunNodeUpdates", time:0.0012999998871237}
{"source":"ProtoFluxController.RunContinuousChanges", time:0.261100000003353}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.00109999999403954}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.000900000100955367}
{"source":"ProtoFluxController.RebuildAndCleanup", time:0.00260000000707805}
{"source":"ProtoFluxController.RunNodeEvents", time:0.000899999868124723}
{"source":"ProtoFluxController.RunContinuousChanges", time:0.000699999975040555}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.000699999975040555}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.00300000002607703}
{"source":"ProtoFluxController.RebuildAndCleanup", time:0.00630000000819564}
{"source":"ProtoFluxController.RunNodeEvents", time:0.00230000005103648}
{"source":"ProtoFluxController.RunNodeUpdates", time:2.12299999990501}
{"source":"ProtoFluxController.RunContinuousChanges", time:6.38509999983944}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.00140000018291175}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.00280000013299286}
{"source":"WorldManager.RunUpdateLoop", time:17.4575999998488}```

The values represent the milliseconds each method execution took. You can see that most methods run pretty fast, but note the milisecond time for the RunContinuousChanges (nodes like T for example, which run on each update) took about 6.3ms to complete with a total world update time of 17.5ms on average.

Now, here's the result of disabling the entire slot hierarchy which contains all world elements including Protoflux -

```{"source":"ProtoFluxController.RebuildAndCleanup", time:0.00650000013411045}
{"source":"ProtoFluxController.RunNodeEvents", time:0.00169999990612268}
{"source":"ProtoFluxController.RunNodeUpdates", time:0.00139999995008111}
{"source":"ProtoFluxController.RunContinuousChanges", time:0.267500000074506}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.00120000005699694}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.000899999868124723}
{"source":"ProtoFluxController.RebuildAndCleanup", time:0.00199999986216426}
{"source":"ProtoFluxController.RunNodeEvents", time:0.00100000016391277}
{"source":"ProtoFluxController.RunContinuousChanges", time:0.000899999868124723}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.000999999931082129}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.00159999984316528}
{"source":"ProtoFluxController.RebuildAndCleanup", time:0.00440000020898879}
{"source":"ProtoFluxController.RunNodeEvents", time:0.00120000005699694}
{"source":"ProtoFluxController.RunNodeUpdates", time:0.0424999999813735}
{"source":"ProtoFluxController.RunContinuousChanges", time:6.62340000015683}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.0011999998241663}
{"source":"ProtoFluxController.RunDiscreteChanges", time:0.000999999931082129}
{"source":"WorldManager.RunUpdateLoop", time:8.91950000007637}```

Clearly I got a lot of frames back, but when you look into the data more closely, you see that effectively none of the Protoflux times were changes, my frame increase was purely from other non-Protoflux components acting correctly when disabled reducing my total update time to 8.92ms, but Protoflux execution took the same amount of time to execute as it did when it was enabled.

My apologies for not posting this as an issue - I incorrectly assumed that the team must have known about this issue since I've heard it mentioned by many other users including those that were early access testers. I hope the information above is helpful.

**Comment by bontebok** [comment] 2023-11-28 05:42
Scanning Discord, the earliest report I could find of the issue was Shrike in the #patrons channel. Feel free to list them if you want to include them for credit. https://discord.com/channels/1040316820650991766/1154514008481742980/1158698576843645018

**Comment by Frooxius** [comment] 2023-11-28 06:02
Thanks for the info!

Would you be able to get a list of the nodes that exhibit this behavior so we can sort through them?

**Comment by Zyzyl** [comment] 2023-11-28 06:02
Generating an exhaustive list of nodes which do and don't respect their hierarchy being deactivated will be a large task. However, I've tested a selection of nodes and found the following results. My testing world is: resrec:///U-Zyzyl/R-6d43a602-b000-4609-a55a-31a6419eaa32

The following nodes stop updating (firing impulses) when their parent hierarchy is deactivated:
- Update
- LocalUpdate
- FireWhileTrue
- LocalFireWhileTrue
- SecondsTimer
- UpdatesTimer

All of the following nodes _do not_ stop updating (either they continue firing impulses OR values driven from them continue to change) when their parent hierarchy is deactivated:
- NearestUserHand
- NearestUserHead
- GetComponentEnabled
- FieldHood (i.e. the field driven by the node continues changing)
- FireOnTrue
- FireOnLocalTrue
- FireOnValueChange
- FireOnLocalValueChange
- ButtonEvents
- IsContextMenuOpen
- GrabbableGrabber
- GrabbablePriority
- IsGrabbableGrabbed
- OnGrabbableGrabbed
- DeltaTime
- ElapsedTime (driven value continues changing, didn't test impulses)
- SmoothDeltaTime
- Stopwatch (driven value continues changing, didn't test impulses)
- WorldTimeFloat
- UTCNow


I hope this is a sufficiently large list to demonstrate a widespread problem. I'll be unable to update this list any further this week. If anyone else would like to use my world (or their own!) to continue testing that would be great.

**Comment by Frooxius** [comment] 2023-11-28 06:52
Sweet thank you! I'll sort through these as soon as I can. If you find more, you can add them to the list.

Some of these are kinda expected to keep updating, I'll note that later when I sort through them.

Just generally - anything that's a property, say UTCNow would keep "updating" - it doesn't actually update at all, it just says that its value changes all the time, so the updates come from whatever consumes the value (e.g. a drive or a display).

Similarly anything what gets events from external source (e.g. ButtonEvents) will also update even when disabled, because the update comes from "outside" of the node, it just proxies it through and the node is technically "passive" in a way.

**Comment by Frooxius** [comment] 2023-11-28 08:26
Yes, there would make sense to freeze. I believe they should and I'm not sure why they don't. I've either forgotten or the mechanism isn't working as it's supposed to.

**Comment by Frooxius** [comment] 2023-12-27 21:21
I'm sorting through the nodes now. I've handled the drive nodes. 

There nodes are expected to "keep" updating - they are not actual source of updates, it's only things that are listening to them (like a drive). So when the drive gets disabled, that stops the updates implicitly.

Essentially you can think of those nodes as if they normally do nothing, except when they're asked "What's your value?". They say that their value changes continuously, so if something needs to know when value has changed, it will keep asking them "What's your value?" and that's why you see the continuous updates.

However that's not coming from these nodes themselves, but rather from whatever is asking for the value (such as the drive).

- NearestUserHand
- NearestUserHead
- GetComponentEnabled
- IsContextMenuOpen
- GrabbableGrabber
- GrabbablePriority
- IsGrabbableGrabbed
- DeltaTime
- ElapsedTime
- SmoothDeltaTime
- Stopwatch
- WorldTimeFloat
- UTCNow

These other nodes are expected to update, because the updates come from external source - they're events and these nodes simply just proxy those through:
- ButtonEvents
- OnGrabbableGrabbed

These ones I'll be looking into:
- [ ] FieldHook
- [ ] FireOnTrue
- [ ] FireOnLocalTrue
- [ ] FireOnValueChange
- [ ] FireOnLocalValueChange

**Comment by Frooxius** [comment] 2023-12-28 22:21
I've got most of these handled, but there's one issue here - the Local versions technically existing completely independently of FrooxEngine, which means they are unaware of the hierarchy and enabled state, which makes it more difficult to have them respect the status.

I'll have to figure out a good way to approach this, though one of that might be just moving them into FrooxEngine dependency.

**Comment by Frooxius** [comment] 2023-12-28 23:44
Ok, I got all the nodes handled! Here's a video testing this:
https://youtu.be/X2hl3PJkwUQ

Since this is changing behavior, I've pushed a build with these changes into `prerelease` branch on Steam.

Would you be able to run through a bunch of content and give it a try, see if/what the breakage is like and such?

**Comment by ohzee00** [comment] 2023-12-29 00:21
I'll try to do as much testing as I can! However just to say, I am out of state on a computer that I'm not too familiar with, I would really appreciate any help from other users to test this build.

Also just to say, I really appreciate you looking into this issue and how much work ya put into it, I hope this can help with performance in some ways and other behavior with Protoflux.

**Comment by Frooxius** [comment] 2023-12-29 03:52
Ah that's fine. I'm busy with holiday and IRL stuff quite a bit, so I just wanted to get the test build out there for now.

**Comment by ohzee00** [comment] 2023-12-29 07:14
I am noticing a LOT of "Change tracking data is not built" exceptions so far, currently looking into a weird world crash that may or may not be related, it is proving very inconsistent.  

This log is only loading into my cloud home that is not the Resonite cloud home, which includes loading my avatar and exiting the game. This does not have a world crash in it, I wanna replicate that better before fully reporting it.

[FOOHY-HOST-PC - 2023.12.28.1406 - 2023-12-28 22_20_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13791385/FOOHY-HOST-PC.-.2023.12.28.1406.-.2023-12-28.22_20_34.log)

So far I haven't noticed anything broken besides the world crash I can't fully replicate, though performance gains are really nice from worlds that use culling systems. Even all the examples from my original post work as I expect them to when under a disabled slot, or disabled themselves.

**Comment by Frooxius** [comment] 2023-12-29 21:58
Thanks! I've fixed up a few things and the exceptions should be gone. There's a new build 2023.12.29.1306 in the pre-release branch. 

If anyone can give it a try, it would help before I push it out!

**Comment by Nytra** [comment] 2023-12-29 23:31
I have a ProtoFlux setup that works differently on the pre-release vs. the current headless branch.

On the pre-release build, the display node on the right will not continuously update when adding and removing the slot called 'a', however on the headless build it will continuously update. The packed state of the node does not seem to matter at all.

![2023-12-29 23 22 52](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/7d455a8b-72db-4ac4-a6b5-448dbd95c644)

**Comment by Frooxius** [comment] 2023-12-29 23:35
@Nytra Can you provide more info on how to replicate this and provide a sample setup?

You mention the behavior is different between client and headless?

**Comment by Nytra** [comment] 2023-12-29 23:44
The behavior is different between Beta 2023.12.21.1127 from the headless branch, and Beta 2023.12.29.1306 from the pre-release branch.

I will try to prepare a video and a public folder item.

**Comment by Nytra** [comment] 2023-12-29 23:59
Well in trying to do that I encountered a crashing bug. If you spawn the item in this folder and then grab and delete the display node it will crash the world: resrec:///U-Nytra/R-E8F184680C1259F767B6A4B4C82701CCB030AE3FC38BE0F384B537D93E28D8AC

Log file: 
[DESKTOP-H976HO2 - 2023.12.29.1306 - 2023-12-29 23_57_24.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13796562/DESKTOP-H976HO2.-.2023.12.29.1306.-.2023-12-29.23_57_24.log)

**Comment by Nytra** [comment] 2023-12-30 00:18
But yes this video is essentially the behavior that I'm seeing (sorry if it is blurry) https://www.youtube.com/watch?v=o3HOWfIZnqA

However it seems to only happen for freshly created display nodes, rather than ones spawned from inventory. So if you spawn the item from this folder, if you create a new display node you will see the same behavior as in the video.

The folder is here (same as in previous comment): resrec:///U-Nytra/R-E8F184680C1259F767B6A4B4C82701CCB030AE3FC38BE0F384B537D93E28D8AC

**Comment by ohzee00** [comment] 2023-12-30 00:53
I just noticed changed behavior myself, I did not see this in the previous prerelease build but the switches for the Online status _and_ the voice mode switches don't visually work. They however do correctly change the mode, just the visuals are broken.
I did confirm this does _not_ happen in the main build.

The log below is me logging in and, hitting the buttons and logging off.

[FOOHY-HOST-PC - 2023.12.29.1306 - 2023-12-29 16_43_17.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13796686/FOOHY-HOST-PC.-.2023.12.29.1306.-.2023-12-29.16_43_17.log)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/d375be4e-d8df-4ddd-8e51-c8de3dbb842f)

**Comment by Zyzyl** [comment] 2023-12-30 15:25
Thanks for working on this Froox! Still some issues to fix up before pushing to release though. The following was all tested on 2023.12.29.1306:

I also see the issue with Dash mic mode and online status buttons. Interestingly, the buttons start to behave as expected after you log in or out of a Resonite account. i.e. if Resonite is started as an anonymous user, the dash buttons show the issue, but the issue disappears for that play session if you then log into a Resonite account. The converse (starting logged in shows incorrect behaviour and then logging out 'fixes' it) is also true.

If I load the testing world I mentioned above (`resrec:///U-Zyzyl/R-6d43a602-b000-4609-a55a-31a6419eaa32`), none of the drives (FieldHook included) appear to be respecting the slot hierarchy active/inactive status anymore. Also some of the impulse-based nodes have also reverted to ignoring that too, specifically:
- FireOnTrue
- FireOnLocalTrue
- FireOnValueChange
- FireOnLocalValueChange
This is a regression from the previous prerelease builds.

There also appears to be some difference in behaviour between nodes which are freshly spawned vs. ones loaded from a saved record. In my testing world, all of the drives keep driving whether the slot hierarchy is active or inactive. However, newly created Display or drive nodes don't update continuously (even when the hierarchy is active). See this video for a demonstration https://youtu.be/P4At_eFKtX8

**Comment by Frooxius** [comment] 2024-01-03 00:15
Thanks for testing! There was a bug causing the change tracking data not to rebuild when they should.

I've pushed another pre-release build Beta 2024.1.3.2

Would you be able to test that one please?

**Comment by ohzee00** [comment] 2024-01-03 00:48
> Thanks for testing! There was a bug causing the change tracking data not to rebuild when they should.
> 
> I've pushed another pre-release build Beta 2024.1.3.2
> 
> Would you be able to test that one please?

The facets are working again as they do in the base build!


> But yes this video is essentially the behavior that I'm seeing (sorry if it is blurry) https://www.youtube.com/watch?v=o3HOWfIZnqA
> 
> However it seems to only happen for freshly created display nodes, rather than ones spawned from inventory. So if you spawn the item from this folder, if you create a new display node you will see the same behavior as in the video.
> 
> The folder is here (same as in previous comment): resrec:///U-Nytra/R-E8F184680C1259F767B6A4B4C82701CCB030AE3FC38BE0F384B537D93E28D8AC

This seems to be fixed too, changing the slot under the parent updates correctly in the current prerelease (2024.1.3.2) build.

The original example in the first post also functions as I believe should, I can't do multi user testing currently but I haven't had any strange issues in my logs, crashes or observed strange behavior with protoflux yet.

**Comment by Nytra** [comment] 2024-01-03 01:07
I have tested the problems I reported and they seem to have been fixed in this new build. Thanks!

**Comment by Frooxius** [comment] 2024-01-03 06:41
Thanks for testing, this is now out in 2024.1.3.393!

**Closed by Frooxius** 2024-01-03 06:41 UTC
Labels: bug, protoflux
