### ISSUE TITLE
A save button that always displays "You must be logged in to save items."

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#2159] opened 2024-05-30 01:50 UTC
### Describe the bug?

When you grab an item and open the context menu, the save button is always labeled "You must be logged in to save items."
This message remains unchanged regardless of whether or not the item being held can be saved.

### To Reproduce

1. Start Resonite and wait until the home world appears.
2. Hold the item and open the context menu.
You are successfully logged in, but the label on the save button says "You must be logged in to save items.
3. Open your inventory and navigate to the path where you can save the item.
4. Open the context menu with the item.
The save button label will show the same message.

### Expected behavior

The message on the label should change depending on the situation.

### Screenshots
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/c98d91c5-55c5-4180-ba75-bcba12585f45)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/5ddd8a8b-31ad-4c04-8cc1-32bd2e980fc3)

### Resonite Version Number

2024.5.30.68

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MENTAIKO - 2024.5.30.68 - 2024-05-30 10_39_45.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15492548/MENTAIKO.-.2024.5.30.68.-.2024-05-30.10_39_45.log)

### Additional Context

Video reproducing this
https://youtu.be/dE_xlzlYI38

### Reporters

orange3134

**Comment by ProbablePrime** [comment] 2024-05-30 02:01
A duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2160

But thank you for being so prompt!

**Closed by ProbablePrime** 2024-05-30 02:01 UTC
Labels: bug
