### ISSUE TITLE
Add 'Worlds You're in' Facet by Default

### ISSUE THREAD

**Issue by rabbuttz** [Yellow-Dog-Man/Resonite-Issues#2161] opened 2024-05-30 02:28 UTC
### Is your feature request related to a problem? Please describe.

Resonite has a convenient feature that allows users to exist in multiple worlds simultaneously. However, this feature can be quite challenging for beginners to handle. Viewing the list of sessions you are currently in from the Worlds tab and leaving a world is quite difficult for beginners.

### Describe the solution you'd like

I believe ProbablePrime's "Worlds You're In" Facet is incredibly useful. While this feature is convenient for advanced users, I think it's especially beneficial for beginners. However, it can take a while for beginners to discover this Facet, and attaching it to their home screen can be challenging. Therefore, I believe this Facet should be incorporated into the home screen by default.
item: resrec:///U-ProbablePrime/R-cb3d5f03-ffa6-4e09-adf2-e07757b9b3e8
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49971163/e830cb92-c105-4836-8bff-cf73da8903c1)

### Describe alternatives you've considered

Continue to disconnect sessions from the Worlds tab as before.

### Additional Context

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49971163/e05f0030-2188-4114-ab9a-17cd77d7a51a)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49971163/938b717d-0394-4ddf-8807-390b3710d537)
I host beginner-friendly events in Resonite every week, and when moving sessions, I often recommend disconnecting from the previous session. However, explaining this process is always challenging. I instruct users to click the X mark in the upper right corner, as shown in the image, but another X mark is displayed when the focus screen is open, causing confusion among beginners.

### Requesters

Discord: rabbuttz

**Comment by Nytra** [comment] 2024-05-30 02:32
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/396

**Comment by rabbuttz** [comment] 2024-05-30 02:33
@Nytra Oh thanks!

**Comment by shiftyscales** [comment] 2024-05-30 20:16
Closing as a duplicate, thanks for the suggestion.

**Closed by shiftyscales** 2024-05-30 20:16 UTC
Labels: duplicate, enhancement
