### ISSUE TITLE
Add ability to show the slot that a component is on

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2067] opened 2024-05-22 01:39 UTC
### Is your feature request related to a problem? Please describe.

When viewing A component inspector I can't see what slot it's under without the original inspector

### Describe the solution you'd like

I would like there to be an arrow on the header of the component inspector when it's clicked it will pop out the inspector inspecting the slot that the component is on

### Describe alternatives you've considered

A Mod

### Requesters

@epicEaston197

**Comment by lxw404** [comment] 2024-05-22 06:01
Duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/608

**Comment by Zyro1331** [comment] 2024-05-22 09:53
It's entirely possible to figure out where a component is located by grabbing the header of the component and pressing the "Open Inspector" button in your context menu as you hold the component reference. Then the newly opened Inspector will show the slot the component is attached to.

**Comment by epicEaston197** [comment] 2024-05-22 12:28
> It's entirely possible to figure out where a component is located by grabbing the header of the component and pressing the "Open Inspector" button in your context menu as you hold the component reference. Then the newly opened Inspector will show the slot the component is attached to.

Bro...

**Comment by shiftyscales** [comment] 2024-05-23 18:52
Thanks, @Zyro1331. I was not aware of that functionality. I will likely use it often. I've left a comment quoting your tip on #608, but for now, I'll otherwise close out this issue since it is functionally a duplicate- making this functionality easier to discover/more visible.

**Closed by shiftyscales** 2024-05-23 18:52 UTC
Labels: enhancement
