### ISSUE TITLE
NaN is equal to NaN in the Equals protolux node

### ISSUE THREAD

**Issue by VirgilCore** [Yellow-Dog-Man/Resonite-Issues#1244] opened 2024-01-25 01:15 UTC
### Describe the bug?

see title. NaN should not be equal to itself by definition

### To Reproduce

compare a float of value NaN to another float of value NaN with the equals node
see it outputs true

### Expected behavior

NaN should not equal NaN

### Resonite Version Number

2024.1.24.840

### What Platforms does this occur on?

Windows, Linux

### Log Files

N/A
[NA.txt](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14045537/NA.txt)

**Comment by Frooxius** [comment] 2024-01-25 01:19
Duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1046

**Closed by Frooxius** 2024-01-25 01:19 UTC
Labels: bug
