### ISSUE TITLE
US LNL Relay Down or unstable

### ISSUE THREAD

**Issue by skywindkitsune** [Yellow-Dog-Man/Resonite-Issues#2798] opened 2024-08-22 19:29 UTC
### Describe the bug?

It has been several weeks and this has likely gone unreported, the US Relay is completely unreliable and nearly unusable, we get very poor voice quality, very poor connection to whoever happens to be unlucky enough to have to use it.

### To Reproduce

Just set the US Relay as your main LNL relay and try connecting to any session with "Always use LNL Relay 
Turned on"

### Expected behavior

Decent voice quality, few to no dropped packets, no disconnections from the session, reliable connection to headless servers and sessions.

### Resonite Version Number

 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Quest 3

### Log Files

No Logs

### Additional Context

Just ask anyone on Resonite, the US LNL Relay is a joke and practically useless.

### Reporters

Skywind Kitsune

**Comment by shiftyscales** [comment] 2024-08-22 20:46
This is a duplicate of #2767 - I'll check again for a status update again now that things have quieted down- internally things have been very busy of late.

As a reminder of our [reporting requirements](https://github.com/Yellow-Dog-Man/Resonite-Issues#reporting-requirements):

> - **Use objective, and respectful language** for anything submitted.
>   - Follow our [Code of Conduct](CODE_OF_CONDUCT.md)

Please keep your reports objective and focused on the facts. I understand the issue has likely been an annoyance to you, and others on Resonite, but bringing that emotion into our GitHub doesn't help anything.

**Closed by shiftyscales** 2024-08-22 20:46 UTC
Labels: bug
