### ISSUE TITLE
crash after headless crashes

### ISSUE THREAD

**Issue by Drafy07** [Yellow-Dog-Man/Resonite-Issues#2726] opened 2024-08-06 17:01 UTC
### Describe the bug?

when a headless or server crashes it send you back home , when this happen the game just straight freezes forcing you to shut it down.

### To Reproduce

join headless , wait for it to crash , expect crash uppon returning to your world.

### Expected behavior

no crash ? 

### Resonite Version Number

beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop/cv1

### Log Files

[error.log](https://github.com/user-attachments/files/16513456/error.log)

**Comment by shiftyscales** [comment] 2024-08-06 17:36
Thanks for the report, @Drafy07. I believe this is a duplicate of #2681. This issue doesn't seem to be specific to headless hosts- it seems the same occurs if any host crashes.

**Closed by shiftyscales** 2024-08-06 17:36 UTC
Labels: bug
