### ISSUE TITLE
Resonite takes forever (at least 13 minutes) to load, is never responsive

### ISSUE THREAD

**Issue by RobertBaruch** [Yellow-Dog-Man/Resonite-Issues#2383] opened 2024-06-22 23:55 UTC
### Describe the bug?

I haven't used Resonite in a month. Starting up Resonite, it's so far taken 6.5 minutes just to get to the initial dash. All throughout, the music is playing.

After 8 minutes, the FPS display on the dash moves momentarily, and then things freeze again. Resonite is barely taking 2% of the CPU, with occasional spikes to about 20%.

The logs have many "Engine has been unresponsive" messages, but also many "Error initializing SRanipal Lip Tracking: RUNTIME_NO_RESPONSE" messages.

After 13 minutes, I just killed Resonite.

### To Reproduce

I dunno, start Resonite?

### Expected behavior

It should really start up within 2 minutes.

### Resonite Version Number

2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Bigscreen Beyond

### Log Files

[DESKTOP-83DJ9R8 - 2024.6.11.74 - 2024-06-22 16_39_52.log](https://github.com/user-attachments/files/15942051/DESKTOP-83DJ9R8.-.2024.6.11.74.-.2024-06-22.16_39_52.log)

### Reporters

Xekri

**Comment by ohzee00** [comment] 2024-06-23 00:00
Ugh yeah I think I know this one, resonite is trying to ping sranipal and getting no response so its retrying constantly. I'm unsure what the solution is besides uninstalling sranipal for there is currently no way for Resonite to not ping the software manually.

**Comment by RobertBaruch** [comment] 2024-06-23 00:04
Yeah, related seems to be Issue #953.

**Comment by shiftyscales** [comment] 2024-06-23 19:10
Per comment from Frooxius on #102:

> I can have a look, but we might not be able to do super much on our end about this, because this might be issue with the SDK itself.
> 
> We poll the SRAnipal API on its own thread to avoid locking up the game, but it still locks up for some reason.
> 
> One solution I was thinking is spinning it up into a whole separate process. That way if it also goes down, it can be restarted easily without killing the main app.

Functionally- this is a duplicate of #953 and related issues #402 / #102.

As such I will be closing this out, @RobertBaruch.

**Closed by shiftyscales** 2024-06-23 19:10 UTC
Labels: bug
