### ISSUE TITLE
PhotonDust Compatibility - `BoxEmitter.DirectionMode` converter doesn't respect both `EmitFromShell` and `AlwaysForceDirection` being false

### ISSUE THREAD

**Issue by Martysh12** [Yellow-Dog-Man/Resonite-Issues#3278] opened 2024-12-05 21:35 UTC
### Describe the bug?

The `LegacyBoxEmitter` converter seems to ignore the `EmitFromShell` option - it thinks it's always on.

### To Reproduce

1. Create a Legacy Particle System using the "Create new..." option on the DevTool.
2. Remove the `LegacySphereEmitter` and replace it with a `LegacyBoxEmitter`:
   1. Set `RandomDirection` to `0`.
   2. Set `Direction` to `[0, -1, 0]`.
3. Save the item and spawn it from your inventory (with conversion on).

Testing item link: `resrec:///U-1UzdhEAL6IK/R-f9387b27-9d13-4765-9808-d4155a7787df`
Testing item package: [LegacyParticleSystem.resonitepackage.gz](https://github.com/user-attachments/files/18029776/LegacyParticleSystem.resonitepackage.gz)

### Expected behavior

The `LegacyBoxEmitter` converter respects the `EmitFromShell` option.

### Screenshots

![Image](https://github.com/user-attachments/assets/2c279ec1-7ad7-428e-83bc-f1893f350ba0)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[2024.12.5.1194 - 2024-12-05 23_30_51.log](https://github.com/user-attachments/files/18029988/2024.12.5.1194.-.2024-12-05.23_30_51.log)

### Additional Context

The converter appears to create a component called `BoxEmitter+LegacyDirectionConverter` with the `Value` set to false.

![Image](https://github.com/user-attachments/assets/e4177205-11ce-4683-bd36-efe50cf648d7)

If I turn `Value` _on_, it seems to correct the behaviour:

![Image](https://github.com/user-attachments/assets/58337493-5abc-4aad-a92d-72892ee9f268)

### Reporters

`@martysh12` on Discord.

**Comment by Frooxius** [comment] 2024-12-06 09:06
I'm a bit confused by this. I've checked that EmitFromShell field converts and it is respected:

![Image](https://github.com/user-attachments/assets/cf6d2bc2-8a70-4821-b21a-880ac6589d05)

![Image](https://github.com/user-attachments/assets/8a713751-f834-42fe-9926-1b19e01bf45c)

**Comment by orange3134** [comment] 2024-12-06 11:58
@Martysh12 @Frooxius  Isn't this problem in DirectionMode, not in EmitFromShell?

When I convert a LegacyParticle with BoxEmitter's RandomDirection set to 0 to PhotonDust, I find that the particle emission directions do not match.
To resolve this, I had to change the DirectionMode to Fixed in the BoxEmitter of PhotonDust.

https://github.com/user-attachments/assets/511172ce-5735-4c7b-933d-8f14dc073db9

This is the minimum item that can reproduce this.
Do not unzip it. Change the extension to .resonitepackage.
[BoxEmitterDirectionIssue.zip](https://github.com/user-attachments/files/18037825/BoxEmitterDirectionIssue.zip)

**Comment by Martysh12** [comment] 2024-12-06 21:50
> Isn't this problem in DirectionMode, not in EmitFromShell?

I dug a little deeper into this, and yes, you're right! The `EmitFromShell` option is being converted correctly.

From what I've understood, `LegacyBoxEmitter` behaviour is as follows:
 - If `EmitFromShell` is false, particles are emitted from the volume, and they move according to `Direction`.
 - If `EmitFromShell` is true, particles are emitted from the shell, with the direction corresponding the closest face normal.
   - _Unless_ `AlwaysForceDirection` is true, in which case particles are still emitted from the shell, but still follow `Direction`.

The converter converts `LegacyBoxEmitter.AlwaysForceDirection` to `BoxEmitter.DirectionMode = ClosestFaceNormal` (if false) or `BoxEmitter.DirectionMode = Fixed` (if true).
However, the converter doesn't account for the case where both `LegacyBoxEmitter.EmitFromShell` and `LegacyBoxEmitter.AlwaysForceDirection` are false - so it incorrectly sets `BoxEmitter.DirectionMode` to `ClosestFaceNormal`, when the actual behaviour of `LegacyBoxEmitter` in that case would be to follow `LegacyBoxEmitter.Direction`.

So the fix would be to set `BoxEmitter.DirectionMode` to `Fixed` if _both `LegacyBoxEmitter.EmitFromShell` and `LegacyBoxEmitter.AlwaysForceDirection`_ are false.

Comparison of converted fields:
![Image](https://github.com/user-attachments/assets/67021314-bcf1-4258-8fd9-693b4e74bfcb)

Sorry for the misunderstanding! I hope this clarifies things.
@orange3134 @Frooxius

**Comment by Frooxius** [comment] 2024-12-11 05:29
Looks like this was same issue as this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3310

It seems to work okay now since that one got fixed, I'm closing this. Thanks for report!

**Closed by Frooxius** 2024-12-11 05:29 UTC
Labels: bug
