### ISSUE TITLE
hotswap (even if kinda slow) to vr from desktop startup

### ISSUE THREAD

**Issue by Redd56** [Yellow-Dog-Man/Resonite-Issues#3256] opened 2024-12-04 09:30 UTC
### Is your feature request related to a problem? Please describe.

When booting from desktop you sometimes might wanna get on vr. But currently its not possible without rebooting the game fully

### Describe the solution you'd like

A new feature to be able to hotswap vr on even if the game didnt originally start in vr mode 

### Describe alternatives you've considered

Just rebooting my currentky hosted session (and saving and syncing for 10 minutes cause my world is like 100megabytes) to get in vr. 

### Additional Context

This i know isnt trivial at all and would require some qute tricky stuff and need the renderer to prolly reboot real quick to intializw the vr portion (unless its intialized behind the scenes somehow with black magic). But i know of atleast one project thats managed to do it. Vivecraft.
https://github.com/Vivecraft/VivecraftMod ferrinarius iirc was the one who worked on most of the stuff to get hotswap working. How it works currently is you can boot the game without steam vr then boot vr mode once steamvr exists, kill steamvr and go to non vr mode for the day etc. tho it does crash when steam vr crashes. Dead composutor go brrrrt.
If ya wanna ask him abything discord is prolly the easiest eay atleast imo. 

Also im not expecting this to happen any earlier than sauce release cause it would be such a pain to do. 

### Requesters

Redd56

**Comment by shiftyscales** [comment] 2024-12-04 14:32
Thank you for the suggestion, @Redd5, but this is a duplicate of #2999.

**Closed by shiftyscales** 2024-12-04 14:32 UTC
Labels: New Feature

**Comment by Redd56** [comment] 2024-12-04 15:39
Dang it i even searched for 10nwhole minutes

**Comment by shiftyscales** [comment] 2024-12-04 23:31
Thank you for taking the time out to search, @Redd56. We'd always prefer duplicate issues to unreported ones. :)

**Comment by Redd56** [comment] 2024-12-05 02:33
Yw
