### ISSUE TITLE
Binary AND/OR/XOR/etc. for ``byte``

### ISSUE THREAD

**Issue by RubberDuckShobe** [Yellow-Dog-Man/Resonite-Issues#2809] opened 2024-08-24 09:44 UTC
### Is your feature request related to a problem? Please describe.

I want to perform binary AND/OR/XOR operations on a ``byte`` value in ProtoFlux. This isn't possible, because ``byte`` specifically lacks these nodes, while every other number type has a node for this.
![image-80](https://github.com/user-attachments/assets/be1e0b58-dce6-4e90-8cde-0f98be057a40)

### Describe the solution you'd like

It'd be great if ``byte`` had the same binary operator nodes that are present for the other number types.

### Describe alternatives you've considered

An alternative I've considered would be to try and implement these operations myself, perhaps as a custom node.
Another alternative would be to cast the ``byte`` to a ``short``, do the operations there, and try to cast it back to a ``byte``.

### Requesters

m1nt_ (Resonite) / the_crescent_moon (Discord)

**Comment by JackTheFoxOtter** [comment] 2024-08-24 10:19
Duplicate of #1263

**Closed** 2024-08-24 12:25 UTC
Labels: enhancement
