### ISSUE TITLE
Dev Tool doesn't change Gizmo options

### ISSUE THREAD

**Issue by ErrorJan** [Yellow-Dog-Man/Resonite-Issues#698] opened 2023-11-15 18:12 UTC
### Describe the bug?

When not having a Dev Tip equipped and selecting a slot in the inspector then equipping the Dev Tip, opening the context menu to switch the Gizmo options to rotate/scale/etc. doesn't appear.

### To Reproduce

Select any slot in the inspector, then equipping the Dev Tip.
Afterwards opening the context menu and going to Gizmo Options doesn't do anything.

### Expected behavior

Being able to change the gizmo to rotate/scale/etc.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/50844353/0d477875-e980-43c1-b0df-4f79ab5a12a5

### Resonite Version Number

2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[JAN-ARCHPC - 2023.11.13.1343 - 2023-11-15 19_07_37.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13367903/JAN-ARCHPC.-.2023.11.13.1343.-.2023-11-15.19_07_37.log)

### Additional Context

Windows version of the game running on Proton

### Reporters

ErrorJan

**Comment by shadowpanther** [comment] 2023-11-15 18:30
Duplicate of #506

**Comment by ErrorJan** [comment] 2023-11-15 18:37
Ah oops, didn't check that one. Sorry

**Closed** 2023-11-15 18:39 UTC
Labels: bug
