### ISSUE TITLE
CTRL+Tab in Desktop no longer cycles between open sessions

### ISSUE THREAD

**Issue by BlueCyro** [Yellow-Dog-Man/Resonite-Issues#1982] opened 2024-05-06 01:59 UTC
### Describe the bug?

When in desktop mode, the key combination "CTRL+Tab" no longer functions as-intended and does not cycle between session you currently have open.

### To Reproduce

1) Enter desktop
2) Presss CTRL+Tab
3) Note that the currently focused session is unchanged

### Expected behavior

The currently focused session should be cycled on each press of the key combo.

### Screenshots

N/A

### Resonite Version Number

2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-6C2UJFB - 2024.5.4.678 - 2024-05-05 20_49_41.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15215263/DESKTOP-6C2UJFB.-.2024.5.4.678.-.2024-05-05.20_49_41.log)

### Additional Context

This appears to be inconsistent, as @EuphieEuphoria notes that it works on his machine.

### Reporters

Myself, @VRBat, @Raidriar796, @EuphieEuphoria

**Comment by VRBat** [comment] 2024-05-06 02:01
Having the same issue as well: 

Tried switching between my personal cloud home and local
[BATTOP - 2024.5.4.678 - 2024-05-05 20_57_33.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15215286/BATTOP.-.2024.5.4.678.-.2024-05-05.20_57_33.log)

Tried switching between Default Cloud Home, my personal cloud home, and Local
[BATTOP - 2024.5.4.678 - 2024-05-05 20_55_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15215287/BATTOP.-.2024.5.4.678.-.2024-05-05.20_55_36.log)

**Comment by shiftyscales** [comment] 2024-05-06 05:02
I can not reproduce this issue. I am on the latest build `Beta 2024.5.4.678` and am able to tab between active sessions I am in without issue, @BlueCyro @VRBat.

**Comment by Lexevolution** [comment] 2024-05-06 05:40
Here is a video and corresponding log of this feature still working for me as of the latest version 2024.5.4.678.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/31176843/eb66dc88-9950-48b1-8577-05320dea8cac

[LEXDESKTOP - 2024.5.4.678 - 2024-05-06 15_33_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15217169/LEXDESKTOP.-.2024.5.4.678.-.2024-05-06.15_33_10.log)

**Comment by XDelta** [comment] 2024-05-06 10:21
What I suspect in the cases it isn't working is that some exception is occurring that is making the Userspace component disable itself. This issue isn't occurring for myself but the described results sound like `Userspace.OnCommonUpdate()` isn't running which may indicate it disabled itself. Can manually replicate the symptoms by manually disabling this component in my userspace.

**Comment by shiftyscales** [comment] 2024-05-07 20:15
Thanks for the additional info, @XDelta - we'd definitely need more information on what (without the use of mods) might be causing the initial exception that causes the Userspace component to become disabled in the first place.

If mods are in-use, it would be useful for @BlueCyro @VRBat and others to try and isolate what mod is causing this issue so it could be reported to its respective mod author.

**Comment by XDelta** [comment] 2024-05-08 01:49
The provided log does not show mods are in use and from separately asking them to confirm in discord, they confirmed that mods are not in use and the issue was still occurring.

**Comment by shiftyscales** [comment] 2024-05-09 16:41
@XDelta - I meant that if mods were *ever* in use. E.g. if a mod caused some issue that persisted even when the mods are not being used. So far that's the only thing I have to go on- the users reporting this issue are users that have been known to make use of/develop mods, and I have at no point ever used a third-party modification to Resonite and I do not experience this issue.

It is not a guarantee mods are responsible- but regardless to that- we would still need to identify why that component was disabled/the source of the exception that would have caused it to disable itself.

**Comment by shiftyscales** [comment] 2024-10-03 21:30
I am still unable to reproduce this issue, so I will be closing it for now unless @BlueCyro or @VRBat can provide additional context on how to replicate this issue.

**Closed by shiftyscales** 2024-10-03 21:30 UTC
Labels: bug, cannot reproduce, needs more information
