### ISSUE TITLE
Protoflux Pulse Display Nodes Outputs

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#52] opened 2023-10-13 22:28 UTC
### Is your feature request related to a problem? Please describe.

it is a bit annoying that you cant have a visual of your protoflux working and your actual protoflux working at the same time

### Describe the solution you'd like

Solution to this problem would be to add an output to the protoflux pulse display nodes which would allow you to place them at any point in the pulse chain and have a visual of what is happening

### Describe alternatives you've considered

I cant think of a better solution and the only other fix that has been used in the past is the mod that gives pulse visuals on the ribbons, but a lot of people hated those and it could cause major performance problems

**Comment by shiftyscales** [comment] 2024-10-03 21:16
Based on your description, it sounds like the needs of this issue would likely be covered by #1122 if I'm understanding your need correctly, @ultrawidegamer? It sounds like you are just wanting to see and track ProtoFlux execution as it is occurring?

**Comment by ultrawidegamer** [comment] 2024-10-03 22:51
yes that should cover the situation that i was asking about

**Comment by shiftyscales** [comment] 2024-10-03 23:22
Thank you, even though this issue was opened first, I will close and merge this as a duplicate of the linked issue. I've added you as a requester on that issue.

**Closed by shiftyscales** 2024-10-03 23:22 UTC
Labels: enhancement, needs more information
