### ISSUE TITLE
Changing audio output by unplugging and plugging heaphones right after (no matter what type, wireless or not) freezes the client and crashes.

### ISSUE THREAD

**Issue by mrkbx** [Yellow-Dog-Man/Resonite-Issues#1739] opened 2024-04-17 10:45 UTC
### Describe the bug?

Title explains.

### To Reproduce

Unplug headphones from your PC when using them as an audio output for resonite, then replug them in.

### Expected behavior

Resonite doesn't freeze or crash and continues normally.

### Resonite Version Number

2024.4.17.208

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-4RMO1K3.-.2024.4.17.208.-.2024-04-17.12_40_56.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15009955/DESKTOP-4RMO1K3.-.2024.4.17.208.-.2024-04-17.12_40_56.log)

### Reporters

mrkbx

**Comment by Frooxius** [comment] 2024-04-17 17:49
1) Is the toggle to use the system output audio device on or off?
2) If it's off, what is your second device after your primary one in the priority list?
3) Can you provide Player.log file for this as well?

**Comment by mrkbx** [comment] 2024-04-18 10:37
1. It's on
2. Speakers in my second monitor
3.  [Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15023532/Player.log)

**Comment by ohzee00** [comment] 2024-04-22 23:49
Just to add my two cents, I've been noticing a uptick of users having crashes and when helping them debug it, it keeps pointing to this issue in particular with disconnecting or reconnecting audio devices as of recently.

Shifty's logs in particular seem really useful, it is weirdly spammed with
 `XR: Error setting active audio output driver.  Falling back to default` which doesn't seem to stop til Resonite dies

**Comment by Frooxius** [comment] 2024-04-23 19:48
I can't really get this to happen or glean much useful from the logs.

When you unplug the audio device, is there any other device present in the system? Or is Resonite left with no audio-devices?

The error in Shifty's log seems relevant to Oculus SDK code maybe? But the original report is just desktop, rather than VR/XR.

**Comment by niddey** [comment] 2024-04-25 13:41
My audio output devices are

- Yeti nano - Set to 24bit 48kHz, supports 44.1kHz.
- Schiit Fulla 3 - Set to 32bit 48kHz, but support 16/24/32bit 44.1kHz - 192kHz. This is what I mainly use.
- Realtek USB Audio - Set to 24bit 48kHz, supports 16/24bit 44.1kHz - 192kHz.
- NVIDIA High Definition Audio - Set to 16bit 48khz, only supports 16/24bit 48kHz.

Input

- Virtual Desktop Audio, 1 channel, 16bit 48kHz
- Rode GO II RX, 2 channels 24bit 48kHz
- Schiit Fulla 3 - 2 channels 24bit 48kHz
- Airpods - 16bit 16kHz

In the audio enchancements of the Yeti Nano it shows a "Logitech HX2E Surround Sound Effect" so I guess virtual surround thing and thats why it shows up as 8 channels. I disconnected this device and the game still freezes when I disconnect the airpods.
If the issue was the same as #1704 I would expect it to also have the unity crash but here the game only freezes forever, maybe still related though.

**Comment by Dusty-Sprinkles** [comment] 2024-04-28 21:16
I've been able to replicate this also but instead of plugging in and unplugging an audio device, if I close and reopen nvidia broadcast because I use it as my default output (or it is not open on launch) the game will freeze, though I don't completely crash out it just never comes back

Two logs where I had the issue occur are below

[DESKTOP-GCR6JOJ - 2024.4.26.1258 - 2024-04-28 16_11_23.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15143804/DESKTOP-GCR6JOJ.-.2024.4.26.1258.-.2024-04-28.16_11_23.log)
[DESKTOP-GCR6JOJ - 2024.4.26.1258 - 2024-04-28 16_02_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15143805/DESKTOP-GCR6JOJ.-.2024.4.26.1258.-.2024-04-28.16_02_11.log)

**Comment by niddey** [comment] 2024-04-29 17:59
I tested disabling all of the audio playback devices and it does not seem to make a difference on what device I leave enabled. If there is no other device enabled except the airpods, then the game does not freeze when they are connected but if there is even a single one enabled it will freeze. Disabling all of the recoding revices also did not make a difference, the result was similar. Game settings were set to use the default output device.

**Comment by Frooxius** [comment] 2024-05-07 06:56
@Dusty-Sprinkles I'll need the Player.log one for this unfortunately. The normal logs don't show anything.

**Comment by dragos240** [comment] 2024-05-07 19:52
I'm getting the same thing. I always have to choose between turning my earbuds off to charge or keep Resonite running.

Here's my [Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15240222/Player.log)

**Comment by Frooxius** [comment] 2024-05-07 20:35
Hmm... I'm not really seeing any sort of pattern in any of this yet.

Some parts that complicate this is that I'm not fully clear on replication steps for other reports too. Notably if the default system output device is enabled or disabled, what are the other audio devices on the system and which action specifically causes the freeze.

I'd ideally need some clear way to replicate this behavior on my end, but given that a lot of these reports seem device specific, I'm not sure how to make this happen reliably on my end. I tried turning devices on and off, changing default and so on, but nothing causes Resonite to freeze on my end.

**Comment by Dusty-Sprinkles** [comment] 2024-05-09 01:02
Here's my player.log 
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15256328/Player.log)

The steps I personally did were as follows:
1. Launch resonite with Nvidia Broadcast not open
2. Playing on desktop so set my default PC devices to my headset microphone and speakers after steamvr finishes launching
3. Wait for the initial loading lag to go away
4. Go to Audio settings in Resonite and verify that nvidia broadcast is still shown as a device by default
5. Open Nvidia Broadcast and Freeze the game

**Comment by Inucune2** [comment] 2024-05-23 18:29
This appears to be caused when an active audio output is connected/disconnected.
I have recorded a demonstration of it. In this case i am switching on a set of Jpop Bluetooth earbuds.
https://youtu.be/KYI6D-9NNl4

log from this testing attached. 
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15421035/Player.log)

**Comment by Frooxius** [comment] 2024-05-24 00:01
This should be fixed in 2024.5.23.1416 now! I think I found the root cause to be a deadlock. 

If this still occurs, comment and we'll reopen this.

**Closed by Frooxius** 2024-05-24 00:01 UTC
Labels: bug, crash, triaged, needs more information
