### ISSUE TITLE
More Dynamic Components/nodes

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#3215] opened 2024-11-25 13:18 UTC
### Is your feature request related to a problem? Please describe.

Currently writing and reading dynamic variables and references inside components dynamically is not really possible.

### Describe the solution you'd like

being able to read and write dynamic variables/references from things like button events or virtual keyboards.

### Describe alternatives you've considered

using protoflux to write variables.

### Additional Context

we have button dynamic impulse triggers that use impulses.

### Requesters

charlie-san

**Comment by ProbablePrime** [comment] 2024-11-25 13:27
Its two components, but you can use ButtonValue/ObjectSet + DynamicValueVariable to achieve this.

Seeing as ButtonValueSet can be targeted to other components and that you usually need a DynamicValueVariable somewhere to read/write from anyway. You can usually get away with just having 1 ButtonValueSet per actual button.

A common thing I sometimes do for buttons is to Copy the Slot Name, into a UIX Text Object and into the ButtonValueSet on it(Using child indexes is also common).

**Comment by 3x1t-5tyl3** [comment] 2024-11-25 13:34
> Its two components, but you can use ButtonValue/ObjectSet + DynamicValueVariable to achieve this.
> 
> Seeing as ButtonValueSet can be targeted to other components and that you usually need a DynamicValueVariable somewhere to read/write from anyway. You can usually get away with just having 1 ButtonValueSet per actual button.
> 
> A common thing I sometimes do for buttons is to Copy the Slot Name, into a UIX Text Object and into the ButtonValueSet on it(Using child indexes is also common).

I don't disagree; but I'd still think dedicated components would be the correct way to handle this IMHO

**Comment by JackTheFoxOtter** [comment] 2024-11-25 13:38
Duplicate of #1630 I think, where Froox already mentioned he wants to add more.

**Comment by ProbablePrime** [comment] 2024-11-25 13:40
Yup this is a duplicate!

I'll close it and we'll merge across to [#1630 ](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1630).

That issue is one of those Fun things that's easy to pick up but might happen randomly. Like right now I feel like I could go do it, but I'm going to bed instead which is a much better idea :D

**Closed by ProbablePrime** 2024-11-25 13:40 UTC
Labels: New Feature
