### ISSUE TITLE
Missing localisations for English (Australia)

### ISSUE THREAD

**Issue by hakanai** [Yellow-Dog-Man/Resonite-Issues#2250] opened 2024-06-07 03:03 UTC
### Describe the bug?

During signup / first login, I saw some untranslated strings in my locale, which is English (Australia).

1. Settings.Locale.SelectLanguageHeader
2. Settings.Locale.DefaultLanguage
3. Settings.Audio.InputDevice
4. Settings.Audio.TestInput
5. Settings.Audio.TestDescription
6. Settings.Audio.StartTest
7. Settings.Audio.Monitoring

I assume English (Australia) falls back to English (United Kingdom) if things are working sensibly, so this might mean they're really missing from the UK strings?

### To Reproduce

Sign up as a new user.

### Expected behavior

I should see whatever translation is seen by the UK users, I doubt there will be many places where it's different, if you're doing the usual thing of dodging colloquialisms in UI.

### Screenshots

![Missing localisation 1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/43236/9336530b-4c51-4044-976c-7021fbf3297b)

![Missing localisation 2](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/43236/0dfbf7e7-46da-4e5b-9511-5d04969d13ef)

### Resonite Version Number

Beta 2024.6.5.1084

### What Platforms does this occur on?

Windows

### Log Files

Do I really need a log for this one?

But thanks for making me read the log file, that gives me another idea for a ticket.

Logs:

[LULZ-DEV - 2024.6.5.1084 - 2024-06-07 06_22_08.log](https://github.com/user-attachments/files/15695869/LULZ-DEV.-.2024.6.5.1084.-.2024-06-07.06_22_08.log)

**Comment by Banane9** [comment] 2024-06-07 12:17
There is no specific australian english locale in vanilla, just US and UK. Some of the audio settings strings got deleted in the Settings Update https://github.com/Yellow-Dog-Man/Locale/issues/241

**Comment by Frooxius** [comment] 2024-06-07 17:52
There's been some stuff that got moved around with the new Settings UI, that we didn't get to clean up yet. We'll try to get these resolved soon.

**Comment by stiefeljackal** [comment] 2024-06-10 15:56
Wouldn't this be a duplicate of #1837, @Frooxius?

**Comment by Frooxius** [comment] 2024-07-24 16:39
It is, I'm closing this as duplicate, thanks!

**Closed by Frooxius** 2024-07-24 16:39 UTC
Labels: bug, duplicate, triaged
