### ISSUE TITLE
Resonite Steam API does not return playtime for user

### ISSUE THREAD

**Issue by 989onan** [Yellow-Dog-Man/Resonite-Issues#1279] opened 2024-01-31 23:40 UTC
### Describe the bug?

A setting for the Resonite on steam seems to not have been changed, because when I try to send an API request for steam and try to search for the app's ID "2519830" on an API call for all my steam games, it does not return with a result. Though if I search for other apps like Blender and Satisfactory, they do return a playtime with the same setup.

### To Reproduce

`Use any valid Steam API key and send a request for https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=<YOUR STEAM API KEY>&steamid=<STEAM ID OF USER THAT PLAYS RESONITE>`

And it will not have a result for resonite with the app ID "2519830"

### Expected behavior

Resonite should be able to be read via the steam API, and I should be able to read playtimes.

### Screenshots

Code used for calling API
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29756848/c8ecbb0f-cc5e-4f07-9f6b-e4835223e904)

### Resonite Version Number

Beta 2024.1.31.744

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[CHEW-PC - 2024.1.31.744 - 2024-01-31 18_36_48.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14118513/CHEW-PC.-.2024.1.31.744.-.2024-01-31.18_36_48.log)

**Comment by 989onan** [comment] 2024-01-31 23:55
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29756848/f6a424e6-d63b-4370-b065-b6434f5599b2)
yes and yes. It is able to grab every other game on my steam *except* resonite

**Comment by 989onan** [comment] 2024-02-01 00:01
Also for additional context, here's the return string it gives when I do the call (WARNING, BIG)
<details><summary>Details</summary>
<p>
`{"response":{"game_count":23,"games":[{"appid":4000,"playtime_2weeks":39,"playtime_forever":24973,"playtime_windows_forever":10186,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1697561692,"playtime_disconnected":0},{"appid":12360,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":105600,"playtime_forever":61851,"playtime_windows_forever":27673,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1694030297,"playtime_disconnected":1},{"appid":262410,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":211820,"playtime_forever":6690,"playtime_windows_forever":6690,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1694134721,"playtime_disconnected":0},{"appid":367540,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":366090,"playtime_forever":384,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1522855687,"playtime_disconnected":0},{"appid":365670,"playtime_2weeks":2540,"playtime_forever":255763,"playtime_windows_forever":221967,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1697726349,"playtime_disconnected":0},{"appid":431960,"playtime_2weeks":1,"playtime_forever":1322,"playtime_windows_forever":1322,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1697463899,"playtime_disconnected":0},{"appid":457550,"playtime_forever":692,"playtime_windows_forever":191,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1658863692,"playtime_disconnected":0},{"appid":526870,"playtime_forever":2595,"playtime_windows_forever":2595,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1696039291,"playtime_disconnected":0},{"appid":661130,"playtime_forever":109,"playtime_windows_forever":109,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1694216969,"playtime_disconnected":0},{"appid":304930,"playtime_forever":8924,"playtime_windows_forever":1560,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1637186427,"playtime_disconnected":0},{"appid":740250,"playtime_2weeks":291,"playtime_forever":201164,"playtime_windows_forever":201164,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1696565464,"playtime_disconnected":0},{"appid":637650,"playtime_forever":46,"playtime_windows_forever":46,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1641343060,"playtime_disconnected":0},{"appid":684410,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":808810,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":730,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":546560,"playtime_forever":549,"playtime_windows_forever":549,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1658016898,"playtime_disconnected":0},{"appid":1281930,"playtime_forever":5055,"playtime_windows_forever":5055,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1681001307,"playtime_disconnected":0},{"appid":346110,"playtime_forever":220,"playtime_windows_forever":220,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":1655877542,"playtime_disconnected":0},{"appid":407530,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0},{"appid":489630,"playtime_forever":0,"playtime_windows_forever":0,"playtime_mac_forever":0,"playtime_linux_forever":0,"rtime_last_played":0,"playtime_disconnected":0}]}}`


</p>
</details>

**Comment by 989onan** [comment] 2024-02-01 00:08
ah so I can change the request string for now. Wonder why it returned Blender which is a free game and not Resonite O-o

**Comment by 989onan** [comment] 2024-02-01 01:04
I did another test, and using the arguments `https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=<REDACTED>&steamid=76561198796666207&include_appinfo=1&include_played_free_games=1` and searched for Resonite. Zero results unfortunately. Am I using the command wrong? It returns free games like TF2 as well

**Comment by ProbablePrime** [comment] 2024-02-01 05:46
This is likely caused by this: 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/b207e199-2645-4cae-a582-feea18816574)

As it was also affecting some other thing, I think the featured game section. There's an issue somewhere on here about it.

You can read more about that icon on our steam page here: https://partner.steamgames.com/doc/marketing/profile

But we can't control it so I'll be closing this as won't fix, because steam are the only ones who can fix it.

**Closed by ProbablePrime** 2024-02-01 05:46 UTC
Labels: bug, needs more information
