### ISSUE TITLE
Launching Resonite with SteamLink while controllers are asleep makes controllers not track

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2944] opened 2024-09-13 02:10 UTC
### Describe the bug?

If you launch Resonite using Steamlink while your controllers are asleep, Resonite won't track them, Even if SteamVR is tracking them. Resonite is getting input data (Like Laser shows when pulling their triggers) but their position/rotation doesn't track.

### To Reproduce

1. Connect to Steamlink
2. Make sure your controllers are off/asleep (Usually auto does this if they're put down)
3. Launch Resonite
4. Wake your controllers up. See they're tracking in SteamVR but not in Resonite.

### Expected behavior

For controllers to resume tracking like SteamVR does.

### Resonite Version Number

2024.9.12.772

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

N/A

### Additional Context

If controllers are asleep and Resonite doesn't pick it up, I have to restart Resonite for tracking to be fixed.

### Reporters

SilyPaws

**Comment by Frooxius** [comment] 2024-09-13 02:10
We need logs for this

**Comment by SilvyPaws** [comment] 2024-09-13 02:24
> We need logs for this

Logs in #2945 will probably be relevant as they're sister issues I believe

**Comment by ko-tengu** [comment] 2024-09-13 15:53
This is a duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/927

**Closed** 2024-10-23 03:34 UTC
Labels: bug, needs more information
