### ISSUE TITLE
Textures Desaturation

### ISSUE THREAD

**Issue by BlueBoyBlitz** [Yellow-Dog-Man/Resonite-Issues#2466] opened 2024-07-04 00:15 UTC
### Describe the bug?

I had saved my item, a new avatar with new textures, to my inventory and when I spawned it back out, it was de-saturated. I remember this issue showing up on the discord, a user named "Fel" was asking about this issue and I saw there was no ticket for this since a log had not been attained, so I grabbed my log.

### To Reproduce

I think Ohzee mentioned it might be an issue with the texture variants not being processed completely, so if that's true, then it's because I had just imported all of those textures in that session. So Importing new textures, applying them, saving the object and bringing it back out should do the same.

### Expected behavior

I expected the colors to be more saturated and stay the same after saving, after applying "ForceAssetVariant" on the colors returned to normal.

### Screenshots

![Resonite_HJXdp1d5oj](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66147111/9b0ebe29-c54a-4d4a-983c-20c61b1073d5)
![Resonite_pApfz6dpB8](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66147111/38282ec0-1b9c-44d6-ad88-f7d40d0ba1dd)

### Resonite Version Number

Beta 2024.6.25.1149

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index, but was in desktop at the time.

### Log Files

[DESKTOP-HHL3GN6 - 2024.6.25.1149 - 2024-07-03 17_19_27.log](https://github.com/user-attachments/files/16091818/DESKTOP-HHL3GN6.-.2024.6.25.1149.-.2024-07-03.17_19_27.log)

### Additional Context

I'm not sure I got the names correct in the reporters. There's a thread on the discord for it!

### Reporters

@Fel @Lux @Jack @ohzee @Blue

**Comment by Geenz** [comment] 2024-07-04 00:17
When you inspect the static texture provider - what is the reported color space?

**Comment by BlueBoyBlitz** [comment] 2024-07-04 00:36
Before I applied ForceAssetVariant, it was set to RGBHalf when it was desaturated. Some Say sRGB and some say Linear after turning it on.

**Comment by Geenz** [comment] 2024-07-04 00:37
This _could_ be something clogged up in the asset variant queue.

**Comment by lxw404** [comment] 2024-07-04 02:33
If it is actually something to do with the asset variant system, is there a particular reason that it falls back to `RGBAHalf` specifically?  This variant almost universally is not what users want for color data for sure.

I've experienced an entire world going desaturated like this before, but had no idea what was causing it until later explained that this could happen.

**Comment by shiftyscales** [comment] 2024-07-04 18:27
@Geenz @BlueBoyBlitz @lxw404 - This is a duplicate of #1595 on which Frooxius had noted:
"The issue here is that we don't apply proper color space processing on certain textures when they're loaded from raw source when the asset variants do not exist."

**Closed** 2024-07-04 18:27 UTC
Labels: bug, duplicate
