### ISSUE TITLE
Specific OBJ file failing to import

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2843] opened 2024-09-02 17:24 UTC
### Describe the bug?

Trying to paste https://graphics.stanford.edu/courses/cs148-10-summer/as3/code/as3/teapot.obj into Resonite does not work and gives an "Exception when decoding file!" after going through the menu.

### To Reproduce

1. Copy `https://graphics.stanford.edu/courses/cs148-10-summer/as3/code/as3/teapot.obj` to your clipboard.
2. Press Ctrl+V in Resonite
3. Click the first option in the import dialog until it starts importing
4. Observe the error

### Expected behavior

The model should appear.

### Screenshots

Failing import dialog:
![image](https://github.com/user-attachments/assets/10713975-ef72-4284-b04f-fab1bfc2f5db)

The same file in Blender:
![image](https://github.com/user-attachments/assets/01de66cc-0b75-49b8-a793-a0da698cceed)

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

I do not feel comfortable sharing my log files, especially for issues this easily reproduced.

### Additional Context

This is the [Utah Teapot](https://www.wikipedia.org/).

### Reporters

cameron5 on Discord, Psychpsyo in Resonite

**Comment by Frooxius** [comment] 2024-09-02 18:44
This needs logs. Especially since it throws an exception.

**Comment by Dusty-Sprinkles** [comment] 2024-09-02 19:07
Since a replication object was provided I went and looked in my own logs, this appears to be the exception.
`2:04:45 PM.212 ( 19 FPS)	Exception when importing https://graphics.stanford.edu/courses/cs148-10-summer/as3/code/as3/teapot.obj:

System.IO.FileNotFoundException: Filename was null or could not be found
File name: 'https://graphics.stanford.edu/courses/cs148-10-summer/as3/code/as3/teapot.obj'
   at Scene Assimp.AssimpContext.ImportFile(string file, PostProcessSteps postProcessFlags)
   at IEnumerator<Context> FrooxEngine.ModelImporter.ImportModel(string file, Slot targetSlot, ModelImportSettings settings, Slot assetsSlot, IProgressIndicator progressIndicator)+MoveNext()`

**Comment by bredo228** [comment] 2024-09-02 20:33
Downloaded the model to my computer and it imported normally into Resonite.

Appears to be related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1439

**Comment by shiftyscales** [comment] 2024-09-03 02:54
Yes, this is a duplicate of #1439. There is not currently a mechanism for importing a model from a remote source.

> We just need to add mechanism to handle this and either download and proxy the file access.
> 
> It might take a bit, because often there can be multiple files that might be discovered as the import happens.

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1439#issuecomment-1977303060

**Closed by shiftyscales** 2024-09-03 02:54 UTC
Labels: bug, needs more information
