### ISSUE TITLE
Built in and safety protections against malicious users

### ISSUE THREAD

**Issue by quellus** [Yellow-Dog-Man/Resonite-Issues#2315] opened 2024-06-13 05:43 UTC
### Is your feature request related to a problem? Please describe.

I don't think this issue is rampant, but it is present. Players are able to force kick other players out of worlds, launch them into the void, freeze them in place, and change their scale.

I've had situations where players have forced me into a backrooms world. Because I was new to Resonite, I didn't know what was happening and ran around the maze for quite a while trying to get back to the people I was hanging out with before realizing I could just refocus on the world I was in.

I've also been launched across worlds, and again, because I as fairly new, I didn't know the many methods to respawn myself.

I think this could drive away new users and finding a solution would increase the amount of people who try Resonite for the first time and keep coming back.

### Describe the solution you'd like

I think protections should be built in. Allowing players to yeet you into the stratosphere, or force you out of the world should be a setting I can change.

### Describe alternatives you've considered

Quite a few players have made protection systems that stop other players from doing these actions to them. The reason I'm making this issue is that these systems aren't accessible to new players. It requires meeting the right people or happening to find the right public folder.

### Additional Context

I think it's important to make this platform more accessible to new users. Making sure people are safe and limiting malicious activities I think will be important and necessary in keeping new users on this platform.

**Comment by ProbablePrime** [comment] 2024-06-13 05:46
Thanks for making the issue, this is unfortunately a duplicate of the goals that will be solved by #1103

**Closed by ProbablePrime** 2024-06-13 05:46 UTC
Labels: enhancement
