### ISSUE TITLE
Resonites E-mail server seems to be down

### ISSUE THREAD

**Issue by ItsCybrix** [Yellow-Dog-Man/Resonite-Issues#2723] opened 2024-08-05 23:46 UTC
### Describe the bug?

The server used for sending emails to users seems to be offline. Making an account and ticket does not send an email both gmail and proton mail

### To Reproduce

Either make an account or a ticket and the confirmation email does not get sent.

### Expected behavior

For the email to send without issues

### Screenshots

![image](https://github.com/user-attachments/assets/09f42045-a886-4397-9777-131c199acfa9)

### Resonite Version Number

2024.8.5.1341

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

[OLDFART - 2024.8.5.1341 - 2024-08-05 19_41_16.log](https://github.com/user-attachments/files/16503605/OLDFART.-.2024.8.5.1341.-.2024-08-05.19_41_16.log)

### Reporters

CYBRIXTHEPROOOOOT

**Comment by ProbablePrime** [comment] 2024-08-06 00:02
I am not able to reproduce this. Emails are generated from both sources you describe.

**Comment by PuppyGoesWoof** [comment] 2024-08-06 00:14
Made an account to say I'm having the same issue. Even tried using another email and got nothing (I'm using gmail)

**Comment by DanteTucker** [comment] 2024-08-06 00:15
I did a few tests.
Both creating accounts and using our /sendtestemail command and am not receiving emails to any address @ProbablePrime

**Comment by ohzee00** [comment] 2024-08-06 00:25
I did a slight test on my own and generated a usage report, it has so far been 10 mins and I have yet to receive it in my email, including spam folders. Last time I did this it was nearly instant.

**Comment by ProbablePrime** [comment] 2024-08-06 00:28
Ok, Support desk emails are up.
SkyFrost Emails are not sending.

**Comment by ProbablePrime** [comment] 2024-08-06 00:40
Frooxius is looking.

**Comment by Frooxius** [comment] 2024-08-06 01:05
I have looked into this, but it seems like it might be an Azure issue.

I've made a post in their community forums if anyone wants to have a look (it contains more details): https://learn.microsoft.com/en-us/answers/questions/1855494/azure-communications-suddenly-fails-to-deliver-to

Until then, email is down unfortunately.

**Comment by bredo228** [comment] 2024-08-06 01:20
Managed to get a test email sent through to the provider I use, and am seeing the duplicate Message-ID headers that the error message in the community forums post is showing:

```
Message-ID: <2024[redacted]======@microsoft.com>
Sender: Resonite <noreply@resonite.com>
...
Message-ID: 6980[redacted]======
```

**Comment by Frooxius** [comment] 2024-08-06 01:22
@bredo228 Problem here is that we don't control these. This issue happens even if I use the "Try Email" in the Azure portal to send a test one - which is using just Microsoft's stuff and doesn't involve our code.

It sounds to me like either Azure changed something recently or Gmail did.

**Comment by bredo228** [comment] 2024-08-06 01:27
> @bredo228 Problem here is that we don't control these. This issue happens even if I use the "Try Email" in the Azure portal to send a test one - which is using just Microsoft's stuff and doesn't involve our code.

I'm aware of that, just demonstrating the issue on an email that did come through.

> It sounds to me like either Azure changed something recently or Gmail did.

Seems like it's an Azure problem - I took a look at an email I received from SkyFrost on 2024-08-03 (3 days ago) and it only has a single Message-ID header. My mail provider is not gmail

**Comment by Frooxius** [comment] 2024-08-06 01:28
@bredo228 Oooh! That's very good info, thank you!

**Comment by Frooxius** [comment] 2024-08-06 01:30
Also I'm a dummy and forgot we got SendGrid as fallback. It wasn't being triggered, because the API said that the message was sent successfully - it doesn't catch that it bounces after.

I've swapped our cloud to use SendGrid as primary for now, which should work (I tested it), while Azure figures this out.

**Comment by Frooxius** [comment] 2024-10-22 23:51
We've swapped back since Azure seems to have resolved their issue. I'm closing this now. Thanks for everyone's reports and helping to investigate!

**Closed by Frooxius** 2024-10-22 23:51 UTC
Labels: bug, infrastructure, triaged
