### ISSUE TITLE
Quest Pro Face Tracking doesn't work using Steam Link and SteamVR Beta

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3067] opened 2024-10-11 02:05 UTC
### Describe the bug?

If you try using the beta of SteamVR and Steam Link, Face tracking does not function.

### To Reproduce

Start Resonite (either prerelease or live) and try using the steam link beta with the hand tracking. Face tracking does not function.

### Expected behavior

For the face tacking to work.

### Resonite Version Number

2024.10.8.1349

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[DESKTOP-QBGCSAQ - 2024.10.8.1349 - 2024-10-10 18_54_26.log](https://github.com/user-attachments/files/17336632/DESKTOP-QBGCSAQ.-.2024.10.8.1349.-.2024-10-10.18_54_26.log)

### Additional Context

Other OSC Programs appear to work, Just not Resonite.

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment] 2024-10-11 02:07
Are there any changes in the beta that could cause this maybe? I'll have to have a poke, but if anyone's aware of anything that could help.

**Comment by Frooxius** [comment] 2024-10-11 02:27
I found the cause. For some reason the beta of SteamLink reports itself as "Oculus Quest2" even though I use Quest Pro. I'm not sure why this is the case, but it makes the system not register the SteamLink OSC driver.

I'll have to investigate some more.

**Comment by Frooxius** [comment] 2024-10-11 02:35
Hmm... this is really weird. Sometimes it does identity itself properly as SteamLink with Quest Pro, sometimes it acts like it's Quest 2 that's connected directly.

**Comment by Frooxius** [comment] 2024-10-11 02:41
Ok I found a pattern. If hands are active when Resonite starts, it'll identify itself as Quest 2. If controllers are active, it'll identity itself as Quest Pro over Steam Link.

I have no idea why it's happening. It's either a bug or some kind of weird thing for compatibility with other apps?

But unfortunately it breaks compatibility with ours, because we don't initialize the SteamLink OSC driver unless it says it's running over SteamLink - because there's no point otherwise. But now I don't have a reliable way to identify if it's running over SteamLink.

**Comment by ScarsTRF** [comment] 2024-10-11 03:24
Could there be a manual override for the time being for the users who actually use it?

**Comment by Frooxius** [comment] 2024-10-11 03:25
My goal right now is to just fix it. I've asked about this on the Valve forums, so I'll see what they say.

**Comment by Frooxius** [comment] 2024-10-11 03:46
For reference: https://steamcommunity.com/app/353380/discussions/0/4335357389280805897/?ctp=3

**Comment by Frooxius** [comment] 2024-10-11 03:57
Here for reference: https://steamcommunity.com/app/353380/discussions/11/6781949392681538656/

**Comment by zahndy** [comment] 2024-10-11 07:00
I wrote a mod a while ago to get around/force this https://discord.com/channels/1040316820650991766/1278292136239955968
didn't really bother creating a issue for this as this was beta stuff and could still change

**Comment by ModernBalloonie** [comment] 2024-10-26 01:00
So... steamVR just got an update and now it's just broken. I'm going to use the mod in the meantime though.

**Comment by Frooxius** [comment] 2024-10-26 01:08
Ow... And I got no answers from Valve :/ https://steamcommunity.com/app/353380/discussions/11/6781949392681538656/

I'll just force this to initialize always. Which sucks, because even if you're not using Steam Link, it'll take some system resources, but there's not really a way around it.

**Comment by shiftyscales** [comment] 2024-10-26 02:43
@Frooxius - It may be worth contacting Steam support directly. https://help.steampowered.com/en/wizard/HelpWithGameIssue/?appid=353380&issueid=354&nodeid=1&return_nodeid=9

> If you have other issues or questions, contact [Steam Support](https://help.steampowered.com/en/wizard/HelpWithGameIssue/?appid=353380&issueid=354&nodeid=1&return_nodeid=9) and attach the remote_connections.txt
> and driver_vrlink.txt
> log files to your ticket.
> 
> The default location for this file on your PC is C:\Program Files (x86)\Steam\logs

From: https://help.steampowered.com/en/faqs/view/0E2C-406B-9135-38A4

At the least I imagine it'd help get the right eyes on your thread above if you link it to them directly.

**Comment by Nytra** [comment] 2024-10-26 12:00
I'm using Quest Pro and Steam Link Beta and the face and eye tracking is working for me, you need to enable it in the Steam Link settings

**Comment by shiftyscales** [comment] 2024-10-27 04:03
@ModernBalloonie @Frooxius @ScarsTRF @zahndy - Can you look into what Nytra and Rue posted above? It sounds like Steam separated out that functionality into a setting that you have to explicitly enable now. It sounds like we might not have to do anything on Resonite's end to correct that issue if the user enables that setting to properly pass through the correct data.

**Comment by Frooxius** [comment] 2024-10-29 02:21
I have a fix for this in place, though it forces the SteamLink OSC driver to activate anytime Oculus headset is detected.

The issue is, you won't be able to replicate it every time. For some reason, the latest version of SteamLink changes the headset identification from the actual headset over SteamLink, to specifically Quest 2 running natively (even if I'm using Quest Pro in my case for testing), which broke the system that was looking for SteamLink specifically.

If you don't ever switch to hand tracking, then this change in identification never happens and it'll work normally, but once you do, it seems to get stuck with it. 

I'll have it out in the next build.

**Comment by Amethyst-Fox** [comment] 2024-10-29 03:03
Workaround for now I just found, Turn off hand and body tracking in the quest settings

**Comment by Frooxius** [comment] 2024-10-29 20:53
This fix is now out in 2024.10.29.1229. Thanks!

**Closed by Frooxius** 2024-10-29 20:53 UTC
Labels: bug, triaged
