### ISSUE TITLE
Add adjerry's Unified Expressions to facetracking auto detection

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2973] opened 2024-09-16 18:26 UTC
### Is your feature request related to a problem? Please describe.

As facetracking gets more and more popular from used Quest Pros becoming cheaper and other factors, more and more avatars are either adding 1st party face tracking support or 3rd parties are adding facetracking DLC's such as [AdJerry](https://adjerry91.gumroad.com/). All 1st party creators are using his shapekey standard and it seems like a majority of the shapekeys don't get picked up by Resonite's auto detection. The reason his standard is so popular, is because he also gives a [free easy-to-add template](https://github.com/Adjerry91/VRCFaceTracking-Templates) for users.

### Describe the solution you'd like

I'd like for his shapekeys to be added to the auto detection for Resonite. He has a [comprehensive spreadsheet](https://docs.google.com/spreadsheets/d/118jo960co3Mgw8eREFVBsaJ7z0GtKNr52IB4Bz99VTA/edit#gid=0) he uses to help creators that's easy to follow

### Describe alternatives you've considered

I don't think there's other alternatives.

### Requesters

SilvyPaws

**Comment by towneh** [comment] 2024-09-16 18:52
This feature enhancement should also include a method to specify ArKit & Meta Movement blendshape usage, in addition to Unified Expressions, for eye and face tracking in Resonite too.

https://docs.vrcft.io/docs/tutorial-avatars/tutorial-avatars-extras/compatibility/overview

**Comment by ProbablePrime** [comment] 2024-09-16 19:20
I'm somewhat confused, is this not just a duplicate of #2292 ?

Jerry's work while fantastic appears to just operate on the VRCF Unified Expressions standard. Which is covered over in 2292

**Closed** 2024-10-23 03:34 UTC
Labels: duplicate, New Feature
