### ISSUE TITLE
Support other means of taking bug reports/feedback

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#1037] opened 2023-12-31 19:12 UTC
### Is your feature request related to a problem? Please describe.

I'm kind of getting tired of hearing about "I have this issue or request but I can't give feedback because I dont have/want/know how to use github"  It's unreasonable to expect users to use only this platform for giving feedback.

### Describe the solution you'd like

Means of collecting feedback/requests/issues outside of github.  Some examples include via a dedicated spot on discord, telegram, other socials, email, or even through an in-application form.  Very important that users are made aware of these means of contact, and there should be at bare minimum an in-game link(s) that can be clicked to direct to giving feedback

### Describe alternatives you've considered

I understand the value of github for issue tracking, prioritization, however the team needs to meet people where they are.

### Additional Context

zangooseoo

**Comment by Frooxius** [comment] 2023-12-31 20:43
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/965

**Closed** 2023-12-31 20:43 UTC
Labels: enhancement
