### ISSUE TITLE
Global texture limit

### ISSUE THREAD

**Issue by ErrorJan** [Yellow-Dog-Man/Resonite-Issues#1857] opened 2024-04-26 11:19 UTC
### Is your feature request related to a problem? Please describe.

When using Resonite on Linux the GPU memory gets fully used up and then the game crashes or has other issues like stops rendering altogether.
Also performance seems to increase when textures are limited to a specific size.

### Describe the solution you'd like

In the new settings menu being able to set a max texture size and anything above the resolution of a texture to be automatically scaled down clientside.
Maybe even being able to set a different max texture resolution for StaticTexture2Ds and a different resolution for RenderTextureProviders

### Describe alternatives you've considered

Using a mod to limit texture resolution. Isn't really that good of a solution, since mods can break and being able to set a max resolution in the game unmodded would be very useful.
Limiting all textures in game by either downscaling them in the StaticTexture2D or using the MaxSize field on the StaticTexture2D. Isn't practical always, since you don't always have builder in each world and you'd need to inspect every texture, even on avatars to be able to set that option.

### Requesters

ErrorJan

**Comment by jae1911** [comment] 2024-04-26 11:23
This might be a duplicate of #1658

**Comment by ErrorJan** [comment] 2024-04-26 11:25
Oh it is! I couldn't find it, when searching for it..

**Closed** 2024-04-26 11:26 UTC
Labels: enhancement
