### ISSUE TITLE
Sometimes random people's private local home sessions are showing in Active Sessions

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1359] opened 2024-02-17 02:02 UTC
### Describe the bug?

Sometimes you can see random user's private local home sessions in Active Sessions.

From what I've seen they will never have a thumbnail and will just show the "No Thumbnail" preview.

I have not tried to join one of these sessions so I don't know what would happen.

I don't know what causes it exactly but it is quite rare. I guess somehow the session is briefly set to public before being made private on launch of Resonite.

I have seen it happen for at least 5+ different random users over time.

The session does disappear after a few minutes.

### To Reproduce

Not easy to reproduce.

Rarely in Active Sessions you will see sessions named "Local" which if you click on it will be set to private access level, and it will be a random user - you don't even need to be contacts with them.

### Expected behavior

Private local home sessions never show in Active Sessions.

### Screenshots

![Screenshot 2024-02-17 032539](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/577e0053-ce23-457f-b3be-656bccaba8ad)

### Resonite Version Number

Beta 2024.2.12.1430

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[DESKTOP-H976HO2 - 2024.2.12.1430 - 2024-02-17 01_38_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14317343/DESKTOP-H976HO2.-.2024.2.12.1430.-.2024-02-17.01_38_07.log)

In this log file the relevant line is this, which shows the "Local" session info being received:

`SessionInfo. Id: S-3004be6a-8f20-4d1c-b2d3-86587c08fd69, Name: Local, Host: [Username Removed], CorrespondingWorldId: , URLs: res-steam://76561198181948111/0/S-3004be6a-8f20-4d1c-b2d3-86587c08fd69, lnl-nat://f4145623eceb433d90dd08e947cc0fc9/S-3004be6a-8f20-4d1c-b2d3-86587c08fd69, IsExpired: False`

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by Chundelac** [comment] 2024-02-19 18:14
I can confirm this issue exists but it is rare. It is not possible to join these sessions.
Happens with no mods installed as well.

**Comment by Chundelac** [comment] 2024-02-20 22:36
This is not the cloud home, but to the local black void session. I have not seen a cloud home like that.
Unsure if same or different issue.

**Comment by shiftyscales** [comment] 2024-05-03 21:00
This seems to still be an issue, @Frooxius @ProbablePrime - the new session visibility notification has made it a lot more obvious when this issue occurs.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/99ae1088-0b9d-44a8-8612-e2691e139ac3)

Note the visibility can be seen as private.

**Comment by ProbablePrime** [comment] 2024-08-15 07:49
After further research this is a duplicate of #448

**Closed by ProbablePrime** 2024-08-15 07:49 UTC
Labels: bug, triaged
