### ISSUE TITLE
Facet transforms do not properly generate for nested facets (world browser, migration, settings) if their tabs have not been viewed

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#466] opened 2023-10-29 09:21 UTC
### Describe the bug?

After starting Resonite, the "Migration" or "World" screen may be empty.

### To Reproduce

I do not know how to reproduce it reliably.
This happens sometimes after launching Resonite.

### Expected behavior

Migration" and "World" should appear correctly.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/1e8d316d-ba87-49b7-98a1-5ca0a1261c69)

### Resonite Version Number

2023.1010.1407~2023.10.20.831

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, VIVE Pro

### Log Files

[MENTAIKO_-_2023.10.10.1407_-_2023-10-12_10_59_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13197643/MENTAIKO_-_2023.10.10.1407_-_2023-10-12_10_59_14.log)

### Additional Context

If this occurs, the menu will remain blank until `-ResetDash` is used.

I previously contacted ProbablePrime about this bug.
He told me to check the userspace inspector if I encounter this problem.
The result is below.

I did an inspector check of my user space and noticed that there was nothing in the Nested children.
![2023-10-13_02 33 57](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/644dabf0-f7d1-4b04-8cd5-bba59cd42201)

Normally there should be a Slot named Facet here.
This is what it looks like in the home tab.
![2023-10-13_02 37 25](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/f4d61189-5152-4f07-b147-f4b8a4bd00f6)

I noticed that Faset itself still exists in the Facets child.

I could see this once I parented it to Root and scaled it to 1.
I was even able to grab it and paste it into the dashboard.
At this time, a Facet Slot is generated as usual under Nested.
![2023-10-13_02 39 57](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/80ade463-0891-40f2-aa2c-7075a85ce108)

### Reporters

Resonite: orange, Discord: orange3134
@Konshu
@Arcanus2112
@AxelTheAvali

**Comment by stiefeljackal** [comment] 2024-04-19 09:04
@shiftyscales I have the reproduction steps to this as the new Settings screen will also become blank in addition to the Worlds and Migrations screens.

1. Before launching the client, add the `-ResetDash` flag.
2. Launch the client.
3. Once the **Dash** opens, go to the **Exit** screen.
4. Press **Exit & Discard Homes**.
5. Remove the `-ResetDash` flag.
6. Launch the client.
7. Once the **Dash** opens, review the Worlds, Settings, and Migrations screens; these screens should be blank.

From what I have observed, it appears that the Facets for those screens do not create the required slot under **Nested** until the screen is viewed. If the user should exit a `-ResetDash` enabled client without viewing those screens, then Resonite will sync the Dash in its current state, which causes those screens to become blank. For the time being, a workaround to sync the Dash in a correct and unbroken state when adding `-ResetDash` is to view all screens first before exiting the client.

**Comment by GearBell** [comment] 2024-04-22 04:18
Having the same issue currently as well. Ive tried several rebooting, reseting, and reinstalling methods, none succeeded in fixing it. Currently I am unable to go to worlds unless I join someone or have the world orb saved.

**Comment by stiefeljackal** [comment] 2024-04-22 06:10
@GearBell There is a workaround to resolve the issue. After adding `-ResetDash` and once the Dash shows upon starting up the client, view all screens on your Dash and have them fully render. Afterwards, exit the client and allow the sync to occur if it is still pending. Remove the `-ResetDash` flag once you are done.

If you should use `-ResetDash` again, make sure to follow the instructions above.

**Comment by GearBell** [comment] 2024-04-22 06:49
> @GearBell There is a workaround to resolve the issue. After adding `-ResetDash` and once the Dash shows upon starting up the client, view all screens on your Dash and have them fully render. Afterwards, exit the client and allow the sync to occur if it is still pending. Remove the `-ResetDash` flag once you are done.
> 
> If you should use `-ResetDash` again, make sure to follow the instructions above.

I did see your suggestion and did try this to the letter and it did not work, sadly.

**Comment by stiefeljackal** [comment] 2024-04-22 07:01
@GearBell Okay. When you add `-ResetDash`, do all screens render correctly or are the affected screens not showing?

**Comment by GearBell** [comment] 2024-04-22 07:08
@stiefeljackal One out of three attempts did work yes, but then removing -ResetDash reverted it to its broken state. Even when carefully repeating the actions of one working time, it failed to work again.

**Comment by stiefeljackal** [comment] 2024-04-22 07:34
@GearBell Okay. Try this other workaround:

1. After adding `-ResetDash` and seeing the Worlds screen facets, go into UI Edit Mode (https://wiki.resonite.com/Basic_Controls#UI_Edit_Mode).
2. Take out each of the facets on the Worlds screen and put them back.
3. Exit the client.

_Note: You can do this for Migration and Settings as well if you wish._

If the above does not work, then I would wait until the bug is resolved.

**Comment by GearBell** [comment] 2024-04-24 00:01
> @GearBell Okay. Try this other workaround:
> 
> 1. After adding `-ResetDash` and seeing the Worlds screen facets, go into UI Edit Mode (https://wiki.resonite.com/Basic_Controls#UI_Edit_Mode).
> 2. Take out each of the facets on the Worlds screen and put them back.
> 3. Exit the client.
> 
> _Note: You can do this for Migration and Settings as well if you wish._
> 
> If the above does not work, then I would wait until the bug is resolved.

This has worked, thank you!

**Comment by MahSandwich** [comment] 2024-04-26 09:58
This might also be occurring when an update affects content on a given tab and that tab is not opened on the following session.

**Comment by stiefeljackal** [comment] 2024-05-05 23:17
@shiftyscales I would like to suggest updating the title of this issue to remove the "after the dash is reset" part. Although `-ResetDash` helps produce a pristine dash, the actual cause of this is due to Resonite systematically marking the Dash as modified.

When either `-ResetDash` is used or when Resonite determines that the Dash needs an update after a new version is released (i.e. the new Settings update), Resonite will systematically mark the dash as modified. When this occurs, there is a 60 seconds time limit before Resonite will automatically save and sync the dash at its current state (logging out or closing Resonite will bypass the wait and perform these operations automatically). Once those 60 seconds have passed, the Dash will save and sync with the unrendered screens, and the only way to fix this is if you modify the Dash via Edit UI after viewing those screens.

**Comment by shiftyscales** [comment] 2024-05-05 23:39
Thanks for the additional context, @stiefeljackal. Still seeking input from @Frooxius - this particular issue has been fairly disruptive for users that run into it.

**Comment by stiefeljackal** [comment] 2024-05-05 23:48
You're welcome, @shiftyscales. I have been meaning to propose that change.

Also, as you have suspected, the Home screen is affected by this too. Although it is the first screen viewed upon launching Resonite, if you perform `-ResetDash` and quickly close the client before the Dash is shown, then it will save and sync with an unrendered Home screen.

**Comment by zahndy** [comment] 2024-05-12 11:31
I added some facets to the Home screen. Since then my Settings and Migration screens have been blank.
[2024.5.7.505 - 2024-05-12 13_23_52.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15286036/2024.5.7.505.-.2024-05-12.13_23_52.log)

**Comment by stiefeljackal** [comment] 2024-05-12 11:50
> I added some facets to the Home screen. Since then my Settings and Migration screens have been blank.
> [2024.5.7.505 - 2024-05-12 13_23_52.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15286036/2024.5.7.505.-.2024-05-12.13_23_52.log)

Have your Migration and Settings screens been blank previously when you attempted to place the facets?

Placing facets on the Home Screen won’t address the blank screens unless you perform a -ResetDash, view the screens that are affected by this, and add any facets within that same session.

**Comment by Frooxius** [comment] 2024-05-30 01:23
This should be fixed in 2024.5.30.68. Thanks for the report!

**Closed by Frooxius** 2024-05-30 01:23 UTC
Labels: bug, triaged
