### ISSUE TITLE
Component FindParentByTag or FindParentByName crash client

### ISSUE THREAD

**Issue by demonzla** [Yellow-Dog-Man/Resonite-Issues#89] opened 2023-10-13 23:46 UTC
### Describe the bug?

Use RootSlot as parametr in component FindParentByTag or FindParentByName crash client if user try take result.

### To Reproduce

1. Create node FindParentByTag
2. Create node RootSlot
3. link RootSlot to FindParentByTag
4. Try take result from output in node FindParentTag

### Expected behavior

At the moment of trying to get the result, the user's client loses connection to the current session and the user ends up in his local session.

### Screenshots

![2023-10-13 21 55 07](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/13164700/984e0275-525a-4a41-ae79-66d2102eca35)

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Oculous

**Comment by shadowpanther** [comment] 2023-10-13 23:51
Duplicate #56 (that one has log)

**Comment by ProbablePrime** [comment] 2023-10-13 23:52
Thank you for making this bug, Shadowpanther is correct this is a duplicate of #56 so I will be closing this one.

**Closed by ProbablePrime** 2023-10-13 23:52 UTC
Labels: bug
