### ISSUE TITLE
Headless not loading worlds or Commands

### ISSUE THREAD

**Issue by Readun** [Yellow-Dog-Man/Resonite-Issues#2549] opened 2024-07-12 07:07 UTC
### Describe the issue.

When I try to use the same config as on my normal Headless, the new .Net Headless is not able to finish starting up.
It stays in an unfinished startup phase.

If I just use the Default config it seems to load quick.

It only posts "Session updated, forcing status update" every couple minutes. Im not able to put in any commands aswell in that state. Closing it via X is working.

### To Reproduce

Loading my usual config with 3 Worlds.

### Expected behavior

It should boot up normally, like it does with the old Headless client.

### Screenshots

![grafik](https://github.com/user-attachments/assets/24981c82-babc-4731-b4a4-645dbd306cc4)

### Resonite Version Number

Beta 2024.7.12.12

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Headless (Windows GUI)

### Log Files

[READUNSERVER - 2024.7.12.12 - 2024-07-12 08_54_01.log](https://github.com/user-attachments/files/16189879/READUNSERVER.-.2024.7.12.12.-.2024-07-12.08_54_01.log)

### Additional Context

Same happens when trying to load a singular, different world too.
.Net 8.0.6 seems to be installed.

### Reporters

readun

**Comment by Readun** [comment] 2024-07-12 07:10
Aaah damn, miight be a duplicate of: #2541 ?

**Comment by bredo228** [comment] 2024-07-12 07:14
> Aaah damn, miight be a duplicate of: #2541 ?

Seems like it, that looks like the same issue I've been seeing

**Comment by Frooxius** [comment] 2024-07-12 15:59
Can you try with 2024.7.12.933? It might be due to some of the other stuff that got fixed.

**Comment by KyuubiYoru** [comment] 2024-07-12 16:39
With 2024.7.12.933 the headless works in a Linux Docker with mcr.microsoft.com/dotnet/runtime:8.0 as base image, before i had to use mcr.microsoft.com/dotnet/aspnet:8.0

**Comment by shiftyscales** [comment] 2024-07-12 16:41
Can you confirm the issue as resolved too, @Readun @bredo228? I'll close for now, as it seems this issue is resolved- particularly if it is indeed a duplicate of #2541.

**Closed by shiftyscales** 2024-07-12 16:41 UTC
Labels: duplicate, prerelease

**Comment by Readun** [comment] 2024-07-12 19:49
> Can you confirm the issue as resolved too, @Readun @bredo228? I'll close for now, as it seems this issue is resolved- particularly if it is indeed a duplicate of #2541.

Yes, the last update fixed it, it was a duplicate indeed.
