### ISSUE TITLE
seperate user and world space if possible.

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2910] opened 2024-09-10 04:29 UTC
### Is your feature request related to a problem? Please describe.

while playing resonite, there are times where the game hit's so low of a fps count that typing in resonite is painfull.

### Describe the solution you'd like

with the proformance update or updates we are getting, is it possible to seperate user and world space on a per thread basis?

this would allow the dashboard to run at 60/90fps so that people can type in virtual reality, the dashboard to not be slow and for users to have smooth frame rates in userspace, kind of like another instance running.

### Describe alternatives you've considered

creating a mod that seperates user and word space over threads or implementing Process based Architecture for userspace.

### Additional Context

though, if the #706 does arrive, then i think this request does get added through PBA.

### Requesters

charlie_san on resonite and discord.

**Comment by ProbablePrime** [comment] 2024-09-10 04:36
Thanks for logging an issue, I'll unfortunately be closing this one as a duplicate of #706 as it does form an overlap

Additionally, and as a reminder:
1. ["Focus on the high-level issue first, not a specific solution"](https://github.com/Yellow-Dog-Man/Resonite-Issues#reporting-requirements)
2.  [Do not request overhauls of systems, focus on the bugs or features you want](https://github.com/Yellow-Dog-Man/Resonite-Issues#reporting-requirements

In this case I feel you're too focused on your intended solution(run userspace on a separate thread). Your actual issue should be a bug and be:
"When a world I am in experiences lags/hitches/poor performance, it also affects the dash..."

**Closed by ProbablePrime** 2024-09-10 04:36 UTC
Labels: enhancement

**Comment by Frooxius** [comment] 2024-09-10 04:44
I'd also like to add info, that what you are asking for isn't entirely possible, at least not the way you're asking for it.

Separating things on multiple threads won't really help you run dashboard at 60/90 FPS (or whatever the headset is) - you still need to render it on the GPU, which is a shared resource - and it needs to render everything at once - world + dashboard.

A potential solution will be if the whole rendering is separate as an overlay, but that does require #706 to go through and it might not be feasible either - we'll need to do more research there.

**Comment by charlie-sans** [comment] 2024-09-10 04:45
it;s more of a idea at this moment
