### ISSUE TITLE
Move ValueUserOverride target field back to the top

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2226] opened 2024-06-03 12:52 UTC
### Is your feature request related to a problem? Please describe.

The value gradient drivers Target Field used to be at the top of the component it's now lower for some reason

### Describe the solution you'd like

I would like the value gradient driver target to be placed back where it was before

### Describe alternatives you've considered

Not doing this but why?
and if this was intentional why was it moved it seems like a really unnecessary change that just harms workflow

### Additional Context

I noticed the Target Field moved when the ValueUserOverrideGather was implemented

this is how it looks now
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/8c482656-9fb5-48f8-a57b-fde9d6af2983)

how it looked previously and how I want it to look now
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/6dddd181-655e-4590-8170-cb4247be6f2a)

### Requesters

@epicEaston197

**Comment by Banane9** [comment] 2024-06-03 14:29
> I noticed the Target Field moved when the ValueUserOverrideGather was implemented

This is actually the cause, as that addition seems to have introduced a base class for ValueUserOverrides, which contains everything except the Target field - and the fields of derived classes are placed after those of base classes.

**Comment by Frooxius** [comment] 2024-06-03 15:45
We do not intentionally move the fields around or position them in the first place - this is fully automated process.

This is a side effect of restructuring the code to allow for new functionality.

Just moving the field is non-trivial since we don't have mechanism to specify the order of fields in the inspector, this is something we'd need to implement first.

**Comment by shiftyscales** [comment] 2024-06-03 17:09
Closing as not planned. Time spent incrementally improving the existing inspector would probably be better handled by the inspector rework instead #563.

**Closed by shiftyscales** 2024-06-03 17:09 UTC
Labels: enhancement
