### ISSUE TITLE
Headless user appearing offline when it's online, session missing from the World Browser

### ISSUE THREAD

**Issue by bontebok** [Yellow-Dog-Man/Resonite-Issues#3325] opened 2024-12-09 00:12 UTC
### Describe the bug?

Sometime around Halloween, we started noticing that sometimes headless servers running under Linux would appear offline in the Contacts list even though they were online and running. The server operates just fine and can even send out invites, acting almost like it was operating offline, but there is no setting for the headless client to set the user offline.

When the server appears offline, it will never come back online until it is reset. It will show offline for the entire duration of the session. This has lead to lower turnout for Creator Jam due to the session not being visible in the World Browser.

### To Reproduce

Start a Linux based headless server and set the world to Anyone and do not hide from listing. Try to locate the user in your Contacts or look for the session in the World Browser.

### Expected behavior

The headless server user should appear online when operating and open/visible sessions should appear in the World Browser.

### Screenshots

Screenshot showing Creator Jam offline, when in fact it was online and hosting Creator Jam:
![Image](https://github.com/user-attachments/assets/2dd78386-1251-4e76-be46-b55deca08612)

Screenshot showing that there are 6 active users in the Creator Jam Hub world:
![Image](https://github.com/user-attachments/assets/ff17d846-72e3-497e-93df-aa5d2c9170e8)

Screenshot showing that the Creator Jam Hub world is not visible in the World Browser: 
![Image](https://github.com/user-attachments/assets/f159a4e4-d3b5-4a3b-8ae6-0d2997c42eda)

Screenshot showing the status output from the console showing that the world is in fact open and not hidden from listing.
![Image](https://github.com/user-attachments/assets/4433fff5-25be-4a19-b282-f5072c28ec9f)

### Resonite Version Number

Beta 2024.12.2.1188 (Headless Client)

### What Platforms does this occur on?

Linux

### What headset if any do you use?

N/A

### Log Files

[headless - 2024.12.2.1188 - 2024-12-08 04_50_05.log](https://github.com/user-attachments/files/18054653/headless.-.2024.12.2.1188.-.2024-12-08.04_50_05.log)

This log was from last night when the server was appearing offline.

### Reporters

Rucio, StiefelJackal, BigMrRaccoon

**Comment by shiftyscales** [comment] 2024-12-09 01:18
As a sanity check, could you sign in to the account hosting the headlesses and ensure that it is not currently set to invisible as its default status / remembered status, @bontebok?

**Comment by bontebok** [comment] 2024-12-09 02:03
> As a sanity check, could you sign in to the account hosting the headlesses and ensure that it is not currently set to invisible as its default status / remembered status, [@bontebok](https://github.com/bontebok)?

That's an interesting hypothesis. After the jam closes, I will do this and see what the default is. Thanks!

**Comment by bontebok** [comment] 2024-12-09 02:37
> > As a sanity check, could you sign in to the account hosting the headlesses and ensure that it is not currently set to invisible as its default status / remembered status, [@bontebok](https://github.com/bontebok)?
> 
> That's an interesting hypothesis. After the jam closes, I will do this and see what the default is. Thanks!

![Image](https://github.com/user-attachments/assets/9fbe958a-a43f-40e3-b8e3-2ac990a77c6e)

That looks like that's **exactly** what's happening. I tested another headless account that was correctly showing online. I logged out of my user account and logged in with the headless user, and then toggled to Invisible. I then logged out of the headless account and started the headless client back up and that account showed as Offline/Invisible.

I was able to move the account back to an Online status by performing the same steps above, except flipping the status from Invisible back to Online.

Good job Shifty!!

Rucio

**Comment by shiftyscales** [comment] 2024-12-09 03:17
Thanks for looking further into it, @bontebok. Based on that- this sounds like it is not a bug- so I will be closing this issue. I'd recommend you follow up by creating a feature request for a command / mechanism to set the online status from the headless client, and highlight the circumstance you ran into here.

**Closed by shiftyscales** 2024-12-09 03:17 UTC
Labels: bug, needs more information
