### ISSUE TITLE
Pictures take forever to load

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#1045] opened 2024-01-02 10:09 UTC
### Describe the bug?

Once upon a time, taking a picture (either finger photo, Shift+P or the Reso Essentials camera) was instant.
Now it takes like 30+ second for pictures to appear and for the steam screenshot to be taken.

### To Reproduce

1. Start Resonite
2. Press Shift+P
3. Wait for your steam screenshot and for your photo to appear

### Expected behavior

1. Start Resonite
2. Press Shift+P
3. The steam screenshot gets taken and the photo appears 

### Screenshots

Still waiting for them to load.

### Resonite Version Number

Beta 2023.12.21.1127

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive, Desktop, others

### Log Files

I am not comfortable providing log files, especially for issues this easily replicated.

### Reporters

U-Psychpsyo on Resonite, cameron5 on Discord

**Comment by Frooxius** [comment] 2024-01-02 10:15
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/874 and https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/871

**Closed by Frooxius** 2024-01-02 10:15 UTC
Labels: bug
