### ISSUE TITLE
Groups with spaces in name show quoted in Inventories view

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#1300] opened 2024-02-04 23:05 UTC
### Describe the bug?

Created a group via the command `/createGroup "Critter Creations"`, as noted on the wiki https://wiki.resonite.com/Resonite_Bot#Group_Commands

In the UI, it displays including the quotes:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/5a070611-9bab-4d87-a35f-bdf500132641)

### To Reproduce

Create group with spaces in name, quoted as the wiki instructs

### Expected behavior

Group name should not display surrounding quotes in UI

### Resonite Version Number

Beta 2024.2.2.1015

### What Platforms does this occur on?

Windows, Linux

### Log Files

n/a

### Reporters

zangooseoo

**Comment by gentlecolts** [comment] 2024-02-04 23:18
Also seems like a lot of commands don't work with the quoted name, and have to use the group ID instead

**Comment by gentlecolts** [comment] 2024-02-10 03:09
> I believe this is because you created the group with quotation marks

I was following the bot command documentation on the wiki, which quoted the name in its example.  If this is incorrect the wiki should probably updated

**Comment by liny-fox** [comment] 2024-02-10 04:39
Duplicate of 482

**Comment by gentlecolts** [comment] 2024-02-10 07:40
Good catch, the wiki definitely needs updating since that's the example they give

**Comment by ProbablePrime** [comment] 2024-02-10 08:57
https://wiki.resonite.com/index.php?title=Resonite_Bot&diff=prev&oldid=75310

wiki is updated.

**Closed** 2024-02-10 08:57 UTC
Labels: bug
