### ISSUE TITLE
[UI / UX] Loading Indicator doesn't show the World Name when triggered from a World Orb

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#2284] opened 2024-06-11 00:25 UTC
### Describe the bug?

A minor visual bug occurs when you open a world from an orb (Specifically a world orb, not from the Worlds tab), the loading indicator won't populate with the actual title of the session or world. Instead just showing "World Name" until the newly loaded world is focused.

### To Reproduce

Open a world from a World Orb.
Observe the loading indicator that appears and only says "World Name".
The loading indicator only shows the name of the world once the world is focused. 

### Expected behavior

The loading indicator should always have the world name or session title appear when visible.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/05369168-63a2-4fd8-a267-c42a2c30108f

(Video showcasing the visual bug only appearing when the same world is opened from an orb, only appearing for a moment before the world switches)

### Resonite Version Number

Beta 2024.6.10.1405

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Meta Quest 3 (SteamLinkVR) + Desktop

### Log Files

[MANGOVRG - 2024.6.10.1405 - 2024-06-10 17_11_11.log](https://github.com/user-attachments/files/15780372/MANGOVRG.-.2024.6.10.1405.-.2024-06-10.17_11_11.log)
(This log isn't as clean as it could be, as I went to try and see if I could replicate it with other world types, but it's only World orbs that cause the visual bug)

### Additional Context

This issue has been around for quite a while, likely as far back as [Beta 2024.4.15.1407](https://wiki.resonite.com/Beta_2024.4.15.1407)
It's only been reported now as a new user pointed it out to me, which encouraged me to write the report on this small bug.

### Reporters

@zyro1331

**Comment by Zyro1331** [comment] 2024-06-11 04:16
Huh, apparently trying to join a contact from the Contacts list also triggers this same issue.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/da3ff6cb-8259-424b-bd3e-8cb508391671)

**Comment by ProbablePrime** [comment] 2024-06-11 04:17
Been planning to fix this for a few weeks. Thank you!

**Comment by ProbablePrime** [comment] 2024-08-06 05:20
I was unable to reproduce this today, except for joining from the Contacts screen which narrows it down yay.

**Comment by ProbablePrime** [comment] 2024-08-06 05:49
Turns out the world name would not appear in the following circumstances:
1. Anything using SessionInfoSource
2. When using a WorldOrb's CustomWorldStart Sync Method
3. When opening a world orb that has no StartSettings
4. When joining from a Contacts screen user. With the join button within a contact on the Contacts Screen
5. When joining from a Session Invite from a Contact. With the join button within that session Invite.

I'm fixing those up, so look out for it in the change logs soon!

**Comment by ProbablePrime** [comment] 2024-08-15 07:21
I wanted to add some extra notes from taking an additional look today.

I found the reason why this is so unreliable to test and look at. It's based on how fast the world / session loads. Before the fixes here, in the cases from the list above the world name would be blank until a certain point in the world loading process where it would receive the name and update it.

If the world loads fast enough for the name to make it in, then you don't see "World Name"
If the world loads slowly for any reason, then you see "World Name" until the end. Or as Zyro put it "only appearing for a moment before the world switches"

The fix for this basically ensure that in all possible places where we know the world name ahead of time(literally all of the items in this list + more), we hand the world name to the world loading process.

This may also help with debugging #448 as its a similar sort of thing, so I'll be reviewing the loading area some more looking for similar issues in the access level.

**Comment by ProbablePrime** [comment] 2024-08-15 07:46
Yeah #448 is an identical issue >.< Ill post some notes there in a moment.

**Comment by Frooxius** [comment] 2024-09-04 07:13
Merged fix in 2024.9.4.357, thanks!

**Closed by Frooxius** 2024-09-04 07:13 UTC
Labels: bug, triaged
