### ISSUE TITLE
Contact status glitch

### ISSUE THREAD

**Issue by Krzeszny** [Yellow-Dog-Man/Resonite-Issues#2234] opened 2024-06-04 15:06 UTC
### Describe the bug?

Contacts sometimes appear as offline for several seconds, or the session info can be out of date.

### To Reproduce

Notice how every once in a while your contacts appear as offline even if they're actually online, which fixes itself after several seconds, or the session status doesn't match the actual session.

### Expected behavior

Not having this issue...

### Resonite Version Number

2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Reverb G2

### Log Files

n/a

### Additional Context

My theory for this behavior is packet loss.

### Reporters

krzeszny
karasutengu

**Comment by JackTheFoxOtter** [comment] 2024-06-04 15:10
Duplicate of #739, as Froox stated there:
> I think this should be fixed with 2024.5.30.68 now. But keep a lookout on it.
> I'm going to close it now. If it still occurs, we'll reopen.

So I assume it's still happening and the issue might need to be re-opened.

**Comment by shiftyscales** [comment] 2024-06-04 18:18
Re-opened the existing issue #739 for now, but we definitely need more information including log files in order to investigate this, @Krzeszny.

**Closed by shiftyscales** 2024-06-04 18:18 UTC
Labels: bug

**Comment by Krzeszny** [comment] 2024-06-06 05:57
> That said, a log is necessary, as well as information which contact incorrectly appeared offline at which time.

I can imagine that, but I couldn't reproduce it.
