### ISSUE TITLE
World crashes when creating a Data Model Store for GUID.

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#467] opened 2023-10-29 13:54 UTC
### Describe the bug?

When I connect a Random GUID to the Write node and create a Data model store from the Write node, the world crashes.

### To Reproduce

1. "Random GUID" and "Write" from the ProtoFlux node browser.
2. Connect the Random GUID to the Value of Write.
3. While grabbing Variable, open the context menu and create a Data Model Store.
4. World crashes.

### Expected behavior

The world should not crash.

### Resonite Version Number

2023.10.20.831

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, VIVE Pro

### Log Files

[MENTAIKO - 2023.10.20.831 - 2023-10-29 22_44_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13198233/MENTAIKO.-.2023.10.20.831.-.2023-10-29.22_44_36.log)

### Reporters

orange3134, zozokasu

**Comment by Frooxius** [comment] 2023-11-13 22:35
This has been fixed in 2023.11.13.1343, thank you!

The issue is that GUID is not a valid generic type for this, but ProtoFlux tool would create it anyway, which would cause other parts of the system to crash.

**Closed by Frooxius** 2023-11-13 22:35 UTC
Labels: bug
