### ISSUE TITLE
better method calls / protoflux template nodes.

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2045] opened 2024-05-17 09:51 UTC
### Is your feature request related to a problem? Please describe.

so, if none of the good things are going to be added to resonite which i'm not mad about. you know, things take time. 

with method call nodes, you can only get them when you grab a method from a inspector and hit drive in your context menu. 
from there you can provide what it want's and it will run the method and do something.
though there is no way of having the node's method type changeable so you can choose what method you want and if it returns something, to have a output you can use. 

### Describe the solution you'd like

a node or set of nodes that provide the ability to call methods that the game has access to, such as a frooxengine.protoflux call that allows for the user to spawn protoflux from the type name that is just abundant at this point with the ability to have a method that can return something have the access to output it back into protoflux.

### Describe alternatives you've considered

i might just make a mod or plugin which generates templates or allows to call a function which can be used within a protoflux node that allows the return value to be used like a read dynamic varible or value node in protoflux.

### Additional Context

this would be good as we could access the system calls from system.string to do things like string parsing and manipulation directly in resonite, better protoflux browsers that we can actually make instead of modifying the original one that the game gives us when we open the browser.

### Requesters

charlie_san

**Comment by Frooxius** [comment] 2024-05-17 19:01
I don't really understand what exactly do you want here.

Any callable methods in the FrooxEngine you can already call with ProtoFlux, by grabbing the proxy to that method in the inspector, opening context menu and clicking "Proxy".

How is this different from that functionality?

**Comment by lxw404** [comment] 2024-05-18 04:20
This is quite confusing to read and probably against the [best practices](https://github.com/Yellow-Dog-Man/Resonite-Issues/blob/main/README.md).  It might be best to read those carefully and thoroughly before proceeding with creating additional issues.

Then in the future you might approach creating an issue by:

1. First search for existing issues which may address the problem you're having.
2. Ask in the [official discord](https://discord.gg/resonite) about the problem as many people there will be willing to help solve it, or you may even learn new terminology which may aid your search.
3. If and only if this is not satisfied by an existing issue and no solution currently exists, then you might consider opening a new issue describing a single specific problem you're trying to solve, excluding any of your own interpretations of what the solution to the problem is.

There's no need for hostility or offhanded remarks.

What I believe you're conflating here are two things: [Nested Nodes](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/564), and [Method Proxies](https://wiki.resonite.com/ProtoFlux:Method_Proxy); and then also tangentially invoking [string](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1572) [manipulation](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/403).

**Comment by charlie-sans** [comment] 2024-05-18 04:42
> I don't really understand what exactly do you want here.
> 
> Any callable methods in the FrooxEngine you can already call with ProtoFlux, by grabbing the proxy to that method in the inspector, opening context menu and clicking "Proxy".
> 
> How is this different from that functionality?

the method call nodes we have are great and all, it's just there is no way to use a function/method if it has a return type. 

say i write a simple add function.

`int add(int a, int b)
{
 return a + b
}
`
and i want to call it in the protoflux and get the return value of both the ints.
well, i don't seem to think you can do it with the current implmentation of the method nodes.

**Comment by lxw404** [comment] 2024-05-18 04:54
It probably would be a good idea to read those links I provided in the previous post.  [Nested Nodes](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/564) is what you are conflating with [Method Proxies](https://wiki.resonite.com/ProtoFlux:Method_Proxy) and [Function Proxies](https://wiki.resonite.com/ProtoFlux:Function_Proxy).

The latter two exist already and can be utilized in ProtoFlux directly, but cannot be edited as they refer to internal engine level functions.

The former refers to the expanded ability to create ProtoFlux nodes which have nested functionality similar to functions in traditional languages that are user-defined.

**Comment by ProbablePrime** [comment] 2024-05-18 04:57
Aggreed, Charlie, you're looking for Nested Nodes of the other items @lxw404 asked for.

Closing as duplicate.

**Closed by ProbablePrime** 2024-05-18 04:57 UTC
Labels: enhancement, needs more information
