### ISSUE TITLE
New supporter badge should be unlit for consistency

### ISSUE THREAD

**Issue by EuphieEuphoria** [Yellow-Dog-Man/Resonite-Issues#2961] opened 2024-09-15 19:18 UTC
### Describe the Underlying Issue

The new supported badge was implemented using a PBS metallic material to mimic the appearance of a gold coin or token. This achieves its purpose but it detracts from the visual clarity of the badge and appears less than ideal in certain lighting situations

### Expected Behavior

The badge should be consistent to other badges and use a flat, unlit sprite.

### Reporters

@EuphieEuphoria @AlphaNeon

**Comment by shiftyscales** [comment] 2024-09-15 19:27
Duplicate of #2954.

**Closed by shiftyscales** 2024-09-15 19:27 UTC
Labels: content
