### ISSUE TITLE
Dash OverRender

### ISSUE THREAD

**Issue by Scrapper1824** [Yellow-Dog-Man/Resonite-Issues#2116] opened 2024-05-27 23:02 UTC
### Is your feature request related to a problem? Please describe.

the dash doesnt OverRender making it hard to see or use when something is around you and seeing the is the tool that lets you leave the game this would be very nice

### Describe the solution you'd like

i was hoping you could make the dash OverRender so it can be obstructed and still see and use it

### Describe alternatives you've considered

N/A

**Comment by lxw404** [comment] 2024-05-28 00:15
This is a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1038.

**Comment by Frooxius** [comment] 2024-05-28 17:56
Yes this is a duplicate.

**Closed by Frooxius** 2024-05-28 17:56 UTC
Labels: duplicate, enhancement
