### ISSUE TITLE
Can see mutual blocked users name tags

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#2097] opened 2024-05-25 21:45 UTC
### Describe the bug?

Can see mutual blocked users name tags

### To Reproduce

idk 

### Expected behavior

not to see anyone

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/96900fac-44da-4257-bb5b-9cba034979ee)

### Resonite Version Number

Beta 2024.5.24.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Steam VR, Oculus

### Log Files

[Uploading SLYS-DESKTOP-PC - 2024.5.24.202 - 2024-05-24 20_11_59.log…]()

.

**Comment by jae1911** [comment] 2024-05-25 21:46
Duplicate of #1385

**Comment by shiftyscales** [comment] 2024-05-27 16:51
As reported- this is a duplicate. Closing and merging into #1385.

**Closed by shiftyscales** 2024-05-27 16:51 UTC
Labels: bug
