### ISSUE TITLE
More Dynamic Bone Colliders

### ISSUE THREAD

**Issue by rayojarr** [Yellow-Dog-Man/Resonite-Issues#1718] opened 2024-04-16 15:08 UTC
### Is your feature request related to a problem? Please describe.

I noticed that there are only spheres for dynamic bone colliders and my current system that uses them to have my tail collide with the floor and walls, but it tends to clip into the wall at a certain point of my avatar turning.

### Describe the solution you'd like

I would like to have more types of dynamic bone colliders to use.

### Describe alternatives you've considered

A good example would be using capsule colliders since that would likely fix my issue. Maybe even a flat grid that can be adjusted (Scaling and rotation)

**Comment by Frooxius** [comment] 2024-04-16 17:35
This is duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/446

**Closed by Frooxius** 2024-04-16 17:35 UTC
Labels: enhancement
