### ISSUE TITLE
Random Crashes in VR

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#2476] opened 2024-07-05 11:08 UTC
### Describe the bug?

When in VR, Desolate Divide, tends to randomly crash, it does not seem to be world dependent as far as they are aware.

### To Reproduce

We were unable to find a reliable way to cause the crash to occur, but it does not seem to happen in desktop.

### Expected behavior

Resonite should not crash.

### Resonite Version Number

Beta 2024.7.4.1347

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Meta Quest 3

### Log Files

[DESKTOP-62F66IE - 2024.7.4.1347 - 2024-07-05 04_44_14.log](https://github.com/user-attachments/files/16108854/DESKTOP-62F66IE.-.2024.7.4.1347.-.2024-07-05.04_44_14.log)
[REs Error crash files 5-15-24.log](https://github.com/user-attachments/files/16108855/REs.Error.crash.files.5-15-24.log)
[Player (1).log](https://github.com/user-attachments/files/16108856/Player.1.log)

### Additional Context

This report was made on the behalf of Desolate Divide.

### Reporters

discord and resonite username: `stellanora`

resonite username: `Desolate Divide` discord: `cobaltscyth`

**Comment by mpmxyz** [comment] 2024-07-05 18:15
This looks a lot like #269.
Your crash stack trace:
```
Stack Trace of Crashed Thread 27772:
0x00007FFFBC398F69 (d3d11) CreateDirect3D11SurfaceFromDXGISurface
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFF0053C368)
...
```

That one's stack trace:
```
Stack Trace of Crashed Thread 20644:
0x00007FFADB1A8F69 (d3d11) CreateDirect3D11SurfaceFromDXGISurface
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFA5DD7C368)
...
```

Do you or other users use RenderTransformOverride and have it set to a scale of `[0,0,0]`?
You can avoid this bug by setting it to something small but non-zero like `[0.01,0.01,0.01]`.

**Comment by Stellanora64** [comment] 2024-07-07 00:53
@mpmxyz I asked Desolate Divide and this was their response "No. One of the devs thought that might be the problem but i crash even if im logged out and just using Resonite as a guest"

**Comment by Zyro1331** [comment] 2024-07-09 09:08
This looks similar to when I had upgraded my computers RAM and enabled XMP, I kept experiencing random crashes and memory access violations across different applications until I reduced the clock speed from 3600 MHz to 3200 MHz. Could it be a hardware related issue like mine?

**Comment by Stellanora64** [comment] 2024-07-09 13:11
@Zyro1331 they said that the cashes were also happening on their old computer, which wasn't modified to have XMP enabled. And that Resonite is the only application that crashes for them

**Comment by Stellanora64** [comment] 2024-09-06 09:41
hey @shiftyscales , Desolate Divide (the user these crashes are happening to) would like to know if there is any more specific info they could provide to help get this resolved?

**Comment by shiftyscales** [comment] 2024-09-06 14:49
Apologies @Stellanora64 - I must have missed the comment button at the time I last reviewed this issue. Re-checked this issue and I believe what probably triggered me to assign that label was:

> To Reproduce
> 
> We were unable to find a reliable way to cause the crash to occur, but it does not seem to happen in desktop.

Without a reliable way for the crash to occur, it's difficult to determine what the probable cause of the issue is, or how to resolve it.

I did just have another look through the Player.log and spotted something I didn't notice at the time. Just before the crash occurred we have:

```
[uDD] Reinitialize
[uDD] Reinitialized
```

This is leading me to suspect this may be the same issue as #727. Otherwise, (to my eyes at least) the crash seems pretty generic / unspecific.

If it is something that is happening consistently, the user affected could try disabling the desktop tab functionality by use of `"disableDesktop": false` in a startup config and see if the crashes stop for now.

Details on Startup Configs can be found on the wiki. https://wiki.resonite.com/index.php?title=Startup_Config_File

**Comment by Stellanora64** [comment] 2024-09-12 01:14
@shiftyscales they did some more testing and it seems that one of the recent updates (2024.9.10.682) has fixed the crashes.

They did have a secondary monitor though, and did try removing it,  but even after reconnecting it now, they have yet to crash.

So at least for them this issue is resolved, if you believe there isn't anything else in those logs to look into, it should be fine to close this issue.

**Comment by shiftyscales** [comment] 2024-09-12 19:22
Thanks for the update- I still believe this is likely the same underlying issue as #727 so I'll close this one out since the user is reportedly no longer having that issue.

**Closed by shiftyscales** 2024-09-12 19:22 UTC
Labels: bug, crash, needs more information
