### ISSUE TITLE
「Image slices as volumetric texture」 never ends.

### ISSUE THREAD

**Issue by ginjake** [Yellow-Dog-Man/Resonite-Issues#2248] opened 2024-06-06 16:19 UTC
### Describe the bug?

「Image slices as volumetric texture」
で連続写真をインポートした場合、Importが終わらない場合があります。

なお、同じファイルをNeosVRでimportしたところ問題なくimportすることが出来、
migrateでResoniteに持ってくることが出来ました。

Image slices as volumetric texture
When importing a series of photos with “Image slices as volumetric texture”, the import may not be completed.

I imported the same file in NeosVR, and it imported without any problem,
I was able to import the same file in NeosVR without any problem and bring it to Resonite by “migrate”.

### To Reproduce

下記のzipを解答し、フォルダ毎importする。
import時に「Image slices as volumetric texture」 を選択
VolumeUnlitMaterialとSlicerは生成されるが、何も生成されない。
しばらく待ってもimport中のメッセージが消えない
[MRIImport.zip](https://github.com/user-attachments/files/15651055/MRIImport.zip)

Answer the following zip file and import the whole folder.
Select “Image slices as volumetric texture” when importing.
VolumeUnlitMaterial and Slicer are generated, but nothing is generated.
The message “importing” is not disappearing even after waiting for a while.

### Expected behavior

The VolumeUnlitMaterial object is displayed
(Image from NeosVR)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/16838187/ae5f3a6c-567b-4fb7-9c02-b04ef6d1177f)

### Screenshots

VolumeUnlitMaterial and Slicer are generated, but nothing is generated.
The message “importing” is not disappearing even after waiting for a while.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/16838187/130c4e8e-1b9d-499c-95d9-4e822b734550)

### Resonite Version Number

2024.6.5.1084

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-M5QK91C - 2024.6.5.1084 - 2024-06-07 01_16_39.log](https://github.com/user-attachments/files/15653823/DESKTOP-M5QK91C.-.2024.6.5.1084.-.2024-06-07.01_16_39.log)

**Comment by shiftyscales** [comment] 2024-06-06 16:31
This seems to be a duplicate of #1186, @ginjake.

**Closed by shiftyscales** 2024-06-06 16:31 UTC
Labels: bug, duplicate
